Catrobat/Catroid

- catroidTest/src/org/catrobat/catroid/test/physics/actions/SetSizeToActionTest.java
Now checking whether size actually changed
Also checking whether circumference is being re-calculated and is correct size (currently with rather large margin for error due to Catroid <-> Box2D conversion inaccuracies)
Testing setting size to larger, smaller, same and zero scale/size
> Tests updated / expanded

- catroidTest/src/org/catrobat/catroid/test/io/XStreamToSupportCatrobatLanguageVersion092AndBeforeTest.java
seems to be a problem with: BrickValueParameterTest.testSoundBricksDefaultValues, everything in the Jenkins run: https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/697/
> rebased/updated languageTest

- catroidTest/src/org/catrobat/catroid/uitest/content/brick/LedBrickTest.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/VibrationBrickTest.java
Remove setUp and tearDown from VibrationBrick and LEDBrick, because the Arduino is not connected to Jenkins.
> remove init of VibrationBrick and LEDBirck

- config/checkstyle.xml
introduced the lint rules as specified by Robert (in Jira), did not cause any problems, Jenkins run still pending ...
> CAT-1255 introduced rules

- catroid/src/org/catrobat/catroid/common/Constants.java
- catroid/src/org/catrobat/catroid/content/Project.java
- catroid/src/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/org/catrobat/catroid/stage/PreStageActivity.java
- catroidTest/src/org/catrobat/catroid/test/io/StorageHandlerTest.java
added Project.getRequiredResources for reading the resources required by the current Project which is saved in saveProject and write those permissions as String to an additional file.
> CAT-1301_permissions

- build.gradle
Guava library update from 17.0 to 18.0
> Guava library update

- build.gradle
- catroid/src/org/catrobat/catroid/bluetooth/ConnectBluetoothDeviceActivity.java
- catroid/src/org/catrobat/catroid/soundrecorder/SoundRecorderActivity.java
- catroid/src/org/catrobat/catroid/stage/PreStageActivity.java
- catroid/src/org/catrobat/catroid/stage/StageActivity.java
- catroid/src/org/catrobat/catroid/transfers/ProjectDownloadService.java
- catroid/src/org/catrobat/catroid/transfers/ProjectUploadService.java
- catroid/src/org/catrobat/catroid/transfers/RegistrationTask.java
- catroid/src/org/catrobat/catroid/ui/BaseActivity.java
- catroid/src/org/catrobat/catroid/ui/WebViewActivity.java
- catroid/src/org/catrobat/catroid/ui/dialogs/NewDataDialog.java
- catroid/src/org/catrobat/catroid/ui/dialogs/OverwriteRenameDialog.java
- catroid/src/org/catrobat/catroid/ui/dialogs/RenameLookDialog.java
- catroid/src/org/catrobat/catroid/ui/dialogs/RenameSoundDialog.java
- catroid/src/org/catrobat/catroid/ui/dialogs/StageDialog.java
- catroid/src/org/catrobat/catroid/ui/dialogs/UploadProjectDialog.java
- catroid/src/org/catrobat/catroid/ui/fragment/AddBrickFragment.java
- catroid/src/org/catrobat/catroid/ui/fragment/BackPackSoundFragment.java
- catroid/src/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroid/src/org/catrobat/catroid/ui/fragment/LookFragment.java
- catroid/src/org/catrobat/catroid/ui/fragment/ProjectsListFragment.java
- catroid/src/org/catrobat/catroid/ui/fragment/ScriptFragment.java
- catroid/src/org/catrobat/catroid/ui/fragment/SpritesListFragment.java
- catroid/src/org/catrobat/catroid/utils/CopyProjectTask.java
- catroid/src/org/catrobat/catroid/utils/ToastUtil.java
- catroidSourceTest/src/org/catrobat/catroid/test/code/SystemOutTest.java
- catroidTest/src/org/catrobat/catroid/uitest/formulaeditor/FormulaEditorEditTextTest.java
Added ToastUtil, and change all Toasts.
Testrun: https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/1010/
> Added ToastUtil, and change all Toasts to SuperToasts

- catroid/src/org/catrobat/catroid/formulaeditor/InternFormula.java
- catroid/src/org/catrobat/catroid/formulaeditor/InternFormulaUtils.java
- catroidTest/src/org/catrobat/catroid/test/formulaeditor/InternFormulaTest.java
fix by when insert operator into number， divide the number into two new number token
> fix issue CAT-1061

- catroid/src/org/catrobat/catroid/content/bricks/AddItemToUserListBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/ChangeVariableBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/DeleteItemOfUserListBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/InsertItemIntoUserListBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/ReplaceItemInUserListBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/SetVariableBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/UserListBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/UserVariableBrick.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/AddItemToUserListTest.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/ChangeVariableTest.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/DeleteItemOfUserListTest.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/InsertItemIntoUserListTest.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/ReplaceItemInUserListTest.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/SetVariableTest.java
- catroidTest/src/org/catrobat/catroid/uitest/stage/BroadCastReceiverRegressionTest.java
[Test green](https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/1072/)
> Baseclass for UserList- and UserVariableBricks

- build.gradle
- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroidCucumberTest/src/org/catrobat/catroid/test/cucumber/MainMenuSteps.java
change minSDK to 16, compile-, build- and targetSdkVersion to 21 and removed the @deprecated lines.
Green run:
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/1325/
> change minSDK to 16, compile-, build- and targetSdkVersion to 22

- catroidTest/src/org/catrobat/catroid/test/facedetection/StageActivityFaceDetectionTest.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/PointToBrickTest.java
Fixes 2 jenkins-test-aborting issues!  [Test ![Green](https://jenkins.catrob.at/static/a6652cc0/images/24x24/blue.png)] (https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/1418/)
> Mr. Jenkins does not like red eggs! He prefers green ones :)

- catroid/src/org/catrobat/catroid/devices/mindstorms/nxt/CommandByte.java
- catroid/src/org/catrobat/catroid/devices/mindstorms/nxt/LegoNXT.java
- catroid/src/org/catrobat/catroid/devices/mindstorms/nxt/LegoNXTImpl.java
- catroidTest/src/org/catrobat/catroid/common/bluetooth/models/MindstormsNXTTestModel.java
- catroidTest/src/org/catrobat/catroid/test/devices/mindstorms/nxt/LegoNXTImplTestWithModel.java
implemented getAlive() and getBatteryLevel()-Method + Tests
> getBatteryLevel() and keepAlive() -methods added + Tests

- catroid/res/values-de/strings.xml
- catroid/res/values/arrays.xml
- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/content/actions/LegoNxtPlayToneAction.java
- catroid/src/org/catrobat/catroid/content/bricks/LegoNxtPlayToneBrick.java
- catroid/src/org/catrobat/catroid/devices/mindstorms/nxt/LegoNXTImpl.java
- catroid/src/org/catrobat/catroid/devices/mindstorms/nxt/sensors/NXTLightSensorActive.java
- catroid/src/org/catrobat/catroid/devices/mindstorms/nxt/sensors/NXTSensorFactory.java
- catroid/src/org/catrobat/catroid/devices/mindstorms/nxt/sensors/NXTSensorService.java
- catroid/src/org/catrobat/catroid/devices/mindstorms/nxt/sensors/NXTSensorType.java
- catroidTest/src/org/catrobat/catroid/common/bluetooth/models/MindstormsNXTTestModel.java
- catroidTest/src/org/catrobat/catroid/test/devices/mindstorms/nxt/LegoNXTImplTest.java
- catroidTest/src/org/catrobat/catroid/test/devices/mindstorms/nxt/LegoNXTImplTestWithModel.java
- catroidTest/src/org/catrobat/catroid/test/devices/mindstorms/nxt/SensorTests.java
- catroidTest/src/org/catrobat/catroid/uitest/devices/mindstorms/nxt/LegoNXTImplTest.java
Added NXT sensor-type Active Light Sensor
Deactivate all sensors on stage-destroy and Mindstorm-disconnect
Fixed duration of PlayTone
> Lego NXT Active Light Sensor added

- catroid/src/org/catrobat/catroid/common/Constants.java
- catroid/src/org/catrobat/catroid/ui/WebViewActivity.java
modify UserAgent with addtional information
> CAT-1324 Set UserAgent String for Web

- catroid/src/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
> Revert "CAT-1353 fix UserBrickScriptActivityTest"

- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/content/Project.java
- catroid/src/org/catrobat/catroid/content/Sprite.java
- catroid/src/org/catrobat/catroid/content/XmlHeader.java
- catroid/src/org/catrobat/catroid/content/bricks/SetVariableBrick.java
- catroid/src/org/catrobat/catroid/formulaeditor/DataContainer.java
- catroid/src/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/org/catrobat/catroid/ui/fragment/ProjectsListFragment.java
- catroid/src/org/catrobat/catroid/utils/UtilMerge.java
- catroid/src/org/catrobat/catroid/utils/Utils.java
- catroidTest/src/org/catrobat/catroid/test/utils/TestUtils.java
- catroidTest/src/org/catrobat/catroid/uitest/content/interaction/MergeProjectTest.java
> CAT-1285 First version of the merge functionality

- catroid/src/org/catrobat/catroid/ui/WebViewActivity.java
- catroid/src/org/catrobat/catroid/utils/DownloadUtil.java
- catroid/src/org/catrobat/catroid/utils/UtilZip.java
Programs with a language version greater than 0.92 could not be downloaded.
APK button was not handled in webview.
> Fixes for download projects and apk generator

- catroid/src/org/catrobat/catroid/devices/mindstorms/nxt/LegoNXTImpl.java
- catroid/src/org/catrobat/catroid/devices/mindstorms/nxt/sensors/NXTSensorService.java
fixes a null pointer where pocket code crashed
> Fixed potential crash while sending nxt command

- catroid/src/org/catrobat/catroid/ui/WebViewActivity.java
fixes the missing file extension for standalone downloadable apk files from share.catrob.at via the PC inner WebViewActivity
> fixed missing application extension @ download standalone

- build.gradle
https://jira.catrob.at/browse/CAT-1337
> CAT-1337 Update checkstyle to 6.7

- catroid/src/org/catrobat/catroid/content/bricks/AddItemToUserListBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/BroadcastBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/BroadcastReceiverBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/BroadcastWaitBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/ChangeVariableBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/DeleteItemOfUserListBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/InsertItemIntoUserListBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/LegoNxtMotorMoveBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/LegoNxtMotorStopBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/LegoNxtMotorTurnAngleBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/PhiroIfLogicBeginBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/PhiroMotorMoveBackwardBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/PhiroMotorMoveForwardBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/PhiroMotorStopBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/PhiroPlayToneBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/PhiroRGBLightBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/PlaySoundBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/PointToBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/ReplaceItemInUserListBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/SetLookBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/SetVariableBrick.java
disabled spinner. 
Visual change: Spinner content is now grey, but should not affect usability.
> CAT-1442 hotfix for spinner appearance

- catroid/src/org/catrobat/catroid/web/ServerCalls.java
The method onReceiveResult in DownloadUtil.java will called repeatedly with old values, so i add a if-condition in the method downloadProject in ServerCalls.java and now the method onReceiveResult will called only with the newest value.
> CAT-1436 fix the bug in the method onReceiveResult

- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/formulaeditor/FormulaElement.java
- catroid/src/org/catrobat/catroid/formulaeditor/Functions.java
- catroid/src/org/catrobat/catroid/formulaeditor/InternFormulaKeyboardAdapter.java
- catroid/src/org/catrobat/catroid/formulaeditor/InternToExternGenerator.java
- catroid/src/org/catrobat/catroid/ui/fragment/FormulaEditorListFragment.java
- catroidTest/src/org/catrobat/catroid/test/formulaeditor/ParserTestFunctions.java
* Added Floor and Ceil functions along with tests.
* Removed the German Translation
Reopening of #1213 from @KKcorps. (+ Rebased, squashed, rewritten commit message .... )
First [yellow](https://jenkins.catrob.at/job/Catroid-Multi-Job-Custom-Branch-RELOADED/2042/) test-job
> CAT-1161 Add math operation for floor and ceiling

- catroid/AndroidManifest.xml
- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/common/Constants.java
- catroid/src/org/catrobat/catroid/transfers/ProjectUploadService.java
- catroid/src/org/catrobat/catroid/utils/StatusBarNotificationManager.java
- catroid/src/org/catrobat/catroid/web/ServerCalls.java
- catroidTest/src/org/catrobat/catroid/test/utils/StatusBarNotificationManagerTest.java
3 types of notifications:
1: "Retry or Cancel"
2: "Open Play Store" to update Pocket Code
3: "Open Pocket Code Program" to correct issues
> CAT-698 implemented upload notifications

- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroid/src/org/catrobat/catroid/ui/ScriptActivity.java
- catroid/src/org/catrobat/catroid/ui/dialogs/NewLookDialog.java
- catroid/src/org/catrobat/catroid/ui/fragment/LookFragment.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/SetLookBrickTest.java
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/2058/
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-CustomEmulator-Single-ClassAndPackage-Test/398/
Warnings are only for Multiline !
> Cat 1439 Fix Returning to ScriptActivity when Dismissing new Look Dialog

- catroidTest/src/org/catrobat/catroid/uitest/stage/SpeakStageTest.java
Imported refactored test
Reviewed imports
Final cleanup
> CAT-1238 Refactor SpeakStageTest

- catroid/src/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-CustomEmulator-Single-ClassAndPackage-Test/397/
> CAT-1441 Move setHasOptionsMenu call to onActivityCreated

- catroid/res/menu/context_menu_default.xml
- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/ui/fragment/LookFragment.java
- catroid/src/org/catrobat/catroid/ui/fragment/SoundFragment.java
- catroid/src/org/catrobat/catroid/ui/fragment/SpritesListFragment.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/SetLookBrickTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/fragment/LookFragmentTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/fragment/SoundFragmentTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/fragment/SpritesListFragmentTest.java
Added two tests in each class, one for moving up, one for moving down.
First test was for the Sprite List, second for Look List
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-CustomEmulator-Single-ClassAndPackage-Test/390/
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-CustomEmulator-Single-ClassAndPackage-Test/391/
> CAT-1395 Added sprites and look sorting

- catroidTest/src/org/catrobat/catroid/uitest/web/UserConceptTest.java
Removed Commenting from UserConceptTest class.
> CAT-1168 Uncommented Test

- catroid/res/values/strings.xml
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Build-SourceTests-StaticChecks/2926/
> CAT-910 Screnshot in stage is not a screenshot

- catroid/res/layout/dialog_new_sound.xml
- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroid/src/org/catrobat/catroid/ui/ScriptActivity.java
- catroid/src/org/catrobat/catroid/ui/controller/SoundController.java
- catroid/src/org/catrobat/catroid/ui/dialogs/NewSoundDialog.java
- catroid/src/org/catrobat/catroid/ui/fragment/LookFragment.java
- catroid/src/org/catrobat/catroid/ui/fragment/SoundFragment.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/PlaySoundBrickTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/activity/SoundRecorderTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/dialog/RenameSpriteDialogTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/fragment/AddBrickFragmentTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/fragment/SoundFragmentTest.java
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/2269/
All Tests pass, except for the setLookBrickTest which always fails !
> CAT-1154 Added Dialog for new Sound File:

- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/ui/dialogs/NewProjectDialog.java
- catroid/src/org/catrobat/catroid/ui/dialogs/NewSpriteDialog.java
- catroid/src/org/catrobat/catroid/utils/Utils.java
Linked with CAT-1291, CAT-1292, CAT-1293 - merged to 1 pull-request because these tickets relate to the same issue.
@thmq : please update in crowdin
> CAT-1290 Name alerts fixed

- catroidTest/src/org/catrobat/catroid/uitest/content/brick/SetLookBrickTest.java
It was requested that i fix the UserConceptTest too, but unfortunately i don't have a clue why this one is failing. I fixed the SetLookBrickTest, so it would be better to make a new Issue for the other test, maybe someone else has a fix for it.
> CAT-1438 Fix SetLookBrickTest

- catroid/src/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java
- catroidTest/src/org/catrobat/catroid/uitest/formulaeditor/FormulaEditorEditTextTest.java
https://jira.catrob.at/browse/CAT-1097
> CAT-1097 Inconsitent text highlighting in Formula Editor

- catroid/src/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/PlaceAtBrickTest.java
PlaceAtBricks with FormulaEditor
> CAT-1315 Disable undo button after switching when editing

- build.gradle
- catroid/src/org/catrobat/catroid/ui/ScriptActivity.java
- catroid/src/org/catrobat/catroid/ui/controller/LookController.java
- catroid/src/org/catrobat/catroid/ui/fragment/LookFragment.java
- catroidTest/AndroidManifest.xml
- catroidTest/src/org/catrobat/catroid/uitest/ui/fragment/LookFragmentTest.java
Fixes generation of BuildConfig after Android Studio + gradle update.
Testrun pending:
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/2461/
> Fix gradle BuildConfig logic

- catroid/src/org/catrobat/catroid/content/Project.java
- catroid/src/org/catrobat/catroid/content/XmlHeader.java
should be revised by @AdrianSch. not sure if the member variable isPhiroProject (isPhiroProProject) is needed at all.
> changed isPhiroProProject to isPhiroProject in XMLHeader

- catroid/src/org/catrobat/catroid/content/Project.java
- catroid/src/org/catrobat/catroid/content/XmlHeader.java
- catroid/src/org/catrobat/catroid/content/bricks/HideTextBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/ShowTextBrick.java
seemed to cause some problems with project download.
> reset XML Header field to isPhiroProProject

- catroid/src/org/catrobat/catroid/ui/dialogs/RenameSoundDialog.java
removed toast in RenameSoundDialog.java
> hotfix removed toast in RenameSoundDialog

- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroid/src/org/catrobat/catroid/common/Constants.java
- catroid/src/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion096AndBefore.java
- catroidTest/src/org/catrobat/catroid/test/io/XStreamToSupportCatrobatLanguageVersion096AndBeforeTest.java
> updated language version

- catroid/src/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion096AndBefore.java
I swapped the StopAllSoundsBrick and the WhenBrick to the corresponding brick info.
> CAT-1579 Add the brick to the corresponding brick info

- catroid/src/org/catrobat/catroid/physics/PhysicsObject.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsBricksCloneTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsObjectTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsSpriteCloneTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsWorldTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/actions/SetPhysicsObjectTypeActionTest.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/physics/SetPhysicsObjectTypeBrickTest.java
changed physics default type from NONE to FIXED
> Cat-1209 Create physics static object if physics brick is present

- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/common/MessageContainer.java
- catroid/src/org/catrobat/catroid/common/standardprojectcreators/StandardProjectCreatorPhysics.java
- catroid/src/org/catrobat/catroid/content/bricks/BroadcastBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/BroadcastReceiverBrick.java
- catroid/src/org/catrobat/catroid/physics/PhysicsCollisionBroadcast.java
- catroid/src/org/catrobat/catroid/physics/content/bricks/CollisionReceiverBrick.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsBricksCloneTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsSpriteCloneTest.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/physics/SetPhysicsObjectTypeBrickTest.java
prevented collision messages from being shown in broadcast bricks
added error dialog when entering possible collision message in broadcast
bricks
> Cat 1428 Hide Collision Broadcasts in Normal Broadcast-recievers

- catroid/src/org/catrobat/catroid/ui/dialogs/LoginRegisterDialog.java
additionally fixed some checkstyle warnings.
> CAT-1546 Fixed URL for PW reset

- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/common/BrickValues.java
- catroid/src/org/catrobat/catroid/content/actions/IfLogicAction.java
- catroid/src/org/catrobat/catroid/content/bricks/IfLogicBeginBrick.java
- catroid/src/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/BrickValueParameterTest.java
changed default value in if-brick(true) and make it consistent
> CAT-899 Consistency if-brick

- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/common/BrickValues.java
- catroid/src/org/catrobat/catroid/content/actions/IfLogicAction.java
- catroid/src/org/catrobat/catroid/content/bricks/IfLogicBeginBrick.java
- catroid/src/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/BrickValueParameterTest.java
> Revert "CAT-899 Consistency if-brick"

- build.gradle
> Revert 23a36eb492c1108746fc2618aeb4046f21d538f9

- build.gradle
increased version no. and name for hotfix.
> Increase Version Code

- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/ui/fragment/ProjectsListFragment.java
- catroid/src/org/catrobat/catroid/ui/fragment/SpritesListFragment.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/activity/MyProjectsActivityTest.java
hopefully with no issues anymore :)
> CAT-897 Added Deselect all Functionality

- catroid/res/layout/activity_my_projects_list_item.xml
- catroid/res/layout/activity_project_spritelist_item.xml
- catroid/res/layout/fragment_look_looklist_item.xml
- catroid/res/values/styles.xml
- catroid/src/org/catrobat/catroid/ui/LookViewHolder.java
- catroid/src/org/catrobat/catroid/ui/adapter/ProjectAdapter.java
- catroid/src/org/catrobat/catroid/ui/adapter/SpriteAdapter.java
- catroid/src/org/catrobat/catroid/ui/controller/LookController.java
- catroid/src/org/catrobat/catroid/ui/fragment/LookFragment.java
was already merged, but with some errors, (looks / background view broken) this is the fix for that.
> CAT-904 Design problem at menu bar

- catroid/src/org/catrobat/catroid/camera/CameraManager.java
- catroid/src/org/catrobat/catroid/drone/DroneInitializer.java
- catroid/src/org/catrobat/catroid/facedetection/FaceDetectionHandler.java
- catroid/src/org/catrobat/catroid/facedetection/IcsFaceDetector.java
- catroid/src/org/catrobat/catroid/formulaeditor/Formula.java
- catroid/src/org/catrobat/catroid/ui/MainMenuActivity.java
- catroid/src/org/catrobat/catroid/ui/SettingsActivity.java
- catroidTest/src/org/catrobat/catroid/test/facedetection/IcsFaceDetectorTest.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/GlideToBrickTest.java
- catroidTest/src/org/catrobat/catroid/uitest/content/interaction/BrickDragAndDropTest.java
- catroidTest/src/org/catrobat/catroid/uitest/facedetection/FaceDetectionResourcesTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/activity/WebViewActivityTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/dialog/SetDescriptionDialogTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/dialog/UploadDialogTest.java
- catroidTest/src/org/catrobat/catroid/uitest/util/UiTestUtils.java
Remove checks and workarounds that were implemented for older API levels
that are now below minimum supported API level.
> CAT-CLEANUP Remove workarounds and checks for deprecated API levels

- catroid/src/org/catrobat/catroid/pocketmusic/note/trackgrid/GridRow.java
- catroid/src/org/catrobat/catroid/pocketmusic/note/trackgrid/GridRowPosition.java
- catroid/src/org/catrobat/catroid/pocketmusic/note/trackgrid/TrackGrid.java
- catroidSourceTest/src/org/catrobat/catroid/test/code/CheckForVerifiesOrAssertionsTest.java
- catroidTest/src/org/catrobat/catroid/test/pocketmusic/note/trackgrid/GridRowPositionTest.java
- catroidTest/src/org/catrobat/catroid/test/pocketmusic/note/trackgrid/GridRowPositionTestDataFactory.java
- catroidTest/src/org/catrobat/catroid/test/pocketmusic/note/trackgrid/GridRowTest.java
- catroidTest/src/org/catrobat/catroid/test/pocketmusic/note/trackgrid/GridRowTestDataFactory.java
- catroidTest/src/org/catrobat/catroid/test/pocketmusic/note/trackgrid/TrackGridTest.java
- catroidTest/src/org/catrobat/catroid/test/pocketmusic/note/trackgrid/TrackGridTestDataFactory.java
Add classes which serve as interface between note events and future GUI.
> MUS-182 Create interface between note-events and gui

- catroid/src/org/catrobat/catroid/stage/StageListener.java
With this changes the nullpointerexception cannot occur.
> fixed problem on stage

- catroid/res/values-de/strings.xml
- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/camera/CameraManager.java
- catroid/src/org/catrobat/catroid/content/actions/ChooseCameraAction.java
- catroid/src/org/catrobat/catroid/content/actions/ExtendedActions.java
- catroid/src/org/catrobat/catroid/content/bricks/ChooseCameraBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/VideoBrick.java
- catroid/src/org/catrobat/catroid/facedetection/FaceDetectionHandler.java
- catroid/src/org/catrobat/catroid/stage/PreStageActivity.java
- catroid/src/org/catrobat/catroid/stage/StageActivity.java
- catroid/src/org/catrobat/catroid/stage/StageListener.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/VideoBrickTest.java
Remove hardcoded cameraIDs and added proper initialization in
CameraManager, Bricks, Actions, and Tests. Moved checks for flash from
preStageActivity into cameraManager.
> CAT-1715 Refactor CameraManager

- catroid/src/org/catrobat/catroid/stage/StageListener.java
https://jira.catrob.at/browse/CAT-1721
> CAT-1721 remove ARDrone Support from stage

- catroid/src/org/catrobat/catroid/camera/CameraManager.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/activity/MainMenuActivityTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/activity/MyProjectsActivityTest.java
Fix video preview in landscape mode. Preview was
rotated by 90 degrees and extensively stretched.
> CAT-1715 VideoBrick fix preview in landscape mode

- catroidTest/src/org/catrobat/catroid/uitest/ui/dialog/NewProjectDialogTest.java
Fix Test that became outdated/broken with CAT-1732.
> CAT-Quickfix Repair NewProjectDialogTest

- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroid/src/org/catrobat/catroid/common/LookData.java
Reverts Catrobat/Catroid#1488: Apparently we still need the ID in LookData
> Revert "CAT-1739 Removed Redo/Undo Code"

- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroid/src/org/catrobat/catroid/common/LookData.java
> Revert "Revert "CAT-1739 Removed Redo/Undo Code""

- catroid/res/layout/brick_set_x.xml
- catroid/res/layout/brick_set_y.xml
- catroid/res/layout/brick_vibration.xml
- catroid/src/org/catrobat/catroid/common/BrickValues.java
- catroid/src/org/catrobat/catroid/content/bricks/SetXBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/SetYBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/VibrationBrick.java
- catroid/src/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- Changed preview form 1000 seconds to 1.0 second.
- Added OnClickListener to TextView.
- Refactored Constructors.
- replaces #1480
> CAT-1649 Edit VibrationDuration redirects to FromulaEditor

- catroid/res/values-de/strings.xml
- catroid/res/values/strings.xml
https://jira.catrob.at/browse/CAT-1736
> CAT-1736 Drone String changes

- catroid/src/org/catrobat/catroid/common/DroneVideoLookData.java
- catroid/src/org/catrobat/catroid/common/LookData.java
- catroid/src/org/catrobat/catroid/content/Look.java
[CAT-1735](https://jira.catrob.at/browse/CAT-1735?filter=11400)
> CAT-1735 LookData should not extend Image

- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/ui/dialogs/NewSpriteDialog.java
* shows now error message when trying to load an image with special chars in filename
-- new string for better user notification
* Dialog behaviour
-- sprite is not created if loading the image fails
> CAT-999 fixed dialog behaviour

- catroid/res/menu/menu_main_menu.xml
- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroid/src/org/catrobat/catroid/common/Constants.java
- catroid/src/org/catrobat/catroid/ui/BaseActivity.java
- catroid/src/org/catrobat/catroid/ui/MainMenuActivity.java
- catroid/src/org/catrobat/catroid/ui/WebViewActivity.java
- catroid/src/org/catrobat/catroid/utils/Utils.java
- catroid/src/org/catrobat/catroid/web/ServerCalls.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/activity/WebViewActivityTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/menu/LogoutTest.java
Offer a logout button in menu to logged in users, that logs them out
in the app and the webview.
> CAT-1653 Logout button

- catroid/src/org/catrobat/catroid/facedetection/FaceDetectionHandler.java
Flash didnt work on first program start, only after resume, or
restart.
> CAT-1749 Fix flash not working on first start

- catroid/src/org/catrobat/catroid/content/BroadcastHandler.java
#1482 Reopened for release branch
> CAT-1576 Functional Broadcast and wait

- catroid/src/org/catrobat/catroid/devices/arduino/phiro/PhiroImpl.java
Changed Pin Assignment and Default Values
> CAT Task Phiro pin Assignment

- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/transfers/LogoutTask.java
- catroid/src/org/catrobat/catroid/ui/MainMenuActivity.java
- catroid/src/org/catrobat/catroid/utils/Utils.java
- catroid/src/org/catrobat/catroid/web/ServerCalls.java
Activate token login functionality that was added in CAT1653.
Add toast for logout.
> CAT TASK Activate token login functionality

- catroid/src/org/catrobat/catroid/camera/CameraManager.java
- catroid/src/org/catrobat/catroid/stage/StageActivity.java
Switching to another app and back broke camera brick.
> CAT-1768 Fix camera brick when switching apps

- catroid/src/org/catrobat/catroid/common/Constants.java
- catroid/src/org/catrobat/catroid/transfers/GetFacebookUserInfoTask.java
- catroid/src/org/catrobat/catroid/ui/dialogs/SignInDialog.java
- catroid/src/org/catrobat/catroid/utils/Utils.java
- catroid/src/org/catrobat/catroid/web/ServerCalls.java
> OAuth Release Changes

- catroid/res/menu/menu_main_menu.xml
- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroid/src/org/catrobat/catroid/ui/BaseActivity.java
- catroid/src/org/catrobat/catroid/ui/dialogs/LogInDialog.java
- catroid/src/org/catrobat/catroid/ui/dialogs/OAuthUsernameDialog.java
- catroid/src/org/catrobat/catroid/ui/dialogs/RegistrationDialog.java
- catroid/src/org/catrobat/catroid/ui/dialogs/SignInDialog.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/menu/LogoutLoginTest.java
- catroidTest/src/org/catrobat/catroid/uitest/web/UserConceptTest.java
Added login button to menu for consistency.
> CAT-1758 Add login button to menu

- catroid/AndroidManifest.xml
- catroid/src/org/catrobat/catroid/content/actions/ShowTextAction.java
- catroid/src/org/catrobat/catroid/content/bricks/ShowTextBrick.java
- catroid/src/org/catrobat/catroid/stage/ShowTextActor.java
CAT-1575 variables increased incorrectly
CAT-1782 crashes when started from project-activity
CAT-1689 broadcast variables increased incorrectly
> CAT-1766 hotfix for vibration

- catroid/src/org/catrobat/catroid/ui/WebViewActivity.java
https://jira.catrob.at/projects/CAT/issues/CAT-1793
> "About Pocket Code" and "(c) Catrobat" links should open browser intent

- catroid/res/layout/dialog_login.xml
- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/ui/dialogs/SignInDialog.java
Change some error messages and add an isNetworkAvailable check for the facebook and google login.
> CAT-1796 Cosmetic changes for logins

- catroid/src/org/catrobat/catroid/stage/StageActivity.java
Alpha animations and transparent elements in stage were incorrectly
displayed.
> CAT-1800 Transparent elements displayed incorrect

- catroid/res/values-tr/strings.xml
> CAT-1830 Removed last ellipsis error

- catroid/src/org/catrobat/catroid/content/bricks/ChangeVariableBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/HideTextBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/SetVariableBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/ShowTextBrick.java
- catroid/src/org/catrobat/catroid/ui/dialogs/NewDataDialog.java
- catroidTest/src/org/catrobat/catroid/uitest/content/brick/VariableBricksTest.java
will no longer name the variable New...
> CAT-1440 Cancelling creating a new variable

- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/common/MessageContainer.java
- catroid/src/org/catrobat/catroid/common/standardprojectcreators/StandardProjectCreatorPhysics.java
- catroid/src/org/catrobat/catroid/content/CollisionScript.java
- catroid/src/org/catrobat/catroid/content/Sprite.java
- catroid/src/org/catrobat/catroid/content/bricks/BroadcastBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/BroadcastReceiverBrick.java
- catroid/src/org/catrobat/catroid/physics/PhysicsCollision.java
- catroid/src/org/catrobat/catroid/physics/PhysicsCollisionBroadcast.java
- catroid/src/org/catrobat/catroid/physics/content/bricks/CollisionReceiverBrick.java
- catroid/src/org/catrobat/catroid/ui/fragment/SpritesListFragment.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsBricksCloneTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsCollisionScriptInteractionTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsCollisionTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsObjectTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/activity/ProjectActivityTest.java
changed CollisionScript behaviour, so that every collision broadcast is distinguishable from the standard broadcasts.
update CollisionBroadcast after ranaming an object
> Redesign of collision brick

- catroid/src/org/catrobat/catroid/physics/PhysicsWorld.java
- catroid/src/org/catrobat/catroid/physics/shapebuilder/PhysicsShapeBuilder.java
- catroid/src/org/catrobat/catroid/physics/shapebuilder/PhysicsShapeScaleUtils.java
- catroid/src/org/catrobat/catroid/stage/StageListener.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsBoundaryBoxTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsLookTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsShapeBuilderTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsShapeScaleUtilsTest.java
remove Threading
reset computed shapes at stage leave
> Refactor ShapeBuilder

- catroidTest/src/org/catrobat/catroid/test/physics/actions/SetLookActionTest.java
checked if there is another look
checked if there is the correct look
> CAT-1011 write SetLookAction test

- catroid/src/org/catrobat/catroid/stage/StageActivity.java
I checked the required resources to only resume these resources and not all.
> CAT-1700 Handle resume button correctly

- catroid/src/org/catrobat/catroid/content/BroadcastHandler.java
#CAT-1693
https://jira.catrob.at/browse/CAT-1693
> CAT-1693 Fix Broadcast scripts crash

- catroid/src/org/catrobat/catroid/stage/StageListener.java
This does not solve the problems mentioned in CAT-1876.
> CAT-1820 background issue in version 0.98

- catroid/src/org/catrobat/catroid/physics/PhysicsObject.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsObjectTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsObjectTypeDefaultValueTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsSpriteCloneTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsWorldTest.java
- catroidTest/src/org/catrobat/catroid/test/physics/actions/SetPhysicsObjectTypeActionTest.java
- catroidTest/src/org/catrobat/catroid/test/utils/PhysicsTestUtils.java
Set default physics object type value depending on the present physics bricks
> CAT-1862 physics object type default value

- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroid/src/org/catrobat/catroid/ui/BaseActivity.java
- catroid/src/org/catrobat/catroid/ui/MainMenuActivity.java
- catroid/src/org/catrobat/catroid/ui/dialogs/SignInDialog.java
- catroid/src/org/catrobat/catroid/utils/Utils.java
#CAT-1289
https://jira.catrob.at/browse/CAT-1289
> CAT-1289 Introduce no-internet dialog

- build.gradle
- catroid/src/org/catrobat/catroid/CatroidApplication.java
added multidex support prior to Android 5.0
> CAT-1891 Resolve compile error after merging

- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroid/src/org/catrobat/catroid/io/LoadProjectTask.java
- catroid/src/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/org/catrobat/catroid/ui/MainMenuActivity.java
> Revert "CAT-1883 Correctly handled a just downloaded missing program"

- catroid/src/org/catrobat/catroid/ui/ScriptActivity.java
- catroid/src/org/catrobat/catroid/ui/fragment/AddBrickFragment.java
- catroid/src/org/catrobat/catroid/ui/fragment/ScriptFragment.java
Hides the backpack menu in the AddBrickFragment.
> CAT-1713 Hide backpack in AddBrickFragment

- catroid/src/org/catrobat/catroid/facedetection/SlowFaceDetector.java
- catroid/src/org/catrobat/catroid/physics/PhysicsBoundaryBox.java
- catroid/src/org/catrobat/catroid/ui/fragment/UserBrickDataEditorFragment.java
- catroidTest/src/org/catrobat/catroid/test/camera/CameraManagerTest.java
- catroidTest/src/org/catrobat/catroid/test/facedetection/IcsFaceDetectorTest.java
- catroidTest/src/org/catrobat/catroid/test/formulaeditor/ParserTestSensors.java
- catroidTest/src/org/catrobat/catroid/test/physics/actions/SetLookActionTest.java
- catroidTest/src/org/catrobat/catroid/test/stage/StageActivityAudioFocusTest.java
- catroidTest/src/org/catrobat/catroid/test/utiltests/UtilsTest.java
- catroidTest/src/org/catrobat/catroid/test/web/ServerCallsTest.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/activity/ProjectActivityTest.java
> CAT-1860 Fixed JUnitTests

- catroid/src/org/catrobat/catroid/content/Project.java
- catroid/src/org/catrobat/catroid/content/Sprite.java
- catroid/src/org/catrobat/catroid/physics/content/actions/IfOnEdgeBouncePhysicsAction.java
CAT-1913 Fix setting correct Action(Physics)Factory for sprites with(out) physics bricks
minor code improvements
> CAT-1913 Fix setting correct Action(Physics)Factory

- catroid/src/org/catrobat/catroid/io/StorageHandler.java
Add Locale.getDefault in StorageHandler .toUpperCase to distuingish
languages
> CAT-1931 Add Locale.getDefault to toUpperCase

- catroid/src/org/catrobat/catroid/io/StorageHandler.java
> Revert "CAT-1931 Add Locale.getDefault to toUpperCase"

- catroid/src/org/catrobat/catroid/io/StorageHandler.java
This replaces #1643, as suggested by @robertpainsi 😼
> CAT-1931 Fixed Lint warning by removing toUpperCase

- catroid/src/org/catrobat/catroid/content/Project.java
- catroid/src/org/catrobat/catroid/content/Sprite.java
- catroid/src/org/catrobat/catroid/physics/content/actions/IfOnEdgeBouncePhysicsAction.java
- catroidTest/src/org/catrobat/catroid/test/physics/PhysicsBaseTest.java
set correct Action(Physics)Factory [Project]
minor code improvements [IfOnEdgeBouncePhysicsAction, Sprite]
fix physics tests [PhysicsBaseTest]
> CAT-1913 Fix setting correct Action(Physics)Factory for sprites with(out) physics bricks

- catroid/src/org/catrobat/catroid/ui/fragment/FormulaEditorListFragment.java
- catroidTest/src/org/catrobat/catroid/uitest/formulaeditor/FormulaEditorListFragmentTest.java
> CAT-1529 Grouped list functions together in FE

- catroid/res/layout/dialog_rate_pocketcode.xml
- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/ui/dialogs/RatingDialog.java
- catroid/src/org/catrobat/catroid/ui/dialogs/UploadProjectDialog.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/dialog/UploadDialogTest.java
If a user uploads two projects, a dialog will ask to rate Pocket Code on Google Play Store.
>  CAT-1595 Implemented Rating Dialog

- catroid/res/layout/dialog_text_multiline_dialog.xml
- catroid/src/org/catrobat/catroid/ui/dialogs/MultiLineTextDialog.java
> Revert "CAT-1904 Added description field expansion in programm overview"

- catroid/src/org/catrobat/catroid/content/bricks/Brick.java
- catroid/src/org/catrobat/catroid/content/bricks/CameraBrick.java
- catroid/src/org/catrobat/catroid/stage/PreStageActivity.java
- catroid/src/org/catrobat/catroid/stage/StageActivity.java
If you want to resume your project, the VideoBrick did not resume. So i added a new brick resources "VIDEO" and resume it correctly.
> CAT-1970 VideoBrick did not resume

- catroidTest/src/org/catrobat/catroid/uitest/ui/activity/MyProjectsActivityTest.java
Test is broken, test brakes whole test run, and this shouldnt be a
ui test in the first place.
> CAT FIX - remove broken testInvalidProject ui test

- catroid/res/layout/brick_physics_set_physics_object_type.xml
- catroid/res/layout/brick_point_in_direction.xml
- catroid/res/layout/brick_turn_left.xml
- catroid/res/layout/brick_turn_right.xml
- catroid/res/values/strings-global.xml
- catroid/res/values/strings.xml
> CAT-STRING various strings changed

- catroid/src/org/catrobat/catroid/pocketmusic/note/trackgrid/TrackToTrackGridConverter.java
- catroidSourceTest/src/org/catrobat/catroid/test/code/CheckForVerifiesOrAssertionsTest.java
- catroidTest/src/org/catrobat/catroid/test/pocketmusic/note/trackgrid/TrackToTrackGridConverterTest.java
Implement the converter which gets the data from the noteevents of the midi file to our data classes.
> MUS-183 Write converter from noteevent to created interface

- catroid/src/org/catrobat/catroid/content/bricks/ChangeBrightnessByNBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/ChangeSizeByNBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/ChangeTransparencyByNBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/ChangeXByNBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/ChangeYByNBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/GlideToBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/MoveNStepsBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/PlaceAtBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/PointInDirectionBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/SetBrightnessBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/SetSizeToBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/SetTextBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/SetTransparencyBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/SetXBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/SetYBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/ShowTextBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/TurnLeftBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/TurnRightBrick.java
- catroid/src/org/catrobat/catroid/content/bricks/VibrationBrick.java
- catroid/src/org/catrobat/catroid/formulaeditor/Formula.java
- catroid/src/org/catrobat/catroid/formulaeditor/InternFormula.java
- catroid/src/org/catrobat/catroid/formulaeditor/InternToExternGenerator.java
- catroid/src/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroid/src/org/catrobat/catroid/utils/Utils.java
- catroidTest/src/org/catrobat/catroid/uitest/formulaeditor/FormulaEditorEditTextTest.java
initial brick values are consistent as integers now
entered decimal values with zero after the comma get trimmed inside the
formula
> CAT-1393 brick value consistency

- build.gradle
- catroid/res/values/strings.xml
- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroid/src/org/catrobat/catroid/common/Constants.java
- catroid/src/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion0991AndBefore.java
- catroid/src/org/catrobat/catroid/ui/BaseActivity.java
- catroid/src/org/catrobat/catroid/ui/BaseExceptionHandler.java
- catroid/src/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/org/catrobat/catroid/utils/Utils.java
- catroidTest/src/org/catrobat/catroid/test/io/XStreamToSupportCatrobatLanguageVersion0991AndBeforeTest.java
Deal with unhandled exceptions and properly finish and restart app.
increased language version number.
> CAT-2015 HOTFIX 0.9.22 - Exception Handling

- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroid/src/org/catrobat/catroid/common/Constants.java
- catroid/src/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion099AndBefore.java
- catroidTest/src/org/catrobat/catroid/test/io/XStreamToSupportCatrobatLanguageVersion099AndBeforeTest.java
decrease language version from 0991 to 099 again.
> CAT HOTFIX - Decrease language version

- catroid/src/org/catrobat/catroid/ProjectManager.java
- catroid/src/org/catrobat/catroid/common/Constants.java
- catroid/src/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion0991AndBefore.java
- catroidTest/src/org/catrobat/catroid/test/io/XStreamToSupportCatrobatLanguageVersion0991AndBeforeTest.java
> Revert "CAT HOTFIX - Decrease language version"

- catroid/src/org/catrobat/catroid/ui/dialogs/OverwriteRenameMediaDialog.java
Fixes [CAT-1884](https://jira.catrob.at/browse/CAT-1884)
> CAT-1884 Fix crash when adding two looks or sounds from media library

- catroid/src/org/catrobat/catroid/common/defaultprojectcreators/DefaultProjectCreatorDefault.java
Fixes [CAT - 1873](https://jira.catrob.at/browse/CAT-1873)
> CAT-1873 Fixed bug in default program

- catroid/src/org/catrobat/catroid/ui/ScriptActivity.java
- catroid/src/org/catrobat/catroid/ui/controller/LookController.java
- catroid/src/org/catrobat/catroid/ui/controller/SoundController.java
- catroid/src/org/catrobat/catroid/ui/dialogs/NewSoundDialog.java
- catroid/src/org/catrobat/catroid/ui/fragment/ScriptFragment.java
- catroid/src/org/catrobat/catroid/ui/fragment/SoundFragment.java
File chooser opens instead of brick categories screen
Refactored Activity-Fragment interaction
> CAT-955 File chooser

- build.gradle
- catroid/res/layout/dialog_new_sound.xml
- catroid/src/org/catrobat/catroid/ui/dialogs/NewSoundDialog.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/activity/PocketMusicTest.java
Add feature toggle to build file to disable entry point for pocket music
> MUS-198 Implement feature toggles

- catroid/src/org/catrobat/catroid/ui/fragment/SoundFragment.java
Remove one line of code, which was left in when merging the develop branch into the feature branch.
> MUS-FIX Remove some code which breaks the build.

- catroid/src/org/catrobat/catroid/ui/dialogs/UploadProgressDialog.java
- catroid/src/org/catrobat/catroid/ui/dialogs/UploadProjectDialog.java
Uploading a project where the project name contains a restricted character is now prohibited.
> CAT-1226 fixed upload bug

- catroid/src/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/org/catrobat/catroid/ui/fragment/SpritesListFragment.java
- catroidTest/src/org/catrobat/catroid/uitest/ui/fragment/SpritesListFragmentTest.java
Hotfix for loading of project after upload & return from WebView in current release.
ActionBar title also wasn't displayed correctly.
> CAT-2076 Fix project loading and ActionBar-Title in SpritesList

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/PreviousLookActionTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/CategoryBricksFactoryTest.java
- catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/PreviousLookAction.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PreviousLookBrick.java
- catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/main/java/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion0991AndBefore.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/res/layout/brick_previous_look.xml
- catroid/src/main/res/values-de/strings.xml
- catroid/src/main/res/values/strings.xml
**reopens #1761**
Like the "next look" brick a "previous look" brick has been
created to be able to switch the looks in reverse order.
> CAT-1953 Switch to previous Look

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/CategoryBricksFactoryTest.java
- catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
- catroid/src/main/java/org/catrobat/catroid/content/WhenConditionScript.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BrickBaseType.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BroadcastReceiverBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ConcurrentFormulaHashMap.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/FormulaBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ScriptBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/UserScriptDefinitionBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenClonedBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenConditionBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenNfcBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenRaspiPinChangedBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenStartedBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenTouchDownBrick.java
- catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/main/java/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion0991AndBefore.java
- catroid/src/main/java/org/catrobat/catroid/physics/content/bricks/CollisionReceiverBrick.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/res/layout/brick_when_condition_true.xml
- catroid/src/main/res/values/strings.xml
- catroidTest/src/org/catrobat/catroid/test/content/actions/WhenConditionBecomesTrueActionTest.java
**reopens #1827**
- script is executed when condition becomes true
- to be executed again, the condition has first to be false
and then become true again
- did some refactoring: ScriptBrick is now an interface instead of an
abstract class
> CAT-1969 When condition becomes true brick

- catroid/src/main/java/org/catrobat/catroid/common/FileChecksumContainer.java
- catroid/src/main/java/org/catrobat/catroid/common/defaultprojectcreators/DefaultProjectCreatorDefault.java
- clone method fixes the bug
- had to add Checksum before clone because otherwise there is no checksum found for the LookData
- added Log Message to increment Usage such that we know which file is missing
> Fixed bug using the clone method of LookData

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/CategoryBricksFactoryTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/PlaySoundAndWaitBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PlaySoundAndWaitBrick.java
- catroid/src/main/java/org/catrobat/catroid/io/SoundManager.java
- catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/main/java/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion0991AndBefore.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/res/layout/brick_play_sound_and_wait.xml
- catroid/src/main/res/values/strings.xml
reopens [#1835](https://github.com/Catrobat/Catroid/pull/1835)
> CAT-1962 Play sound and wait Brick added

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/StopScriptActionsTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/CategoryBricksFactoryTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/StopScriptBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/common/BrickValues.java
- catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/StopAllScriptsAction.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/StopOtherScriptsAction.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/StopThisScriptAction.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/StopScriptBrick.java
- catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/main/java/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion0991AndBefore.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/res/layout/brick_stop_script.xml
- catroid/src/main/res/values/strings.xml
reopens [#1806](https://github.com/Catrobat/Catroid/pull/1806)
> CAT-1940 StopScripts Brick added

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/CategoryBricksFactoryTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/SpeakAndWaitBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/SpeakAction.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/SpeakAndWaitBrick.java
- catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/main/java/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion0991AndBefore.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/res/layout/brick_speak_and_wait.xml
- catroid/src/main/res/values/strings.xml
reopens [#1854](https://github.com/Catrobat/Catroid/pull/1854)
> CAT-2025 Speak and wait Brick

- catroid/src/main/java/org/catrobat/catroid/pocketmusic/PocketMusicActivity.java
Create a dummy song containing 2 notes
as preparation for ticket MUS-197
> MUS-201 Create a Dummy Song

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/CategoryBricksFactoryTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
as suggested by the Usability-Team
> CAT-FIX Brick order in BrickCategories changed

- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/common/SoundInfo.java
- catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PlaySoundAndWaitBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PlaySoundBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/SetLookBrick.java
- catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/main/java/org/catrobat/catroid/merge/MergeTask.java
- catroid/src/main/java/org/catrobat/catroid/ui/controller/BackPackListManager.java
- catroid/src/main/java/org/catrobat/catroid/ui/controller/SoundController.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/SpritesListFragment.java
See https://jira.catrob.at/browse/CAT-2071
> CAT-2071 Fix for sprite clone not working consistent

- catroid/src/main/java/org/catrobat/catroid/ui/adapter/BrickAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/res/values/strings.xml
> CAT-2031 Add help option to the bricks short press menu

- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
Addition to https://github.com/Catrobat/Catroid/commit/e47a41a9a8e11344c0c3c0249df7ebfaf9fc0d1e
> CAT-2031 Add rules for bricks in multiple categories

- catroid/src/androidTest/java/org/catrobat/catroid/test/sensing/CollisionDetectionAdvancedTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/BrickValueParameterTest.java
This will not fix failing tests in BrickValueParameterTest.
> CAT-FIX Fix build errors in tests

- catroid/src/main/java/org/catrobat/catroid/ui/adapter/BrickAdapter.java
> CAT-2031 Dont display for bricks without description

- catroid/src/androidTest/java/org/catrobat/catroid/uitest/ui/dialog/NewSceneDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/adapter/SpriteAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/NewSceneDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dynamiclistview/UtilDynamicListView.java
- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
- catroid/src/main/res/values/colors.xml
Fix drag&drop visibility of Sprites
Remove backpack background on longPress (to be consistent)
Fix crash in newSceneDialog
Refactoring
Fix lint + pmd errors/warnings
> CAT-FIX Grouping/Backpack/Scenes

- catroid/src/androidTest/java/org/catrobat/catroid/uitest/ui/activity/PocketMusicTest.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/PocketMusicActivity.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TrackRowView.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TrackView.java
- catroid/src/main/res/values/colors.xml
Implemented loading a track into GUI and make an UI test for it.
> MUS-197 Structure to GUI

- catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
Really? A Pull Request for that???
Yes, really :smile_cat:
> CAT-FIX Fix wrong logger TAG class

- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/TrackTestDataFactory.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/trackgrid/TrackGridTestDataFactory.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/PocketMusicActivity.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/trackgrid/TrackToTrackGridConverter.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/NoteView.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TrackRowView.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TrackView.java
Implement the button press handling so that the data structure
is updated upon the onClick callback.
> MUS-191 GUI to structure

- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/TrackTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/trackgrid/TrackGridTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/trackgrid/TrackGridTestDataFactory.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/trackgrid/TrackGridToTrackConverterTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/trackgrid/TrackToTrackGridConverterTest.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/Track.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/trackgrid/GridRow.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/trackgrid/TrackGrid.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/trackgrid/TrackGridToTrackConverter.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/trackgrid/TrackToTrackGridConverter.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TrackView.java
In order to properly achieve this some refactoring work was needed.
Especially the implicit assumption of initially filled empty data structures was dropped.
> MUS-202 Implementing TrackGrid to Track converter

- .idea/copyright/Catroid.xml
- .idea/copyright/profiles_settings.xml
This feature has already been in the repository but has been deleted
unintentionally [1].
[1] https://github.com/Catrobat/Catroid/pull/1859
> CAT-FIX Add copyright to newly created files through AS

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/SetRotationStyleActionTest.java
- catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/SetRotationStyleAction.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/SetRotationStyleBrick.java
The rotation style option is an integer, the position in the spinner.
The options (ALL_AROUND, LEFT_RIGHT_ONLY, NONE) are hard-coded and have
nothing to do with a Formula.
> CAT-REF Replace Formula by an integer in SetRotationStyleAction

- catroid/src/main/java/org/catrobat/catroid/content/bricks/CameraBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ChooseCameraBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/FlashBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/StopScriptBrick.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/UserVariable.java
- catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java
Also see https://github.com/Catrobat/Catroid/pull/1991
> CAT-FIX Don't serialize members which shouldn't be in the XML

- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/common/LookData.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/AddItemToUserListBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BackPackedData.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ChangeVariableBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/FormulaBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/InsertItemIntoUserListBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ReplaceItemInUserListBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/UserListBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/UserVariableBrick.java
- catroid/src/main/java/org/catrobat/catroid/ui/controller/BackPackListManager.java
- catroid/src/main/java/org/catrobat/catroid/ui/controller/BackPackScriptController.java
- catroid/src/main/java/org/catrobat/catroid/ui/controller/BackPackSpriteController.java
- catroid/src/main/java/org/catrobat/catroid/ui/controller/LookController.java
- catroid/src/main/java/org/catrobat/catroid/ui/controller/SoundController.java
- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
1. Fix "sporadic" missing images & sounds in backpack --> this happened when the hashcode of the file has changed (when file has been modified).
2. Support Backpacking of variables & lists that only occur in formulas. This is CAT-2052 actually.
3. Show correct Login-Dialog after a crash
> Cat nolb v3 fixes

- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/ProjectTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/ProjectTestDataFactory.java
- catroid/src/androidTest/java/org/catrobat/catroid/uitest/ui/activity/PocketMusicTest.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/PocketMusicActivity.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/Project.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/midi/MidiToProjectConverter.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TrackView.java
- catroid/src/main/res/values-de/strings.xml
Writing the midi file to the correct folder structure.
> MUS-203 Saving the music when leaving the activity

- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/TrackTestDataFactory.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/trackgrid/GridRowPositionTestDataFactory.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/trackgrid/TrackGridTestDataFactory.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/trackgrid/TrackGridToTrackConverterTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/trackgrid/TrackToTrackGridConverterTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uitest/ui/activity/PocketMusicTest.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/PocketMusicActivity.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/Project.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/Track.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/trackgrid/GridRow.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/trackgrid/GridRowPosition.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/trackgrid/TrackGrid.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/trackgrid/TrackToTrackGridConverter.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/NoteView.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TrackRowView.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TrackView.java
- catroid/src/main/java/org/catrobat/catroid/ui/adapter/SoundBaseAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/controller/SoundController.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/SoundFragment.java
Support saving and loading of midi files.
> MUS-204 Loading a midi file from path.

- catroid/src/main/java/org/catrobat/catroid/ui/adapter/DataAdapter.java
- catroid/src/main/res/layout/dialog_overwrite_project.xml
- catroid/src/main/res/values/strings.xml
rebased & reopened #1872 (use release-branch as base).
this contains minor UX improvements (string changes, radiobutton style, etc), nothing fancy
ping @thmq: please accept it if you want to add it to the new release. Otherwise you can close it.
> CAT-1742 usability improvements

- catroid/src/main/java/org/catrobat/catroid/ui/adapter/DataAdapter.java
- catroid/src/main/res/layout/dialog_overwrite_project.xml
- catroid/src/main/res/values/strings.xml
Same as https://github.com/Catrobat/Catroid/pull/1985 but with `develop` as head.
> Cat 1742 usability improvements

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/SpriteTest.java
- catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
- catroid/src/main/java/org/catrobat/catroid/content/Script.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/HideTextAction.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/ShowTextAction.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/HideTextBrick.java
- catroid/src/main/java/org/catrobat/catroid/stage/ShowTextActor.java
The Show & HideVariableActions need a reference to the correct Scene that holds the relevant sprite variables. The currentScene was definitely wrong as it only works when the program is  started coincidentally from that Scene.
> Fix Scene-Reference in VariableActions

- build.gradle
- catroid/build.gradle
Reset gradle version, because Jenkins didn't work with 2.2.3
> Reset gradle version

- catroid/src/main/java/org/catrobat/catroid/pocketmusic/PocketMusicActivity.java
Override the onOptionsMenuSelected function within PocketMusicActivity and
implement the home button to finish the activity.
> MUS-213 Back button

- catroid/src/main/java/org/catrobat/catroid/ui/BottomBar.java
- catroid/src/main/java/org/catrobat/catroid/ui/MyProjectsActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/SetDescriptionDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ShowDetailsFragment.java
- catroid/src/main/res/layout/activity_my_projects.xml
- catroid/src/main/res/layout/fragment_project_show_details.xml
- catroid/src/main/res/values/strings.xml
- catroid/src/main/res/values/styles.xml
Currently the project description is shown by a dropdown arrow. In consultation with the UX-Team there should be a new fragment with the values.
> Create new fragment to show description of a project

- catroid/src/androidTest/java/org/catrobat/catroid/test/merge/MergeTaskTest.java
- catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/main/java/org/catrobat/catroid/merge/ConflictHelper.java
- catroid/src/main/java/org/catrobat/catroid/merge/MergeManager.java
- catroid/src/main/java/org/catrobat/catroid/merge/MergeTask.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/MergeNameDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/MergeSceneDialog.java
- catroid/src/main/res/values/strings.xml
It wasn't possible to merge projects with more than one scene.
> Bugfix of merging scenes

- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
CAT-2262
https://jira.catrob.at/browse/CAT-2262
> CAT-2262 Add When tapped brick to starter bricks

- catroid/catroid.iml
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/PocketMusicActivity.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/mididriver/MidiRunnable.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/trackgrid/TrackGrid.java
Play the corresponding piano sound when clicking a view on the track grid.
> MUS-208 Play a sound on clicking a View

- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ScrollController.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/mididriver/MidiRunnable.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/trackgrid/TrackGrid.java
Playing all the notes of the tact.
> MUS-209 Playing the sounds

- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorCategoryListFragment.java
- catroid/src/main/res/values/strings.xml
Small structural change in Device Variables. Add new header "NFC" for corresponding nfc sensor variables (nfc_tag_id; nfc_tag_message)
> CAT-2141 Add header NFC in device variables for better structure

- catroid/src/androidTest/java/org/catrobat/catroid/test/pocketmusic/note/NoteNameTest.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/NoteName.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/PianoKey.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/PianoView.java
When pressing a View in the trackgird the corresponding piano note should be played.
> MUS-187 Playing the note on pressing the piano key

- catroid/src/main/res/layout/dialog_formulaeditor_string.xml
Please review this pull request.
> CAT-2064 Editing text field in formula editor should be larger than one line

- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/mindstorms/ev3/LegoEV3MotorTest.java
- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProgramMenuActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ScriptActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/PlaySceneDialog.java
added variable startScene, which is the scene which is started when one presses the restart button
> CAT-2216 fixes restard button within scenes

- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProgramMenuActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ScriptActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/PlaySceneDialog.java
Reverts Catrobat/Catroid#2113 - changed base class and added wrong commits from develop
> Revert "CAT-2216 fixes restard button within scenes"

- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/mindstorms/ev3/LegoEV3MotorTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/GlideToBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PlaceAtBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ReplaceItemInUserListBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/SetPenColorBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ShowTextBrick.java
- catroid/src/main/java/org/catrobat/catroid/physics/content/bricks/SetGravityBrick.java
- catroid/src/main/java/org/catrobat/catroid/physics/content/bricks/SetVelocityBrick.java
new pull request for master branch
> CAT-2280 Fixes Edit Formula of bricks with multiple input fields

- catroid/src/main/java/org/catrobat/catroid/content/bricks/ArduinoSendDigitalValueBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ArduinoSendPWMValueBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/InsertItemIntoUserListBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/LegoEv3PlayToneBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/LegoNxtPlayToneBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PhiroRGBLightBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/RaspiPwmBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/RaspiSendDigitalValueBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/SetTextBrick.java
fixes the rest of the bricks, which were missing on CAT-2280
> CAT-2300 fixes Edit Formula on non-standard bricks with multiple input fields

- catroid/src/main/res/layout/activity_my_projects.xml
- catroid/src/main/res/layout/fragment_projects_list.xml
changed position of scrollbar in the programm list from the left to the right side. Formatted the changed files with the coding standart of Android studio.
> CAT-2285 changed position of scrollbar

- catroid/src/main/java/org/catrobat/catroid/utils/SnackBarUtil.java
CAT-2228
https://jira.catrob.at/browse/CAT-2228
> CAT-2228 Apply the font face for hints

- catroid/gradle/code_quality_tasks.gradle
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/UploadProgressDialog.java
- catroid/src/main/res/layout/activity_my_projects.xml
- catroid/src/main/res/layout/fragment_projects_list.xml
```
This commit does *not* fix the Checkstyle warning about the license year.
```
https://jira.catrob.at/browse/CAT-2305
> Fix Checkstyle warnings

- catroid/src/main/java/org/catrobat/catroid/CatroidApplication.java
- catroid/src/main/java/org/catrobat/catroid/ui/AccessibilityPreferencesActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
CAT-2229
https://jira.catrob.at/browse/CAT-2229
> CAT-2229 Apply profile always in main menu after restart

- catroid/src/main/java/org/catrobat/catroid/ui/SettingsActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroid/src/main/java/org/catrobat/catroid/utils/TextSizeUtil.java
CAT-2231
https://jira.catrob.at/browse/CAT-2231
> CAT-2231 Apply fontsize in formula editor with respect to device

- catroid/src/main/res/values/strings.xml
changed broadcast brick default message from message 1 to new message in the string.xml file
> CAT-1708 changed default broadcast brick message

- catroid/src/main/java/org/catrobat/catroid/camera/CameraManager.java
- catroid/src/main/java/org/catrobat/catroid/common/DroneVideoLookData.java
- catroid/src/main/java/org/catrobat/catroid/common/LookData.java
- catroid/src/main/java/org/catrobat/catroid/common/SoundInfo.java
- catroid/src/main/java/org/catrobat/catroid/io/BackpackBrickSerializerAndDeserializer.java
- catroid/src/main/java/org/catrobat/catroid/io/BackpackScriptSerializerAndDeserializer.java
- catroid/src/main/java/org/catrobat/catroid/io/LoadProjectTask.java
- catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java
- catroid/src/main/java/org/catrobat/catroid/io/XStreamBrickConverter.java
- catroid/src/main/java/org/catrobat/catroid/io/XStreamScriptConverter.java
- catroid/src/main/java/org/catrobat/catroid/io/XStreamSettingConverter.java
- catroid/src/main/java/org/catrobat/catroid/io/XStreamSpriteConverter.java
- catroid/src/main/java/org/catrobat/catroid/scratchconverter/ScratchConversionManager.java
- catroid/src/main/java/org/catrobat/catroid/transfers/FetchScratchProgramDetailsTask.java
- catroid/src/main/java/org/catrobat/catroid/transfers/SearchScratchProgramsTask.java
- catroid/src/main/java/org/catrobat/catroid/utils/UtilCamera.java
- catroid/src/main/java/org/catrobat/catroid/utils/UtilZip.java
- catroid/src/main/java/org/catrobat/catroid/web/ServerCalls.java
> Revert "CAT-2150 Firebase Exception Reporting"

- catroid/build.gradle
- catroid/config/lint.xml
- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/mindstorms/ev3/LegoEV3MotorTest.java
- catroid/src/main/java/org/catrobat/catroid/common/TrackingConstants.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BroadcastBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BroadcastReceiverBrick.java
- catroid/src/main/java/org/catrobat/catroid/ui/SettingsActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/UploadProgressDialog.java
- catroid/src/main/java/org/catrobat/catroid/utils/TrackingUtil.java
Adds tracking of:
- Project submission
- Broadcast message creation
- Enabling/Disabling of hints
+ increases versionCode for next release
> CAT-NOLB Additional tracking

- catroid/src/main/java/org/catrobat/catroid/ui/controller/SoundController.java
Sorry for delay in squash commit to one as I am new at this. Please reconsider my commit
> CAT-2203 Crash when adding a sound

- catroid/src/main/java/org/catrobat/catroid/content/bricks/SetPenColorBrick.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
Toast appears only after the back or ok button is pressed and not during the changing of the formula.
> CAT-2123 Toast Bug fixed

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/BrickTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/GoToBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorKeyboardTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/UiTestUtils.java
> CAT Espresso Tests

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/SmokeTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/BrickTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/ForeverBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/GlideToBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/SetColorBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorKeyboardTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/stage/StageTestSimple.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/UiTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/matchers/ScriptListMatchers.java
> GIT Espresso

- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/NewDataDialog.java
- catroid/src/main/res/values/strings.xml
Deleted the checkName function and postponed his functionality into the OK-Button press Event. Introduced another check too(if name consists only of white spaces then error dialog appears). 
Furthermore the OK-Button Event appears in the setOnShowListener. In this case the dialog will not be closed if the OK-Button is pressed and the Customer can digit(input) another name.
> CAT-2122 name check in ok button click event in NewDataDialog

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/StopAllSoundsBrickTest.java
- catroid/src/main/res/values/strings.xml
refactored UI test from Robotium to Espresso
> CAT-XP6 [LS, MS] StopAllSoundsTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/ChangeBrightnessByNBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/ChangeXByNBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/ChangeYByNBrickTest.java
refactored UI tests from Robotium to Espresso for bricks
* ChangeXByNBrick
* ChangeYByNBrick
* ChangeBrightessByNBrick
> CAT-XP6 [LS, MS] Change_ByNTests

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/ComeToFrontBrickTest.java
refactored UI test from Robotium to Espresso
> CAT-XP6 [PM, MS] ComeToFrontBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/NextLookBrickTest.java
Refactor UI test for NextLook brick.
> CAT-XP6 [JK,LS] NextLookBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/TurnLeftBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/TurnRightBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/WaitBrickTest.java
refactored UI tests from Robotium to Espresso
> CAT-XP6 [PM, MS] TurnLeftTurnRightWaitBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/ChangeSizeByNBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/SetTransparencyBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/ShowBrickTest.java
Refactor UI-Test SetTransparencyBrick, ShowBrick, ChangeSizeByNBrick
> CAT-XP6 [JK,LS] SetTransparencyBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/BrickTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/SetVolumeToBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/SetXBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/SetYBrickTest.java
refactored UI tests from Robotium to Espresso
added more versatile FormulaEditor value setter
> CAT-XP6 [PM, MS] SetVolumeSetXSetYBricks, BrickTestUtils

- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/NoteView.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TrackRowView.java
- catroid/src/main/res/values/colors.xml
The tact coloring was made alternating. There is no limitation of two tacts.
> MUS-222 Show 2 tacts on screen with alternating colors

- catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
This is a reopening of https://github.com/Catrobat/Catroid/pull/2174
Credits go to @FleetAdmiral
> CAT-2296 Improve UX for web loading screens

- catroid/src/androidTest/java/org/catrobat/catroid/common/firmata/FirmataUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/arduino/ArduinoImplTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/arduino/ArduinoSettingsTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/phiro/PhiroImplTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uitest/devices/arduino/ArduinoTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uitest/devices/phiro/PhiroTest.java
- catroid/src/main/java/org/catrobat/catroid/devices/arduino/ArduinoImpl.java
- catroid/src/main/java/org/catrobat/catroid/devices/arduino/ArduinoListener.java
Contains a few tests for ArduinoImpl (NOTE: only tests setDigitalArduinoPin() and setAnalogArduinoPin())
> CAT-2322 Arduino output tests

- catroid/src/androidTest/java/org/catrobat/catroid/common/firmata/FirmataUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/arduino/ArduinoImplTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/arduino/ArduinoSettingsTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/phiro/PhiroImplTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uitest/devices/arduino/ArduinoTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uitest/devices/phiro/PhiroTest.java
- catroid/src/main/java/org/catrobat/catroid/devices/arduino/ArduinoImpl.java
- catroid/src/main/java/org/catrobat/catroid/devices/arduino/ArduinoListener.java
Some Refactoring of Arduino code.
Was previously based on [#2120](https://github.com/Catrobat/Catroid/pull/2120), but [#2120](https://github.com/Catrobat/Catroid/pull/2120) has changed in the meantime.
IMPORTANT: please review [#2120](https://github.com/Catrobat/Catroid/pull/2120) first, as I will rebase the CAT-REF commits of this PR onto [#2120](https://github.com/Catrobat/Catroid/pull/2120) then.
> CAT-2319 Arduino refactoring

- catroid/src/main/java/org/catrobat/catroid/utils/SnackBarUtil.java
#CAT-2236
https://jira.catrob.at/browse/CAT-2236
> CAT-2236 Change color scheme of hints

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/ArduinoSendPWMValueBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/BrickTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/PointInDirectionBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/SetBrightnessBrickTest.java
three tests 
PointInDirectionBrickTest
ArduinoSendPWMValueBrickTest
SetBrightnessBrickTest
Comment in BrickTestUtils.java reporting BUG
> CAT-XP6 [MH,KL] ArduinoSendPWMvalueBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/ArduinoSendDigitalValueBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/ChangeColorByNBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/ChangeTransparencyByNBrickTest.java
inkl.
ChangeTransparencyByNBrickTest
ArduinoSendDigitalValueBrickTest
> CAT-XP6[MH, PM] ChangeColorByNBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/LegoEv3MotorMoveBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/SetRotationStyleBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/SpeakBrickTest.java
refactor LegoMotorMoveBrickTest, SetRotationStyleBrickTest and SpeakBrickTest
> CAT-XP6 [JK,LS] SpeakBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/LegoEV3SetLedBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/LegoNXTMotorMoveBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/LegoNXTMotorStopBrickTest.java
includes
LegoEV3SetLedBrickTest
LegoNXTMotorMoveBrickTest
LegoNXTMotorStopBrickTest
> CAT-XP6[MH, PM] LegoBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/arduino/ArduinoImplTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/arduino/ArduinoSettingsTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/pocketmusic/PocketMusicActivityTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/pocketmusic/RecyclerViewMatcher.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/PocketMusicActivity.java
Apply changes suggested by Thomas.
> MUS-225 Refactor of UI espresso tests

- catroid/src/main/java/org/catrobat/catroid/common/TrackingConstants.java
- catroid/src/main/java/org/catrobat/catroid/utils/TrackingUtil.java
Tracks the versionCode in customEvents in the create@school flavor
> CAT-2357 Track versionCode 

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/BrickTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/DeleteItemOfUserListBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uitest/util/UiTestUtils.java
Refactored UI test from Robotium to Espresso
> CAT-XP6 [KL, MS] DeleteItemOfUserListBrickTest

- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TrackRowView.java
- catroid/src/main/res/values/colors.xml
Only some minor color changes to be visually more pleasing.
> MUS-226 Change the grey values for the note views

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/pocketmusic/PocketMusicActivityTest.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TactScrollRecyclerView.java
- catroid/src/main/res/layout/pocketmusic_add_tact_button.xml
- catroid/src/main/res/values/dimens.xml
- catroid/src/main/res/values/strings.xml
Added a Button at the end of the recyclerview which adds a new
tact when clicked.
> MUS-217 Show a plus button at the end of the Tact Scroller

- catroid/src/main/java/org/catrobat/catroid/content/Look.java
this slipped though my checks of a recently merged PR ;)
> removed one unused import

- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
Added a lot of nullchecks for many function types - this was not in the scope of this issue, but leaving it would create a lot more issues in the long run (better to fix it straight away).
Corrected some nullchecks.
Did some minor refactoring.
> CAT-2082 Crash related to multitouch sensors

- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
Fixes all current Checkstyle warnings in the develop branch https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidCheck/387/
> CAT-FIX Checkstyle warnings

- catroid/src/main/java/org/catrobat/catroid/ui/AccessibilityPreferencesActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/AccessibilityProfilesActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/adapter/AccessibilityCheckboxAdapter.java
#CAT-2363
https://jira.catrob.at/browse/CAT-2363
> CAT-2363 Apply font size within accessibility settings

- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
#CAT-2358
https://jira.catrob.at/browse/CAT-2358
> CAT-2358 Fix help link for ev3 bricks

- catroid/src/main/java/org/catrobat/catroid/content/Project.java
- catroid/src/main/java/org/catrobat/catroid/content/Scene.java
- catroid/src/main/java/org/catrobat/catroid/merge/MergeTask.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ScriptFragment.java
Duplicate of https://github.com/Catrobat/Catroid/pull/2237 for the NOLB branch.
> CAT-2353 Broadcast messages are only removed if they don't exist in any scene of a project

- catroid/src/main/java/org/catrobat/catroid/ui/SettingsActivity.java
- catroid/src/main/java/org/catrobat/catroid/utils/TextSizeUtil.java
- catroid/src/main/res/layout/preference_enlarged.xml
- catroid/src/main/res/layout/preferencecategory_enlarged.xml
- catroid/src/main/res/xml/preferences.xml
#CAT-2235
https://jira.catrob.at/browse/CAT-2235
> CAT-2235 Apply font size within settings

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/BrickTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/GoToBrickTest.java
Added functions for checking spinner values, etc.
> CAT-Espresso Updated BrickTestUtils

- catroid/src/main/java/org/catrobat/catroid/formulaeditor/SensorHandler.java
Added new methods for getting default device rotation and for checking if the orientation needs to be flipped and used them for the appropriate functions (tilt, acceleration, ...) in the SensorHandler, removed unnecessary boxing.
rotateOrientation() will return 0 if the orientation should not be rotated, 1 & -1 if it should be rotated 90° in one or another direction.
> CAT-1611 X/Y axis flip with large (horizontal layout) tablets

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/LoopBrickTest.java
Implements the basic parts of the LoopBrickTest:
* testForeverBrick
* testRepeatBrick
These original testscase are still missing:
* testNestedForeverBricks
* testCopyForeverBrickActionMode
* testSelectionAfterCopyActionMode
* testSelectionActionMode
* testLoopEndBrickCheckBoxVisibleActionMode
> CAT-XP6 [LS,KL] LoopBrickTest

- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroid/src/main/java/org/catrobat/catroid/utils/BorderTextView.java
- catroid/src/main/java/org/catrobat/catroid/utils/FormulaEditorIntroUtil.java
- catroid/src/main/java/org/catrobat/catroid/utils/SnackbarUtil.java
- catroid/src/main/res/layout/formula_editor_intro_dialog.xml
- catroid/src/main/res/values/colors.xml
- catroid/src/main/res/values/strings.xml
#CAT-2213
https://jira.catrob.at/browse/CAT-2213
> CAT-2213 Intro for formula editor

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/annotations/Device.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/PlaySoundBrickTest.java
move from Robotium to Espresso framework
> CAT-XP6 [AS, MS] PlaySoundBrickTests

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/PlaySoundAndWaitBrickTest.java
move from Robotium to Espresso framework, add idling resource to SoundRecorderActivity
> CAT-XP6 [KL, MS] PlaySoundAndWaitBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/AddItemToUserListTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/BrickTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/GoNStepsBackTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/MoveNStepsBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/RepeatBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/SceneTransmitionBrickTest.java
> CAT-XP6 [MH, PH] AddItemToUserListTest

- catroid/src/main/java/org/catrobat/catroid/content/actions/ComeToFrontAction.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/GoNStepsBackAction.java
This pull request simplify ComeToFront and MoveNSteps
> CAT-2348 ComeToFront and MoveNSteps simplification

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/AskBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/utils/FormulaTextFieldUtils.java
Damit es niemandem langweilig wird ;-)
> CAT-XP6[PM, KL] AskBrickTest

- catroid/config/checkstyle_suppressions.xml
adapt checkstyle suppression rule for Windows
> CAT-2426 Fix checkstyle errors for ellipsis character

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/AskBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/UserVariableTestUtils.java
Added untility to perform assertions on user variable changes in stage.
Added AskBrickTest.
> CAT-2454 GSOC[TH] Espresso AskBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/WhenNfcBrickStageTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/WhenNfcBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/utils/UiNFCTestUtils.java
Refactor and rewrite whenNfcBrickTest for Espresso
> CAT-2314 Rewrite WhenNfcBrickTest for Espresso

- catroid/src/main/java/org/catrobat/catroid/common/LookData.java
- catroid/src/main/java/org/catrobat/catroid/common/defaultprojectcreators/DefaultProjectCreatorDefault.java
- catroid/src/main/java/org/catrobat/catroid/content/WhenConditionScript.java
- catroid/src/main/java/org/catrobat/catroid/io/CatroidFieldKeySorter.java
- catroid/src/main/java/org/catrobat/catroid/io/XStreamBrickConverter.java
This pull request includes the implementation of manual crash reporting system using Crashlytics.
> CAT-2427 Crashlytics manual crash reporting

- catroid/src/main/java/org/catrobat/catroid/ui/BaseActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/SendReportDialog.java
- catroid/src/main/java/org/catrobat/catroid/utils/CrashReporter.java
- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
This pull request includes the modified version of CrashReporter.checkIfCrashRecoveryAndFinishActivity where the unrelated code is removed.
> CAT-2467 CrashReporter.CheckIfCrashRecoveryAndFinishActivity

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/SceneTest.java
- catroid/src/main/java/org/catrobat/catroid/content/Scene.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BrickWithSpriteReference.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/CloneBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PointToBrick.java
- catroid/src/main/java/org/catrobat/catroid/ui/controller/BackPackScriptController.java
As this fix is not only relevant to feature/NOLB this fix should be merged into develop, too.
see #2374
> CAT-2476 Fix CloneBrick grouping functionality

- catroid/src/main/java/org/catrobat/catroid/content/bricks/FormulaBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/LegoEv3MotorMoveBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/LegoEv3MotorStopBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/LegoEv3MotorTurnAngleBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/LegoEv3SetLedBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/LegoNxtMotorMoveBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/LegoNxtMotorStopBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/LegoNxtMotorTurnAngleBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PhiroMotorMoveBackwardBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PhiroMotorMoveForwardBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PhiroMotorStopBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PhiroPlayToneBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PhiroRGBLightBrick.java
- catroid/src/main/res/layout/brick_ev3_motor_move.xml
- catroid/src/main/res/layout/brick_ev3_motor_stop.xml
- catroid/src/main/res/layout/brick_ev3_motor_turn_angle.xml
- catroid/src/main/res/layout/brick_nxt_motor_action.xml
- catroid/src/main/res/layout/brick_nxt_motor_stop.xml
- catroid/src/main/res/layout/brick_nxt_motor_turn_angle.xml
See
https://jira.catrob.at/browse/CAT-2323
for detailed description
> CAT-2323 Fixed Backpack-Unpacking bug

- catroid/src/main/java/org/catrobat/catroid/web/ServerCalls.java
- catroid/src/main/res/layout/brick_note.xml
- catroid/src/main/res/layout/brick_say_bubble.xml
- catroid/src/main/res/layout/brick_think_bubble.xml
Fixes crashes + error messages
> NOLB bugfixes release 0.9.29

- catroid/build.gradle
Added a feature flag FEATURE_CLOUD_MESSAGING to build.gradle file.
> CAT-2475 Add Feature Flag for Firebase Cloud Messaging

- catroid/build.gradle
- catroid/src/androidTest/java/org/catrobat/catroid/test/cloudmessaging/CloudMessageTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/cloudmessaging/CustomFirebaseMessagingServiceTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/scratchconverter/WebSocketClientTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/MainMenuActivityTest.java
- catroid/src/main/AndroidManifest.xml
- catroid/src/main/java/org/catrobat/catroid/cloudmessaging/CloudMessage.java
- catroid/src/main/java/org/catrobat/catroid/cloudmessaging/CloudMessaging.java
- catroid/src/main/java/org/catrobat/catroid/cloudmessaging/CustomFirebaseMessagingService.java
- catroid/src/main/java/org/catrobat/catroid/cloudmessaging/NotificationBuilderProvider.java
- catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
- catroid/src/main/java/org/catrobat/catroid/utils/StatusBarNotificationManager.java
This pull request includes the implementation of cloud messaging with custom parameters.
> CAT-2471 Adding parameters to sent Cloud Message

- catroid/src/main/res/values/strings.xml
Correcting the sequence of CrashReporter Preference strings in
strings.xml
> CAT-FIX Correction in Preference sequence of CrashReporter Strings

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/BaseExceptionHandlerTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/utils/SettingsActivityCrashReporterTest.java
Updated the two test files BaseExceptionHandlerTest.java and SettingsActivityCrashReporterTest.java
> CAT-FIX Remove deprecated code from test

- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
Fixed error which was occured on calling Utils.showErrorDialog at
ProjectManager.java
Error url:- https://console.firebase.google.com/u/0/project/firebase-catrobat/monitoring/app/android:org.catrobat.catroid/cluster/09ea9d7c?duration=2592000000&appVersions=35
> CAT-FIX Resolve ShowDialog Error On ProjectManager

- catroid/src/androidTest/java/org/catrobat/catroid/test/formula/FormulaTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/formula/SensorListenerTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/formula/UserVariableTest.java
- catroid/src/main/java/org/catrobat/catroid/formula/DataProvider.kt
- catroid/src/main/java/org/catrobat/catroid/formula/Formula.java
- catroid/src/main/java/org/catrobat/catroid/formula/FormulaInterpreter.kt
- catroid/src/main/java/org/catrobat/catroid/formula/SensorDataProvider.kt
- catroid/src/main/java/org/catrobat/catroid/formula/function/BinaryFunctionToken.kt
- catroid/src/main/java/org/catrobat/catroid/formula/function/FunctionToken.kt
- catroid/src/main/java/org/catrobat/catroid/formula/function/UnaryFunctionToken.kt
- catroid/src/main/java/org/catrobat/catroid/formula/operator/BinaryOperatorToken.kt
- catroid/src/main/java/org/catrobat/catroid/formula/operator/UnaryOperatorToken.kt
- catroid/src/main/java/org/catrobat/catroid/formula/sensor/SensorListener.kt
- catroid/src/main/java/org/catrobat/catroid/formula/value/ValueToken.kt
> [GSoC17] CAT-2505 Refactored Boolean Values to Evaluate to Double

- catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
Fixing a minor sub-bug to make correction to dispose of the texture
> CAT-2371 Correction in Textures Disposal

- catroid/src/main/java/org/catrobat/catroid/ui/MyProjectsActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectListFragment.java
Fixed NullPointerException of onLoadProjectSuccess
Error:- Exception java.lang.Throwable: Attempt to invoke virtual method
'java.lang.String android.content.Context.getPackageName()' on a null
object reference
Error url:-
https://console.firebase.google.com/u/0/project/firebase-catrobat/monitoring/app/android:org.catrobat.catroid/cluster/077bd744?duration=2592000000
> CAT-FIX NullPointerException At ProjectListFragment

- catroid/src/androidTest/java/org/catrobat/catroid/test/common/LookDataTest.java
- catroid/src/main/java/org/catrobat/catroid/common/LookData.java
- catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
Changed the method name in LookData and improved the image disposal in
StageListener
> CAT-FIX Improve Image Disposal

- catroid/src/main/java/org/catrobat/catroid/content/actions/HideTextAction.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/HideTextBrick.java
UserVariable is null and resulting in 'java.lang.String org.catrobat.catroid.formulaeditor.UserVariable.getName()' on a null object reference
Error URL:-
https://console.firebase.google.com/u/0/project/firebase-catrobat/monitoring/app/android:org.catrobat.catroid/cluster/c5523444?duration=2592000000
Also fixed the issue where "NoVariableSet" was visible even after adding
the hide brick.
> CAT-FIX UserVariable Null at HideTextBrick.java

- catroid/src/main/java/org/catrobat/catroid/ui/BaseExceptionHandler.java
Added a CrashReporter logging at BaseExceptionHandler.java file
> CAT-FIX Logging Exception At BaseExceptionHandler

- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectListFragment.java
getActivity() is null while calling runOnUiThread() method.
Error URL:
https://console.firebase.google.com/u/0/project/firebase-catrobat/monitoring/app/android:org.catrobat.catroid/cluster/e70cc96e
> CAT-FIX Null Value Of getActivity() at ProjectListFragment

- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
#CAT-2528
https://jira.catrob.at/browse/CAT-2528
> CAT-2528 Add chromecast help link

- catroid/src/main/java/org/catrobat/catroid/common/defaultprojectcreators/DefaultProjectCreatorDefault.java
Even though the Sprites Clouds1 and Clouds2 share a lot of code, they
shouldn't share bricks.
The DefaultProjectCreatorDefault is quite a mess. So I only quickly fixed the references.
The new example program xml output. As you can see, no brick references.
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<program>
<header>
<applicationBuildName></applicationBuildName>
<applicationBuildNumber>0</applicationBuildNumber>
<applicationName>Pocket Code</applicationName>
<applicationVersion>0.9.29</applicationVersion>
<catrobatLanguageVersion>0.994</catrobatLanguageVersion>
<dateTimeUpload></dateTimeUpload>
<description></description>
<deviceName>Nexus 6</deviceName>
<isCastProject>false</isCastProject>
<landscapeMode>false</landscapeMode>
<mediaLicense></mediaLicense> …
```
> CAT-1873 Remove brick references in example program

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/sprite/NumberOfBricksTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/testsuites/AllEspressoTestsSuite.java
- catroid/src/main/java/org/catrobat/catroid/ui/adapter/SpriteAdapter.java
espresso Test has activity switching.
if you have another scenario for the test, please let me know
> CAT-1900 Amount of Bricks (Show details) is wrong 

- catroid/src/main/res/values-ko/strings.xml
- catroid/src/main/res/values-sw/strings.xml
Updated korean strings for hotfix.
Changed the folder name for Swahili strings + string update.
> CAT-String Update: Updated Strings for Hotfix.

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/testsuites/AllEspressoTestsSuite.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/HindiNumberAtShowDetailsAtProjectActivityTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/LanguageSwitchMainMenuTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/RtlUiTestUtils.java
- catroid/src/main/java/org/catrobat/catroid/ui/adapter/SpriteAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/controller/LookController.java
**Numbering styles vary depending on the region. bidirectional languages numbering style may be implemented by either Hindi digits or Arabic digits**
> CAT-2382 Numbering style for bidirectional languages

- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/transfers/CheckTokenTask.java
- catroid/src/main/java/org/catrobat/catroid/ui/BaseActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/LogInDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/OAuthUsernameDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/PrivacyPolicyDialogFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/RegistrationDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/SignInDialog.java
- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
- catroid/src/main/res/layout/dialog_privacy_policy.xml
- catroid/src/main/res/menu/menu_main_menu.xml
- catroid/src/main/res/values/strings.xml
CAT-2554 Make Privacy Policy available offline within Pocket Code
CAT-2555 Affirmation of Privacy Policy at Registration of a new account
CAT-2556 Show existing users Affirmation Dialogue for Privacy Policy
> CAT-2555 privacy policy on register

- catroid/src/main/java/org/catrobat/catroid/ui/BaseMainMenuActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProgramMenuActivity.java
- catroid/src/main/java/org/catrobat/catroid/utils/IconsUtil.java
#CAT-2529
https://jira.catrob.at/browse/CAT-2529
> CAT-2529 Dynamic icons for main and program menu

- catroid/src/main/java/org/catrobat/catroid/ui/BaseSettingsActivity.java
- catroid/src/main/java/org/catrobat/catroid/utils/TextSizeUtil.java
- catroid/src/phiro/java/org/catrobat/catroid/ui/SettingsActivity.java
#CAT-2552
https://jira.catrob.at/browse/CAT-2552
> CAT-2552 Dynamic textsize for settings

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/JumpingSumoAnimationBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/JumpingSumoSoundBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/testsuites/AndroidPackageRunner.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/RenameSpriteDialogTest.java
- catroid/src/main/res/layout/brick_jumping_sumo_animations.xml
Make this smaller and cleaner and remove the constructor madness that
is coming from Suites.class (from which this class is "inspired").
> CAT-Refactor AndroidPackageRunner

- catroid/src/androidTest/java/org/catrobat/catroid/test/utils/Reflection.java
- catroid/src/androidTestCreateatschool/java/org/catrobat/catroid/createatschool/uiespresso/ui/activity/RestrictedLoginTest.java
- catroid/src/catroid/java/org/catrobat/catroid/ui/dialogs/PrivacyPolicyDialogFragment.java
- catroid/src/createatschool/java/org/catrobat/catroid/ui/dialogs/PrivacyPolicyDialogFragment.java
- catroid/src/createatschool/res/layout/dialog_privacy_policy.xml
- catroid/src/createatschool/res/values-de/strings.xml
- catroid/src/createatschool/res/values/strings.xml
- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/BasePrivacyPolicyDialogFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/RestrictedLoginDialog.java
- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
- catroid/src/main/res/values/strings.xml
- catroid/src/phiro/java/org/catrobat/catroid/ui/dialogs/PrivacyPolicyDialogFragment.java
- catroid/src/standalone/java/org/catrobat/catroid/ui/dialogs/PrivacyPolicyDialogFragment.java
Add PrivacyPolicyDialog to createatschool/restricted login and fix crash on logout
> Add PrivacyPolicyDialog to createatschool/restricted login

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/rtl/RtlBrickTest.java
related to **CAT-2360** Right-to-Left support for Bricks
> right-to-lift Bricks test

- catroid/src/main/res/values/strings.xml
As Prof. Slany recommended:
change the text of language description to "select the Language of the App"
> Summary Text Of Language Setting

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/FlashBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/VibrationBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/FlashBrickStageTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/VibrationBrickStageTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/WhenNfcBrickHardwareStageTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/UserVariableTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/hardware/SensorTestArduinoServerConnection.java
Write new and refactor old Arduino Hardware tests for Espresso
> CAT-2313 Rewrite Arduino sensorbox hardware tests for Espresso

- catroid/build.gradle
- catroid/src/androidTest/java/org/catrobat/catroid/test/utils/DividerUtilTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/utils/IconsUtilTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/utils/TestTextSizeUtil.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/AccessibilityPreferencesActivityTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/AccessibilityProfilesActivityTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/utils/AccessibilityActivitiesUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/matchers/AccessibilityCheckboxMatchers.java
- catroid/src/main/java/org/catrobat/catroid/ui/AccessibilityPreferencesActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/BaseMainMenuActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/BaseSettingsActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/adapter/BrickCategoryAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/dragndrop/DragAndDropListView.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/BaseBrickCategoryFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/java/org/catrobat/catroid/utils/BrickEditText.java
- catroid/src/main/java/org/catrobat/catroid/utils/BrickSpinner.java
- catroid/src/main/java/org/catrobat/catroid/utils/BrickTextView.java
- catroid/src/main/java/org/catrobat/catroid/utils/DividerUtil.java
- catroid/src/main/java/org/catrobat/catroid/utils/IconsUtil.java
- catroid/src/main/java/org/catrobat/catroid/utils/TextSizeUtil.java
- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
#CAT-2582
https://jira.catrob.at/browse/CAT-2582
> CAT-2582 Accessibility tests and refactor

- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
#CAT-2605
https://jira.catrob.at/browse/CAT-2605
> CAT-2605 Add jumping sumo help link

- catroid/src/main/res/layout/activity_accessibility_preferences.xml
- catroid/src/main/res/layout/activity_accessibility_profiles.xml
- catroid/src/main/res/values-ar/strings.xml
add the Arabic translation for Accessibility setting
> refactoring some xml attributes to support R2L languages

- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/java/org/catrobat/catroid/utils/IconsUtil.java
- catroid/src/main/res/layout/brick_jumping_sumo_animations.xml
- catroid/src/main/res/layout/brick_jumping_sumo_jump_high.xml
- catroid/src/main/res/layout/brick_jumping_sumo_jump_long.xml
- catroid/src/main/res/layout/brick_jumping_sumo_move_backward.xml
- catroid/src/main/res/layout/brick_jumping_sumo_move_forward.xml
- catroid/src/main/res/layout/brick_jumping_sumo_nosound.xml
- catroid/src/main/res/layout/brick_jumping_sumo_rotate_left.xml
- catroid/src/main/res/layout/brick_jumping_sumo_rotate_right.xml
- catroid/src/main/res/layout/brick_jumping_sumo_sound.xml
- catroid/src/main/res/layout/brick_jumping_sumo_taking_picture.xml
- catroid/src/main/res/layout/brick_jumping_sumo_turn.xml
#CAT-2604
https://jira.catrob.at/browse/CAT-2604
> CAT-2604 Add icons to jumping sumo bricks

- automationScripts/createBetaTestingPocketCodeAPK.py
to by default output an application named "versionname + beta"
> CAT-Automation updating test apk generation script

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/SettingsActivityTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/BaseSettingsActivity.java
- catroid/src/main/java/org/catrobat/catroid/utils/DynamicListPreference.java
- catroid/src/main/java/org/catrobat/catroid/utils/TextSizeUtil.java
- catroid/src/main/res/layout/activity_main_menu_with_dividers.xml
- catroid/src/main/res/layout/brick_category_drone_js.xml
- catroid/src/main/res/layout/brick_ev3_motor_move.xml
- catroid/src/main/res/layout/brick_ev3_motor_stop.xml
- catroid/src/main/res/layout/brick_ev3_motor_turn_angle.xml
- catroid/src/main/res/layout/brick_ev3_play_tone.xml
- catroid/src/main/res/layout/brick_ev3_set_led.xml
- catroid/src/main/res/layout/brick_jumping_sumo_animations.xml
- catroid/src/main/res/layout/brick_jumping_sumo_jump_high.xml
- catroid/src/main/res/layout/brick_jumping_sumo_jump_long.xml
- catroid/src/main/res/layout/brick_jumping_sumo_move_backward.xml
- catroid/src/main/res/layout/brick_jumping_sumo_move_forward.xml
- catroid/src/main/res/layout/brick_jumping_sumo_nosound.xml
- catroid/src/main/res/layout/brick_jumping_sumo_rotate_left.xml
- catroid/src/main/res/layout/brick_jumping_sumo_rotate_right.xml
- catroid/src/main/res/layout/brick_jumping_sumo_sound.xml
- catroid/src/main/res/layout/brick_jumping_sumo_taking_picture.xml
- catroid/src/main/res/layout/brick_jumping_sumo_turn.xml
- catroid/src/main/res/layout/dialog_languages.xml
- catroid/src/main/res/layout/list_language_item.xml
- catroid/src/main/res/layout/list_language_item_enlarged.xml
- catroid/src/main/res/values/dimens.xml
#CAT-2610
https://jira.catrob.at/browse/CAT-2610
> CAT-2610 Fixes for sizes and visual glitches

- catroid/src/main/java/org/catrobat/catroid/utils/CrashReporter.java
Copy of https://github.com/Catrobat/Catroid/pull/2624 for NOLB
> CAT-FIX Crash when opening project on first app startup

- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ShowDetailsFragment.java
> CAT-2545 SceneList shows wrong contextMenu & ShowDetailsFragment has contextMenu

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PhiroColorBrickTest.java
Refactored PhiroColorBrickTest from Robotium to Espresso
> CAT-2590 refactored PhiroColorBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/test/utiltests/UtilFileSizeTranslationsTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/rtl/RtlBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/HindiNumberAtShowDetailsAtProjectActivityTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/LanguageSwitchThroughSharedPreferenceTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/RtlUiTestUtils.java
- catroid/src/main/java/org/catrobat/catroid/CatroidApplication.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/MyProjectsActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProgramMenuActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ScriptActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/SettingsActivity.java
add the new supported Languages.
fix the problem with change language on API >= 25
> CAT-2618 Language reset to device language on restart

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorFunctionListTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/matchers/FormulaEditorFunctionListMatchers.java
Added the FormulaEditorListFragmentTest which is implemented as a parameterized test
Also added a new Matcher.
> CAT-2601 refactored FormulaEditorListFragmentTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PlaySoundAndWaitBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorAddVariableTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorDeleteVariableTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormularEditorVariableScopeTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/UserDataItemRVInteractionWrapper.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/UserListDataItemRVInteractionWrapper.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/UserVariableDataItemRVInteractionWrapper.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/ProjectActivityNumberOfBricksRegressionTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/HindiNumberAtShowDetailsAtProjectActivityTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/DeleteLookDialogTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/DeleteSoundDialogTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/DeleteSpriteDialogTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/RenameSpriteDialogTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CopyLookTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CopyProjectTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CopySoundTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteLookTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteProjectTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteSoundTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameLookTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameProjectTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameSoundTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/rvutils/RecyclerViewInteractionWrapper.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/rvutils/RecyclerViewItemInteractionWrapper.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/rvutils/RecyclerViewItemMatcher.java
-Add tests for FormulaEditorDataFragment
-Split RecyclerViewInteractionWrapper to RecycerViewItemInteractionWrapper and RecycerViewInteractionWrapper
-Split RecyclerViewMatcher to RecycerViewItemMatcher and RecyclerViewMatcher
> CAT-2596 reimplement FormulaEditorDataFragmentListTest in espresso

- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
* add the new languages "uk" and "kn" to the language list
> CAT-2664 updating language List

- catroid/src/main/java/org/catrobat/catroid/ui/ScratchConverterActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ScratchProgramDetailsActivity.java
- catroid/src/main/res/layout/activity_scratch_converter.xml
- catroid/src/main/res/layout/activity_scratch_project_details.xml
*because of missing toolbar layout
*using SupportActionBar instead of ActionBar
> Scratch Converter wont open

- catroid/src/main/java/org/catrobat/catroid/pocketmusic/PocketMusicActivity.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ScrollController.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TactScrollRecyclerView.java
Fix the problem where none of our vies were showing up.
> MUS-241 TrackGrid does not display anything

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/PlaySoundBrickStageTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/testsuites/SensorboxTestSuite.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/hardware/SensorTestArduinoServerConnection.java
+ Add test with Arduino SensorServerBox if audio is played from PlaySoundBrick.
+ Add SensorboxTestSuite.java for testruns on Jenkins
+ update SensorTestArduinoServerConnection.java with timeout (already) on Socket creation.
> CAT-2312 Add Audio Test for SensorBox

- catroid/src/main/java/org/catrobat/catroid/common/ScratchVisibilityState.java
- catroid/src/main/java/org/catrobat/catroid/scratchconverter/protocol/Job.java
- catroid/src/main/java/org/catrobat/catroid/scratchconverter/protocol/message/Message.java
- catroid/src/main/java/org/catrobat/catroid/scratchconverter/protocol/message/base/BaseMessage.java
- catroid/src/main/java/org/catrobat/catroid/scratchconverter/protocol/message/job/JobMessage.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
- catroid/src/main/java/org/catrobat/catroid/utils/TouchUtil.java
I left in the usage of HashMap in ScratchConversionManager because it's used for a synchronizedMap there.
> [CAT-2666] - Refactor usages of Map to SparseArray

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PhiroSeekBarColorBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/utils/CustomSwipeAction.java
Refactored PhiroSeekBarColorBrickTest from Robotium to Espresso.
Created a test for every color seek bar. (Red, Green, Blue)
The seek bar is controlled via Swipe ViewAction.
> CAT-2591 refactored PhiroSeekBarColorBrickTest

- catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
this will fix AskBrickStageTest
> CAT-2679 ask-brick has incompatible theme with stageActivity

- catroid/src/androidTest/java/org/catrobat/catroid/common/bluetooth/ObservedOutputStream.java
ObservedOutputStream (proxy for OutputStream) did not handle flush
> [CAT-2602] Fix testI2CUltrasonicSensor

- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenNfcBrick.java
* missing method setCheckboxView(id);
> CAT-2678 When NFC Brick don't allow to copy/disable/delete through the Context Menu

- catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveBackwardBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveDownBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveForwardBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveLeftBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveRightBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveUpBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneTurnLeftBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneTurnLeftMagnetoBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneTurnRightBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneTurnRightMagnetoBrick.java
* missing default case in switch statement :(
> CAT-2677 Edit Formula don't work with AR.Drone Bricks

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/pocketmusic/PocketMusicActivityTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/pocketmusic/RecyclerViewMatcher.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ScrollController.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/mididriver/MidiRunnable.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/trackgrid/TrackGrid.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/AnimatorUpdateCallback.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/PianoView.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TactScrollRecyclerView.java
- catroid/src/main/res/layout/pocketmusic_empty_view.xml
Change the animation when pressing the play button and make it possible to play multiple tacts.
> MUS-219 PlayAnimation for multiple tacts

- catroid/src/main/java/org/catrobat/catroid/pocketmusic/PocketMusicActivity.java
- catroid/src/main/res/layout/activity_pocketmusic.xml
The bugfix fixes the issue with the not shown toolbar.
> MUS-242 Toolbar missing in pocketmusic activity

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorEditTextGenericTests.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorEditTextTest.java
> CAT-2598 Refactor FormulaEditorEditTextTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PenBricksTest.java
- check of elements in color chooser view added
> CAT-2589 reimplement PenBricksTest

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/controller/LookControllerTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/content/controller/SceneControllerTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/content/controller/SoundControllerTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/content/controller/SpriteControllerTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackLookFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackSceneFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackSpriteFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SceneController.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SpriteController.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/NfcTagListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SceneListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.java
Also slightly changed controller behaviour. Copying and packing no longer has side effects i.e. objects are not added to respective lists inside the controller methods.
> [TESTING] Added Sprite and Scene Controller Tests

- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/LegoSensorPortConfigDialog.java
- catroid/src/main/res/values/strings.xml
-fix bug introduced with CAT-2683
> CAT-FIX fix crashing LegoSensorPortConfigDialog

- catroid/src/main/java/org/catrobat/catroid/pocketmusic/PocketMusicActivity.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ScrollController.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/fastscroller/FastScroller.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/fastscroller/RecyclerViewScrollListener.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/fastscroller/SectionTitleProvider.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/fastscroller/viewprovider/DefaultBubbleBehavior.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/fastscroller/viewprovider/DefaultHandleBehavior.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/fastscroller/viewprovider/DefaultScrollerViewProvider.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/fastscroller/viewprovider/ScrollerViewProvider.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/fastscroller/viewprovider/ViewBehavior.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/fastscroller/viewprovider/VisibilityAnimationManager.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/ui/TactScrollRecyclerView.java
- catroid/src/main/res/animator/pocketmusic_fastscroller_fade_in.xml
- catroid/src/main/res/animator/pocketmusic_fastscroller_fade_out.xml
- catroid/src/main/res/animator/pocketmusic_fastscroller_hide.xml
- catroid/src/main/res/animator/pocketmusic_fastscroller_show.xml
- catroid/src/main/res/drawable/pocketmusic_fastscroller_bubble.xml
- catroid/src/main/res/drawable/pocketmusic_fastscroller_handle.xml
- catroid/src/main/res/layout/activity_pocketmusic.xml
- catroid/src/main/res/layout/pocketmusic_fastscroller_bubble.xml
- catroid/src/main/res/values/attrs.xml
- catroid/src/main/res/values/dimens.xml
Implement a fast scroller so you can navigate faster through the tacts.
Also show in which tact you are, when you are scrolling with the fastscroller.
> MUS-220: Navigation though tacts

- Jenkinsfile
Set the data partition size of the AVD to 512M
> Fix tests on emulator caused by INSTALL_FAILED_INSUFFICIENT_STORAGE exception

- catroid/src/androidTest/java/org/catrobat/catroid/test/io/XstreamSerializerTest.java
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
This is just a fix. No improvements, refactorings or similar :open_mouth:
> CAT-FIX Fix no preview images for programs

- Jenkinsfile.BuildStandalone
- Jenkinsfile.ManualTests
- Jenkinsfile.PullRequest
- Jenkinsfile.PullRequestEspresso
- Jenkinsfile.PullRequestIndependentAPK
- Jenkinsfile.PullRequestStandaloneAPK
- buildScripts/build_step_create_standalone_apk
- docker/Dockerfile.jenkins
Additionally group the environement variables to better reflect their usage in all Jenkinsfiles.
> JENKINS-209: Add Pipeline-Scripts for all current Jobs

- buildScripts/build_helper_functions.py
and not run on every build step (on a local developer machine).
> JENKINS-208: Make the SDK install step explicit only

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/SettingsFragmentTest.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/common/SharedPreferenceKeys.java
- catroid/src/main/java/org/catrobat/catroid/scratchconverter/ScratchConversionManager.java
- catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ScratchConverterActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/SignInActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackLookFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackSceneFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackSoundFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackSpriteFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/PrivacyPolicyDialogFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SceneListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/scratchconverter/ScratchSearchResultsFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/settingsfragments/AccessibilityProfilesFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/settingsfragments/SettingsFragment.java
- issues were cause by incorrect settings key.
- moved share preference key to single file.
- still removed check from login as per PO request.
> [FIX] No longer shows Privacy Policy Fragment on login

- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/content/Script.java
- catroid/src/main/java/org/catrobat/catroid/content/StartScript.java
- catroid/src/main/java/org/catrobat/catroid/content/WhenClonedScript.java
- catroid/src/main/java/org/catrobat/catroid/content/WhenGamepadButtonScript.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BroadcastBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BroadcastMessageBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BroadcastReceiverBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BroadcastWaitBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ScriptBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/UserScriptDefinitionBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenBackgroundChangesBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenClonedBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenConditionBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenGamepadButtonBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenNfcBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenTouchDownBrick.java
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
- catroid/src/main/java/org/catrobat/catroid/physics/content/bricks/CollisionReceiverBrick.java
- removed isUserScript from StartScript.
- removed unnecessary overrides.
> [GSoC18] Refactored Scripts (Language version update)

- catroid/src/androidTest/java/org/catrobat/catroid/test/utils/UniqueNameProviderTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/util/UniqueNameProvider.java
- Add tests for UniqueNameProvider
- Simplify UniqueNameProvider by using regex groups
> Refactor unique name provider

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/BrickValueParameterTest.java
- catroid/src/main/java/org/catrobat/catroid/common/BrickValues.java
- catroid/src/main/java/org/catrobat/catroid/stage/PenActor.java
- thickness approximately 0.5mm for the default pen size
- creator screen size also effects setPenSizeBrick
> CAT-2717 Consistent pen size over any screen

- Jenkinsfile
Per Branch / Pull Request only the last 30 builds should be kept.
> JENKINS-196 Keep only the last 30 builds per branch/pull request

- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
Revert Catrobat/Catroid#2939 because of new bugs - NO RELEASE happened
> Revert "Hotfix 0.9.40"

- Jenkinsfile
The generated APKs are accessible from the Jenkins jobs, including PR jobs.
> JENKINS-231 Do not upload APKs from develop to files.catrob.at.

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/script/WhenConditionScriptTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/WhenConditionBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/content/WhenConditionScript.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenConditionBrick.java
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- removed unnecessary constructors, that allowed
for creation of WhenConditionBrick in illegal state.
- refactored and cleaned WhenConditionScript initialisation.
- added test.
> CATROID-52 Fix WhenConditionBrick

- Jenkinsfile.SensorboxTests
JENKINS-210-FixSensorBoxTests - Add Jenkinsfile to run the hardwaretests on the sensorbox
> JENKINS-210-FixSensorBoxTests 

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/regression/activitydestroy/SpriteListFragmentActivityRecreateRegressionTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/RecyclerViewFragment.java
- prevent crashes during crash-recovery (crashception).
> CATROID-74 Moved finishActionMode() to onStop().

- catroid/build.gradle
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SetBackgroundBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SetLookBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/VariableBrickTest.java
- fixed issues with missing string, that was obfuscated by translation
workflow -> missing strings only show up when all translations of
this string are removed.
- increased version code for Google Play.
> [RELEASE] Fix issues with missing strings, increased version code.

- Jenkinsfile
> CATROID-102 JENKINS-261 The 'test this please' PR-comment triggers a Jenkins rebuild.

- catroid/src/androidTest/java/org/catrobat/catroid/test/io/DefaultChromeCastProgramLoadingTest.java
- catroid/src/main/java/org/catrobat/catroid/common/defaultprojectcreators/ChromeCastProjectCreator.java
- catroid/src/main/java/org/catrobat/catroid/common/defaultprojectcreators/DefaultProjectCreator.java
Junit Test is included "Espresso test is not a good idea since it need Activity-switching 'MainMenuActivity -> ProjectActivity'".
PS: this ticket still in Issue Pool. which I worked on for personal purpose -_-.
> CATROID-85 Error parsing XML while opening an example cast project.

- Jenkinsfile.SensorboxTests
Run the Nexus hardware tests inside a docker container.
> JENKINS-247 Run SensorBox Tests inside docker container

- catroid/src/androidTest/java/org/catrobat/catroid/test/io/DefaultDroneProgramLoadingTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/io/DefaultJumpingSumoProgramLoadingTest.java
- catroid/src/main/java/org/catrobat/catroid/common/defaultprojectcreators/ArDroneProjectCreator.java
- catroid/src/main/java/org/catrobat/catroid/common/defaultprojectcreators/JumpingSumoProjectCreator.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/NewProjectDialogFragment.java
PS: this ticket still in Issue Pool. which I worked on for personal purpose -_-.
> CATROID-86 fix creating AR.Drone / Jumping Sumo projects

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/looks/paintroid/PocketPaintNewLookDiscardIntentTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/looks/paintroid/PocketPaintNewSpriteDiscardIntentTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/looks/paintroid/PocketPaintNewSpriteIntentTest.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/soundrecorder/SoundRecorderActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ImportLaunchers.kt
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
- catroid/src/main/res/values/strings.xml
- fixed issues where files form external applications (files, camera,
pocket paint) were not imported correctly.
- changed default names as specified in ticket.
> CATROID-50 Fix import issues and default names

- catroid/src/lunaAndCat/java/org/catrobat/catroid/common/FlavoredConstants.java
> CATROID-128: Fixed Library Base URL Issue.

- catroid/src/main/java/org/catrobat/catroid/ui/controller/BackpackListManager.java
> CATROID-91: Removed ASync Tasks to the UI Thread.

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SetVariableTest.java
- softkeyboard obstructed the ok button on small screens.
- added viewaction to close the keyboard to new variable workflow.
> TESTS Fixed testIfSetVariableSpinnerCanHoldMultipleVariables()

- catroid/src/androidTest/java/org/catrobat/catroid/test/scratchconverter/ScratchServerCallsTest.java
- catroid/src/main/java/org/catrobat/catroid/transfers/SearchScratchProgramsTask.java
- catroid/src/main/java/org/catrobat/catroid/web/ServerCalls.java
- catroid/src/main/java/org/catrobat/catroid/web/WebconnectionException.java
- test now no longer fails when scratch server does not provide
projectData.
- removed unnecessary code from server calls.
- optimized exception handling for server calls.
> TEST Changed scratch converter server test

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/SettingsFragmentTest.java
- catroid/src/main/res/layout/accessibility_profile.xml
when we click on the radiobutton the onClick of the parent view is not called and so to fix this I made the radio button unclickable.
> CATROID-146 Fix multiple radio button selection in profile settings

- catroid/src/main/res/layout/brick_place_at.xml
- catroid/src/main/res/layout/brick_show_variable.xml
- catroid/src/main/res/values/strings.xml
- catroid/src/main/res/values/styles.xml
- changed project import message.
- escaped special characters.
- removed trailing whitespaces in strings.
- replaced trailing whitespaces with padding.
> STRINGS Changed import messages, escaped quotes, fixed brick strings

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/HighlightBrickPartsTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/dragndrop/BrickListView.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ScriptFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/BrickAdapter.java
- catroid/src/main/res/values/strings.xml
- added option "highlight brick parts" to context menu (second from the top)
- added highlighting of all brick parts of controll structure bricks 
- added small test
> CATROID-22 Highlight brick parts

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/CategoryBricksFactoryTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/ShowTextColorAndSizeBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/common/BrickValues.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/HideTextAction.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/ShowTextColorAndSizeAction.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ShowTextColorAndSizeBrick.java
- catroid/src/main/java/org/catrobat/catroid/stage/ShowTextActor.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/res/layout/brick_show_variable_text_color_and_size.xml
- catroid/src/main/res/values/strings.xml
Add size parameter for Show variable brick. Wrote one TestCase
for new ShowTextColorAndSizeBrick.
> CATROID-23/24 Implemented new ShowTextAndColorBrick and Action.

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorMovementPropertiesTest.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
Test is included.
Bug happens cause stageListener is null if the stage is never started yet.
> CATROID-116 Compute touches_edge crashes in formula editor

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CopySceneTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteAllScenesTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteFirstSceneTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameSceneTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SceneListFragment.java
just reloading the project after renaming the Scene fixed the bug.
> CATROID-144 white stage or crash when playing a renamed Scene

- catroid/src/androidTest/java/org/catrobat/catroid/stage/DrawAxesTest.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
- larger font-size for axes
- distance to display-border larger
- simple test to check axes font size
> CAT-2565 Axes not readable at high res. devices

- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
- this only happend when importing projects that have
language version 0.999. because Xstream was not
prepared correctly.
- now changed the rename method so that it no longer relies
on xstream validation.
> CATROID-187 Fixed issue where renaming legacy projects does not work

- catroid/src/main/java/org/catrobat/catroid/transfers/FacebookLoginHandler.java
- catroid/src/main/java/org/catrobat/catroid/transfers/MediaDownloadService.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/activity/ProjectUploadActivity.java
- catroid/src/main/res/values/strings.xml
Toast message shows the error that session expired and redirects to
signinworkflow. No tests written.
> CATROID-39 bug fix regarding uploading a project after session expired.

- catroid/src/androidTest/java/org/catrobat/catroid/catrobattestrunner/CatrobatTestRunner.java
- tried to load project from wrong directory. fixed this now.
> [TESTING] Fixed issue with CatrobatTestRunner

- catroid/build.gradle
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/BroadcastBrickMessageUpdateTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PointToBrickAdditionalTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SceneBricksTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SetVariableTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/utils/BrickSpinnerDataInteractionWrapper.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/messagecontainer/BroadcastAndWaitBrickMessageContainerTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/messagecontainer/BroadcastMessageBrickUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/messagecontainer/BroadcastSendBrickMessageContainerTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/matchers/BrickSpinnerMatchers.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BrickBaseType.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BroadcastMessageBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/SceneStartBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/SceneTransitionBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenBackgroundChangesBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/brickspinner/BrickSpinner.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/test/java/org/catrobat/catroid/test/roboelectric/BroadcastBrickTest.java
update Robolectric to version 4.2.1, because version 4.2 cause a problem on windows when running the test.
new tests:
* BroadcastBricksTest.java
* PointToBrickAdditionalTest.java
* SceneBricksTest.java
* BroadcastBrickMessageUpdateTest.java
done with help of @84n4n4 , [link](https://github.com/Catrobat/Catroid/compare/fb2a6d9f2dcbd67d6971d24c43b124c09c0e8938..81b558d76d89e496518dfb502e911f346608b932) to his changes, which I copied into this PR
> CATROID-137 Update broadcast messages and scenes after adding new ones from brick

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickCategoryTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/io/devicevariableaccessor/DeviceVariableAccessorCleanRoutineTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/io/devicevariableaccessor/DeviceVariableAccessorNullValueTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/io/devicevariableaccessor/DeviceVariableAccessorParameterizedValueTest.java
- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/WriteVariableOnDeviceAction.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/WriteVariableOnDeviceBrick.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/UserVariable.java
- catroid/src/main/java/org/catrobat/catroid/io/DeviceVariableAccessor.java
- catroid/src/main/java/org/catrobat/catroid/io/XStreamUserVariableConverter.java
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
- catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectLoadTask.java
- catroid/src/main/java/org/catrobat/catroid/transfers/project/ProjectUpload.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/DataListAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SpriteController.java
- catroid/src/main/res/layout/brick_write_variable_on_device.xml
- catroid/src/main/res/values-en-rGB/strings.xml
- catroid/src/test/java/org/catrobat/catroid/test/io/DeviceVariableAccessorExceptionTest.java
- catroid/src/test/java/org/catrobat/catroid/test/transfers/ProjectUploadTest.kt
New Branch because of broken GIT-history.
> CATROID-25 Add WriteVariableOnDeviceBrick

- catroid/build.gradle
- catroid/src/androidTest/java/org/catrobat/catroid/test/io/asynctask/ProjectRenameTaskTest.java
- catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectRenameTask.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/activity/ProjectUploadActivity.java
CATROID-274 Fix for renaming projects in upload dialog
> Hotfix 0.9.61/274 rename upload project

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickPermissionTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/RequiresPermissionTaskTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ForeverBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/IfLogicBeginBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/IfThenLogicBeginBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PhiroIfLogicBeginBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/RepeatBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/RepeatUntilBrick.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageResourceHolder.java
* fixes problems where bricks that require resources are not added to the list.
Closes #3234
> CATROID-270 fix permissionsBug

- catroid/build.gradle
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/ShowTextColorSizeAlignmentBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ShowTextColorSizeAlignmentBrick.java
- catroid/src/main/java/org/catrobat/catroid/ui/UiUtils.java
- catroid/src/main/res/values/arrays.xml
- catroid/src/main/res/values/strings.xml
- catroid/src/main/res/values/styles.xml
- catroid/src/test/java/org/catrobat/catroid/test/roboelectric/BrickSingleFormulaFieldTest.java
* Add colorpicker dependency to all flavors
* Add a custom dialog style for dialogs with title, mirroring the one in pocket paint
* Add tests for basic colorpicker functionality
* Show a selection alertdialog, asking the user if they want to pick a new value in the colorpicker or edit it in the formula editor
> CATROID-249 Colorpicker option for show variable

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickCategoryTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- stitch brick only available to insert for background
> CATROID-147 Stitching should only be possible on background

- Jenkinsfile
- Jenkinsfile.buildMetadata
JENKINS_328 use android28 for buildMetadata as well
> JENKINS-324 use android28 for emulator starts

- catroid/src/androidTest/java/org/catrobat/catroid/test/io/asynctask/ProjectRenameSpecialCharactersTaskTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/io/asynctask/ProjectRenameTaskTest.java
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
> CATROID-264 Fixed rename project with special characters

- catroid/build.gradle
This fixes a crash on Android >= Pie
> BLOCKING: Raise paintroid version to 2.4.1

- catroid/src/androidTest/java/org/catrobat/catroid/test/io/asynctask/ProjectRenameSpecialCharactersTaskTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/io/asynctask/ProjectRenameTaskTest.java
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
Backport of #3293 for hotfix-0.9.63
> BACKPORT/CATROID-264 Fixed rename project with special characters

- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- added arctan2 function in previous commit, this
increases the language version.
> MAINTENENCE Update language version after adding new function

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/MergeProjectDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/RecyclerViewFragment.java
- catroid/src/main/res/values/strings.xml
A dialog to enter the name of a new, merged project.
> CATROID-159 Add dialog to enter name of new, merged project

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PhiroColorBrickFormulaTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PhiroColorBrickNumberTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PlaceAtBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SetPenColorBrickFormulaTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SetPenColorBrickNumberTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/FormulaBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/GoNStepsBackBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/MoveNStepsBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PhiroRGBLightBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PlaceAtBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/RepeatBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/SetPenColorBrick.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/Formula.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
- catroid/src/test/java/org/catrobat/catroid/test/formulaeditor/FormulaTest.java
- created new function (isElementANumber) in FormulaElement - works for positive and negative numbers and is used in PhiroRGBLightBrick.java and SetPenColorBrick.java
- updated tests SetPenColorBrickTest and PhiroColorBrickTest
> CATROID-349/ CATROID-210 Fix negative number in brickfield is number / Only show place at for numbers

- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/test/java/org/catrobat/catroid/test/content/project/LoadProjectsTest.java
- add function to check if Version is valid
- remove all "if" which only update language version to the next
- keep those which do other things
- set to current language version in the end
> CATROID-347 Refactor languageVersion check

- catroid/gradle/standalone_apk_tasks.gradle
- catroid/src/androidTest/java/org/catrobat/catroid/test/io/XstreamSerializerTest.java
- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
- catroid/src/test/java/org/catrobat/catroid/test/content/project/LoadProjectsTest.java
- remove Function in standalone gradle which removes values from permission file
- change Test in XstreamSerializerTest which uses the file
- add function in ProjectManager to remove Permissionfile if upgraded to higher language version
- add new if in language Version check
- increase language Version
- remove creation of permissionFile in XstreamSerializer
> CATROID-308 remove permissions.txt

- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenBackgroundChangesBrick.java
- catroid/src/main/java/org/catrobat/catroid/physics/content/bricks/WhenBounceOffBrick.java
- catroid/src/test/java/org/catrobat/catroid/test/content/script/ScriptsBrickDragNDropListTest.java
- change WhenBackgroundChangesBrick from BasicBrickType to ScriptBrickBaseType
- add Testcase for the error
> CATROID-345 whenBackGroundChanges crash fix

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/visualplacement/SpriteActivityVisualPlacementTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/visualplacement/VisualPlacementActivityTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/PlaceAtBrick.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/visualplacement/VisualPlacementActivity.java
- evaluating and add parameters for intent
- transform imageview for positioning
- set coord at start to avoid different case handling for no changes
- add espressotest for VisualPlacement
> CATROID-312 use last know position in visual placement

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/ProjectUploadRatingDialogTest.java
- catroid/src/debug/AndroidManifest.xml
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectUploadActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/controller/ProjectUploadController.java
* Relocate rating-dialog to onReceiveResult
> CATROID-174 Ask for rating after successful upload

- Jenkinsfile
- catroid/build.gradle
* fixed response code in testLoginWithNotExistingUser 803 instead of 764
> JENKINS increased jvm heap to overcome memory leakage in JVM tests

- catroid/src/main/java/org/catrobat/catroid/content/Scene.java
- catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickBroadcastMessageTest.java
- catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickWithSecondaryListBroadcastMessageTest.java
- change iteration through bricks
- add testcase for nested and nested with secondary list
> CATROID-360 fix broadcast messages lost in compound bricks

- docker/Dockerfile.jenkins
> add packages to dockerfile

- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/Formula.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/DataListFragment.java
- catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickVariableUpdateTest.java
- catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickWithSecondaryListUpdateTest.java
- catroid/src/test/java/org/catrobat/catroid/test/content/bricks/UpdateVariableInFormulaBrickTest.java
- catroid/src/test/java/org/catrobat/catroid/test/content/bricks/UpdateVariableInFormulaScriptBrickTest.java
- add function to update all references to this variable in current project
- add testcase to test all formulabricks
> CATROID-258 Change names in formula fields if variable name changes

- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormulaState.java
- catroid/src/test/java/org/catrobat/catroid/test/formulaeditor/InterFormulaStateUserDataUpdateTest.java
- add function to update uservariable and userlist in InternFormulaState
- call function in FormulaEditorEditText
- add testcase for function
> CATROID-378 fix Formulaeditor crashes after variable/list rename and discard

- catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
- catroid/src/test/java/org/catrobat/catroid/test/content/sprite/SpriteTest.java
"Show Details" now shows the correct number of bricks
> CATROID-359 fix brick count

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/AddUserbrickTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddBrickFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserBrickFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
- catroid/src/main/res/layout/fragment_brick_add_userbrick.xml
- catroid/src/main/res/values-de/strings.xml
- catroid/src/main/res/values-en-rAU/strings.xml
- catroid/src/main/res/values-en-rCA/strings.xml
- catroid/src/main/res/values-en-rGB/strings.xml
- catroid/src/main/res/values/strings.xml
* Add fragment_brick_add_userbrick.xml
* Add query to distinguish userbricks and others for loading the specific xmls
* Add UI Test
* Rename "My bricks" to "Your bricks"
> CATROID-212 + CATROID-391 Add list view for User Bricks

- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
* Move switch between uris into code
* Revert change to `/program/` infix until web has released their new version
> CATROID-399: Fix project infix for share

- catroid/src/main/java/org/catrobat/catroid/content/bricks/PlaySoundAndWaitBrick.java
fixed issue where deleting sound used by PlaySoundAndWaitBrick caused an IllegalArgumentException.
> CATROID-418 Handle user deleting sound file used by PlaySoundAndWaitBrick

- catroid/src/main/java/org/catrobat/catroid/visualplacement/VisualPlacementTouchListener.java
- catroid/src/test/java/org/catrobat/catroid/test/visualplacement/VisualPlacementPositionCorrectionTest.java
- add variables for the last 2 event timestamps
- add variable for the last 2 positions
- check the last 2 movement events ins ACTION_UP
- add testcase
> CATROID-311 Visual Placement position correction

- catroid/src/main/java/org/catrobat/catroid/transfers/LoginTask.java
- catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/SignInActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
- added Utils function to also print error message
- call this method instead of the old one
- add function call to catrobat community and media library
> CATROID-363 no Internet error messages and refactoring

- catroid/src/androidTest/java/org/catrobat/catroid/common/bluetooth/BluetoothTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/common/bluetooth/ConnectionDataLogger.java
- catroid/src/main/java/org/catrobat/catroid/bluetooth/ConnectBluetoothDeviceActivity.java
- add request for location permission in onCreate of Activity
- add ScanCallbackMethod which adds dive to adapter
- add BLE Scan to DoDiscoveryMethod
- call classic discovery after BLE Scan and when there are no permissions
> CATROID-367 Find BLE devices

- catroid/src/androidTest/java/org/catrobat/catroid/test/io/asynctask/ProjectExportTaskTest.java
- catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectExportTask.java
- catroid/src/main/java/org/catrobat/catroid/transfers/project/ProjectDownloadService.kt
- catroid/src/main/java/org/catrobat/catroid/transfers/project/ProjectUploadService.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
- catroid/src/main/java/org/catrobat/catroid/utils/notifications/NotificationData.kt
- catroid/src/main/java/org/catrobat/catroid/utils/notifications/StatusBarNotificationManager.java
- catroid/src/main/java/org/catrobat/catroid/web/ProjectDownloader.kt
+ refactor NotificationManager
> CATROID-428 fix open project with download notification bug

- catroid/src/androidTest/java/org/catrobat/catroid/test/common/LookDataTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/physics/collision/CollisionDetectionAdvancedTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/physics/collision/CollisionDetectionPolygonCreationTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/physics/collision/CollisionTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/sensing/CollisionInformationBubblePositionTest.java
- catroid/src/main/java/org/catrobat/catroid/content/Look.java
- catroid/src/main/java/org/catrobat/catroid/sensing/CollisionInformation.java
- catroid/src/main/java/org/catrobat/catroid/sensing/CollisionPolygonCreationTask.java
- catroid/src/main/java/org/catrobat/catroid/sensing/GatherCollisionInformationTask.java
- catroid/src/main/java/org/catrobat/catroid/stage/ShowBubbleActor.java
- catroid/src/main/java/org/catrobat/catroid/utils/ImageEditing.java
- catroid/src/test/java/org/catrobat/catroid/test/stage/ShowBubbleActorTest.java
* Correct position of say/think bubble
* Add function to check if a pixel is transparent
* Add tests
Co-Authored-By: geschob <geschob@users.noreply.github.com>
> CATROID-173 Correct Position of Say and Think Bubble

- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
- catroid/src/main/java/org/catrobat/catroid/web/Cookie.java
- catroid/src/test/java/org/catrobat/catroid/test/transfers/WebViewActivityLoginCookieTest.java
Added a JUnit4 test and made a small refactoring.
> CATROID-374 add WebViewActivityLoginCookieTest

- catroid/src/main/res/values/strings.xml
CATROID-467 Correct English Capiatlisation
Fix Bug CATROID-467
**BEFORE**
**AFTER**
> CATROID-467 Fixed Correct English  Capitalisation

- Jenkinsfile
- Jenkinsfile.baseDocker
JENKINS-366 actually push images
JENKINS-365 use image for build
JENKINS-365 set default label to stable and add parameter to overwrite for debug reasons
JENKINS-365 always pull docker images
JENKINS-365 add build trigger for midnight develop
> JENKINS-365 add jenkinsfile to build and push docker image

- catroid/src/androidTest/java/org/catrobat/catroid/test/BricksHelpUrlTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickCategoryTest.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/ClearUserListAction.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ClearUserListBrick.java
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/res/layout/brick_clear_userlist.xml
- catroid/src/main/res/values/strings.xml
- catroid/src/test/java/org/catrobat/catroid/test/content/actions/ClearUserListActionTest.java
> CATROID-389 Introduce <Delete all items from list> brick

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/SceneTransitionWithSoundBrickStageTest.java
- catroid/src/main/java/org/catrobat/catroid/io/SoundManager.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
- added test for correct behavior of sound on scene transition
> CATROID-169 Sound continues on scene continue transition

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/AddUserListToActiveFormulaUITest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorFunctionListTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/UserListBrick.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormula.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/CategoryListRVAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/DataListFragment.java
- catroid/src/main/java/org/catrobat/catroid/utils/AddUserListDialog.java
- catroid/src/test/java/org/catrobat/catroid/test/content/actions/AddUserListToActiveFormulaTest.java
- Refactor/Move tests out of FormulaEditorFunctionListTest
- Add UI espresso test to check if the last user list is inserted correctly.
- Add Unit test to check if Dialog pops up when there is no current user list.
https://jira.catrob.at/browse/CATROID-404
> CATROID-404 Insert existing user list as parameter of list functions

- catroid/src/androidTest/java/org/catrobat/catroid/test/stage/ScreenshotSaverTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/AskBrickStageTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/SceneTransitionWithVibrationBrickStageTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/facedetection/FaceDetectionResourceStartedTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/stage/StagePausedTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/stage/StageScreenshotTest.java
Look in failing PR's for flaky Tests. Most of them have timing issues => flaky.
> CATROID-530 fix bug in stage tests

- Jenkinsfile
Change the number of builds to keep to use less disk space on Jenkins see https://jira.catrob.at/browse/JENKINS-377
> JENKINS-377 change number of builds to keep

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/stage/StagePausedTest.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageLifeCycleController.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
Fixed possible null-pointer-exception occurrences,
Minor refactoring of Stage.
> CATROID-550 Fix Stage-Touch-Events not ignored while Stage paused bug

- Jenkinsfile.BuildStandalone
- Jenkinsfile.ManualTests
- Jenkinsfile.OutgoingNetworkCallsTests
- Jenkinsfile.SensorboxTests
- Jenkinsfile.buildMetadata
- Jenkinsfile.releaseAPK
> JENKINS-372 use docker catrobat image in all Jenkinsfiles

- catroid/src/main/res/values/attrs.xml
- catroid/src/main/res/values/styles.xml
- catroid/src/main/res/values/styles_accessibility.xml
**Description:**
Renamed category_icon_visiblity to category_icon_visibility.
> Fix typo in attr.xml, styles.xml and styles_accessibility.xml

- catroid/src/main/java/org/catrobat/catroid/facedetection/IcsFaceDetector.java
- catroid/src/main/java/org/catrobat/catroid/facedetection/SlowFaceDetector.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
**Description:**
Replaced manual min max calculation with Math.min and Math.max.
> Replaced manual min max calculation with Math.min and Math.max.

- README.md
Updated grammatical mistake in line 12 in readme.
Updated grammatical mistake in line 12 in readme.
> Update in Readme

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/AddUserDefinedBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/UserDefinedBrick.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserBrickFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDataToUserBrickFragment.java
- catroid/src/main/java/org/catrobat/catroid/userbrick/UserBrickLabel.java
- catroid/src/main/res/layout/fragment_add_user_data_to_user_brick.xml
- catroid/src/main/res/values/strings.xml
- catroid/src/main/res/values/styles.xml
- Feature of adding labels to a UserDefinedBrick
- Updating UserDefinedBrick Files and Tests of UserDefinedBricks.
https://jira.catrob.at/browse/CATROID-215
> CATROID-215 Add a label to "Your bricks"

- catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
> CATROID-578 fix Visual Placement Distorts Bug

- catroid/src/test/java/org/catrobat/catroid/test/utiltests/StringFinderTest.java
- as discussed, PO suggested it could be missunderstood as sarcasm/criticism
this corrects it to the original quote so it is clearer.
> MAINTENANCE Changed controversial test string

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/ProjectActivityTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/ProjectUploadRatingDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectUploadActivity.java
-  based on the work of @Pratik1999
- saves changes to new projects after its upload.
https://jira.catrob.at/browse/CATROID-504
This PR is basically just a rebase and squash with minor fixes of PR https://github.com/Catrobat/Catroid/pull/3556 which was based on https://github.com/Catrobat/Catroid/pull/3553 since a hotfix would be necessary to be released as soon as possible.
> CATROID-504 Project is not saved

- catroid/src/androidTest/java/org/catrobat/catroid/test/io/devicevariableaccessor/DeviceVariableAccessorCleanRoutineTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/VariableBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/utils/BrickVariableSpinnerDataInteractionWrapper.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorVariableScopeTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/FormulaEditorDataListWrapper.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/content/Project.java
- catroid/src/main/java/org/catrobat/catroid/content/backwardcompatibility/ProjectUntilLanguageVersion0999.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/UserVariableBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/UserVariableBrickWithFormula.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/brickspinner/UserVariableBrickTextInputDialogBuilder.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/UserDataWrapper.java
- catroid/src/main/java/org/catrobat/catroid/io/DeviceVariableAccessor.java
- catroid/src/main/java/org/catrobat/catroid/stage/ShowTextActor.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/DataListAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/DataListFragment.java
- catroid/src/main/res/values/strings.xml
- catroid/src/test/java/org/catrobat/catroid/test/formulaeditor/FormulaEditorDataListAdapterArraysValueTest.java
[CATROID-543](https://jira.catrob.at/browse/CATROID-543)
The second step in adding multiplayer functionality to Pocket Code.
- Add multiplayer variables list in Project
- Add category for multiplayer variables in Data list
- Use multiplayer variables in addition to regular ones where needed
> CATROID-543 Store and display multiplayer variables

- Jenkinsfile.BuildStandalone
> Fix Jenkinsfile.BuildStandalone

- catroid/build.gradle
**Caution: Do not merge until [PAINTROID-130](https://github.com/Catrobat/Paintroid/pull/741) is approved**
This PR relates to [this ticket](https://jira.catrob.at/browse/PAINTROID-130) from Paintroid.
It will allow Paintroid to build it's pull requests with the develop branch of Catroid which will make testing a lot easier.
The intention of this PR is that if `paintroidLocal` is provided, catroid should use the paintroid package located in the local maven repository and not from jcenter.
> MAINTENANCE Paintroid PR can build with Catroid on Jenkins

- catroid/src/androidTest/java/org/catrobat/catroid/test/BricksHelpUrlTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/StopSoundActionTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickCategoryTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/utils/TestUtils.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/StopSoundAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/bricks/StopSoundBrick.kt
- catroid/src/main/java/org/catrobat/catroid/io/SoundManager.java
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/res/layout/brick_stop_sound.xml
- catroid/src/main/res/values/strings.xml
Adds new brick to stop a specific sound.
https://jira.catrob.at/browse/CATROID-575
> CATROID-575 Stop sound __ brick

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/AddBrickFloatingBehaviorTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
https://jira.catrob.at/browse/CATROID-597
> CATROID-597 Fix incorrect floating behavior of second added script brick

- catroid/build.gradle
> MAINTENANCE: Upgrade Paintroid and colorpicker to 2.5.0

- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/io/BackwardCompatibleCatrobatLanguageXStream.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/MainMenuFragment.java
> Hotfix 0.9.71

- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/io/BackpackBrickSerializerAndDeserializer.java
- catroid/src/main/java/org/catrobat/catroid/io/BackpackSerializer.java
- catroid/src/main/java/org/catrobat/catroid/io/BackwardCompatibleCatrobatLanguageXStream.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/MainMenuFragment.java
> Hotfix 0.9.72

- catroid/build.gradle
> [HOTFIX] Increased version code and number for testing purpose

- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/io/BackpackSerializer.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/MainMenuFragment.java
- Fix NPE in load Backpack --> Runtime Exception in JSON parsing
- Fix NPE in Project Upload --> Current project not set on start
> Hotfix 0.9.73

- README.md
Applied changes from Wolfgang from https://github.com/Catrobat/Catblocks/pull/157/files/d4a29b9e16087700e608dd250454f59924f4ee52
https://jira.catrob.at/browse/CATROID-642
> CATROID-642 change readme.md

- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/camera/FaceDetector.kt
Corrects face position calculation, especially for landscape mode.
> Fix face position calculation

- catroid/src/main/java/org/catrobat/catroid/camera/FaceDetector.kt
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
> Get face detection image dimensions dynamically

- catroid/src/androidTest/java/org/catrobat/catroid/test/BricksHelpUrlTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickCategoryTest.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/FinishStageAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ExitStageBrick.java
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteAttributesActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/res/layout/brick_exit_stage.xml
- catroid/src/main/res/values/strings.xml
change text of FinishStageBrick
enable execution of tests in all activities
> CATROID-622 new ExitStageBrick

- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickCategoryFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/settingsfragments/SettingsFragment.java
- catroid/src/main/res/values/strings.xml
- catroid/src/main/res/xml/preferences.xml
add additional Settings Checkbox - "Testing Extension"
https://jira.catrob.at/browse/CATROID-611
> CATROID-611 unlock Testing Category for Release

- catroid/src/main/java/org/catrobat/catroid/camera/CameraManager.kt
- catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
Only makes stage transparent when camera preview is shown.
> CATROID-657 Transparent parts of thumbnail preview images should be white

- catroid/src/main/java/org/catrobat/catroid/camera/FaceDetector.kt
> Inverted face position on older Android builds

- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
https://jira.catrob.at/browse/CATROID-665
> CATROID-665 Uploading project from longclick menu crashes

- catroid/build.gradle
Release Preparation PR:
- Increased version code and number
> Release 0.9.74

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/UserDefinedBrickTest.java
- catroid/src/main/res/layout/fragment_user_defined_brick_list.xml
- catroid/src/main/res/values/strings.xml
Added description mentioned above if the UserDefinedBrickList of the current sprite is empty. Added a test for functionality of the code.
https://jira.catrob.at/browse/CATROID-219
> CATROID-219 Add hint: Tap "+" to add your own new bricks

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CurrentProjectTest.java
- Added test that checks if current project is set correctly after a new project is added (like when downloading)
https://jira.catrob.at/browse/CATROID-640
> CATROID-640 Write tests for current project on landing page

- catroid/src/embroideryDesigner/res/values/colors.xml
- catroid/src/lunaAndCat/res/values/colors.xml
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/MainMenuFragment.java
- catroid/src/main/res/drawable/ic_done.xml
- catroid/src/main/res/drawable/ic_more_vert.xml
- catroid/src/main/res/layout/landing_page.xml
- catroid/src/main/res/values/colors.xml
- catroid/src/main/res/values/styles.xml
> CATROID-686 Revert landing page and toolbar to old color scheme

- catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/MainMenuFragment.java
- catroid/src/main/java/org/catrobat/catroid/utils/ProjectDownloadUtil.kt
- catroid/src/main/java/org/catrobat/catroid/web/ProjectDownloader.kt
- catroid/src/test/java/org/catrobat/catroid/test/web/DownloadCallBackTest.java
> CATROID-641 Refresh landing page after download is finished

- catroid/src/androidTest/java/org/catrobat/catroid/test/BricksHelpUrlTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BrickBaseType.java
https://jira.catrob.at/browse/CATROID-689
> CATROID-689 adjust documentation links

- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
CATROID-679 Add "Help" option in context menu for "Define" brick: https://jira.catrob.at/browse/CATROID-679
> CATROID-679 Add "Help" option in context menu for "Define" brick

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/UserDefinedBrickTest.java
> Reduce Flaky tests in UserdefinedBrickTest.java

- catroid/src/main/res/layout/landing_page.xml
https://jira.catrob.at/browse/CATROID-704
> CATROID-704 Make landing page icons more visible on white backgrounds

- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/ProjectListener.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/HorizontalProjectsAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/MainMenuFragment.java
- catroid/src/main/res/drawable/ic_arrow_forward_vector.xml
- catroid/src/main/res/layout/landing_page.xml
- catroid/src/main/res/layout/project_picture_listitem.xml
- catroid/src/test/java/org/catrobat/catroid/test/web/DownloadCallBackTest.java
https://jira.catrob.at/browse/CATROID-618
- Added a horizontal recyclerview to show the last 10 recently used projects
- Implemented scrolling to support smaller phones
> CATROID-618 Show the last accessed projects on the landing page

- docker/Dockerfile.jenkins
https://jira.catrob.at/browse/DEVOPS-412
Catroid image should use a debian preferably 9 because of openjdk 8 support.
More comfortable to debug and can be replicated easier.
Should fix segfault in JVM and maybe fastlane errors.
> updated dockerfile

- catroid/src/main/res/values/strings.xml
Reverts Catrobat/Catroid#3555 --- broke unit tests (sorry!)
> Revert "CATROID-435. Changing 'Looks' => 'Look'"

- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/camera/CameraManager.kt
- catroid/src/main/java/org/catrobat/catroid/camera/PreviewView.kt
- catroid/src/main/java/org/catrobat/catroid/stage/StageLifeCycleController.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
> CATROID-683 Transparency is not handled correctly for screenshots

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CategoryListFragmentTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java
- catroid/src/main/java/org/catrobat/catroid/web/WebpageUtils.java
https://jira.catrob.at/browse/CATROID-709
The regex assistant button opens https://catrob.at/regex on click.
> CATROID-709 Link wiki page

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/VisualPlacementBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/VisualPlacementBrick.java
https://jira.catrob.at/browse/CATROID-696
> CATROID-696 Fix behavior of visual placement dialog

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorRegexDetectionTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
https://jira.catrob.at/browse/CATROID-715
Assistant button on change regular expression dialog opens now assistant dialog
> Catroid 715 assistant dialog on abc

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/HtmlExtractorDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/HtmlExtractorDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/HtmlExtractorInputDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/RegularExpressionAssistantDialog.java
- catroid/src/main/res/layout/dialog_regex_html_extractor.xml
- catroid/src/main/res/values/strings.xml
CATROID-718 Add Html extractor dialog
https://jira.catrob.at/browse/CATROID-718
-add html extractor dialog to RegEx feature list
-add UI tests
> CATROID-718 Add Html extractor dialog

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/HtmlExtractorDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/HtmlExtractorDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/HtmlExtractorInputDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/RegularExpressionAssistantDialog.java
- catroid/src/main/java/org/catrobat/catroid/utils/HtmlRegexExtractor.java
- catroid/src/main/res/layout/dialog_regex_html_extractor.xml
- catroid/src/main/res/values/strings.xml
CATROID-719 HTML extract (0) - message not successful (depends on @CATROID-718)
- Implement message, if search was not successful TASKS ENDS HERE!
- After Button press, print a message that the search was not successful
- Input: keyword/string, html text
- mock of text is not found, outputted that search is not successful
https://jira.catrob.at/browse/CATROID-719
> CATROID-719 HTML extract (0) - message not successful

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/HtmlExtractorDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/HtmlExtractorDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/HtmlExtractorInputDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/RegularExpressionAssistantDialog.java
- catroid/src/main/java/org/catrobat/catroid/utils/HtmlRegexExtractor.java
- catroid/src/main/res/layout/dialog_regex_html_extractor.xml
- catroid/src/main/res/values/strings.xml
CATROID-720 html extract (0) - message search successful (depends on CATROID-718 & 719)
- Implement message: search was successful
- combination of inputs, search and message (more advanced than 4.3 https://docs.google.com/spreadsheets/d/1FZwBT0FTstHb8z2mKENRsDUCoJRlxuvyouHUazDaZMI/edit#gid=0)
- finds text in html text, confirms if found
https://jira.catrob.at/browse/CATROID-720
> CATROID-720 html extract (0) - message search successful

- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectUtils.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/res/values/strings-global.xml
- catroid/src/main/res/values/strings.xml
> CATROID-681: Show warning for downloaded project that contains Start listening to voice and Web access bricks

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/actionbar/ActionBarUndoSpinnerTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/brickspinner/BrickSpinner.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
- catroid/src/main/res/menu/menu_script_activity.xml
https://jira.catrob.at/browse/CATROID-20
> CATROID-20 Enable undo of spinner manipulation

- catroid/src/main/res/layout/list_action_buttons.xml
https://jira.catrob.at/browse/CATROID-774
> CATROID-774 Action buttons not working on Android 5

- Jenkinsfile
- docker/Dockerfile.jenkins
> Added Fastlane

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/RegularExpressionAssistantDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/RegularExpressionAssistantDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/WikiWebPage.java
- catroid/src/main/res/values/strings.xml
-add wiki button in assistant window
-add Ui tests
https://jira.catrob.at/browse/CATROID-713
> CATROID-713 - Link to Wiki in assistant window

- catroid/build.gradle
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/RegularExpressionAssistantDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/RegularExpressionAssistantDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/WikiWebPage.java
- catroid/src/main/res/values/strings.xml
depends on #3794 
-add feature flag in build.gradle
-add condition for RegEx assistant functionalities via feature flag
https://jira.catrob.at/browse/CATROID-752
> Catroid-752 - Feature flag as condition for RegEx assistant functionalities

- catroid/src/androidTest/java/org/catrobat/catroid/test/BricksHelpUrlTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/BrickBaseType.java
on the new wiki the documentation is now found at
...Documentation\BrickDocumentation\... instead of
...Documentation\Brick%20Documentation\...
> CATROID adjust link to Documentation

- .idea/codeStyles/Project.xml
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/JsonExtractorDialogTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/RegularExpressionAssistantDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/JsonExtractorDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/RegularExpressionAssistantDialog.java
- catroid/src/main/res/layout/dialog_regex_json_extractor.xml
- catroid/src/main/res/values/strings.xml
Catroid-754: https://jira.catrob.at/browse/CATROID-754
- JsonExtractorDialog.java: ADD of new class for JSON extractor
- strings.xml: ADD of new string for JSON extractor
- dialog_regex_json_extractor.xml: ADD of new layout for JSON extractor
> Catroid 754 JSON Extractor Dialog

- catroid/src/main/java/org/catrobat/catroid/utils/HtmlRegexExtractor.java
- catroid/src/test/java/org/catrobat/catroid/test/ui/regexassistant/HtmlRegexExtractorTest.java
https://jira.catrob.at/browse/CATROID-721
-ADD Space replacement to wildcard
-ADD Unit-Test
> CATROID-721 Extended Keyword search

- catroid/src/main/java/org/catrobat/catroid/utils/HtmlRegexExtractor.java
- catroid/src/test/java/org/catrobat/catroid/test/ui/regexassistant/HtmlRegexExtractorTest.java
depends on #3797 
-add regex creating abilities / functionalities
-add unit tests
https://jira.catrob.at/browse/CATROID-762
> Catroid-762 Add regular expression assistant  regex creating functionalities 

- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/BrickAdapter.java
https://jira.catrob.at/browse/CATROID-784
> CATROID-784 Checkboxes in scriptsView do not appear when actionmode is used

- catroid/src/androidTest/java/org/catrobat/catroid/test/ProjectManagerTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/scratchconverter/WebSocketClientTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/scratchconverter/protocol/WebSocketMessageListenerTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/utils/TestUtils.java
- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/common/ProjectData.java
- catroid/src/main/java/org/catrobat/catroid/content/Project.java
- catroid/src/main/java/org/catrobat/catroid/content/XmlHeader.java
- catroid/src/main/java/org/catrobat/catroid/content/backwardcompatibility/ProjectMetaDataParser.java
- catroid/src/main/java/org/catrobat/catroid/scratchconverter/Client.java
- catroid/src/main/java/org/catrobat/catroid/scratchconverter/ScratchConversionManager.java
- catroid/src/main/java/org/catrobat/catroid/scratchconverter/protocol/message/base/BaseMessage.java
- catroid/src/main/java/org/catrobat/catroid/scratchconverter/protocol/message/base/InfoMessage.java
- catroid/src/test/java/org/catrobat/catroid/test/content/project/LoadProjectsTest.java
- catroid/src/test/java/org/catrobat/catroid/test/content/project/ProjectTest.java
https://jira.catrob.at/browse/CATROID-707
> CATROID-707 change catrobatLanguageVersion from float to double

- catroid/src/main/java/org/catrobat/catroid/camera/PreviewView.kt
Implements scaling of camera image for older Android versions
> Catroid-735 Fix vertical distortion of camera image on Android 5 and 6 devices

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/HtmlExtractorDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormula.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/HtmlExtractorDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/RegularExpressionAssistantDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java
- catroid/src/main/java/org/catrobat/catroid/utils/HtmlRegexExtractor.java
- catroid/src/main/res/values/strings.xml
- catroid/src/test/java/org/catrobat/catroid/test/formulaeditor/InternFormulaRegexAssistantTest.java
- catroid/src/test/java/org/catrobat/catroid/test/ui/regexassistant/HtmlRegexExtractorTest.java
https://jira.catrob.at/browse/CATROID-764
CATROID-764 - Assistant - Smart assistant button in function list (Id: 1.3.1.1)
-add Unit-Tests
-add functionality to check if selection is in part of regular expression function
-add functionality to select correct parameter on assistant button click
-change behavior of assistant button in function list when to add regular expression
> Catroid-764 - Assistant - Smart assistant button in function list (Id: 1.3.1.1)

- catroid/src/main/java/org/catrobat/catroid/stage/StageResourceHolder.java
- catroid/src/main/java/org/catrobat/catroid/utils/VibrationUtil.java
Commit 1: Quick-fix unnecessary vibration
Commit 2: Refactor some parts of VibrationUtil (For a general overhaul, I will create a separate ticket)
> CATROID-279 Fix unnecessary vibration

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/rtl/RtlBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/brickspinner/BrickSpinner.java
https://jira.catrob.at/browse/CATROID-787
> CATROID-787 Fix RTLBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/ProjectUploadRatingDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/content/Project.java
- catroid/src/main/java/org/catrobat/catroid/content/XmlHeader.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectUploadActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/controller/ProjectUploadController.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectDetailsFragment.java
- catroid/src/main/res/layout/activity_upload.xml
- catroid/src/main/res/layout/fragment_project_show_details.xml
- catroid/src/main/res/values/strings.xml
https://jira.catrob.at/browse/CATROID-386
Edit and view notes and credits in "Show details" screen
Add notes and credits section when uploading
> CATROID-386 Add notes and credits section

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/HtmlExtractorDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/utils/HtmlRegexExtractor.java
- catroid/src/test/java/org/catrobat/catroid/test/ui/regexassistant/HtmlRegexExtractorTest.java
https://jira.catrob.at/browse/CATROID-793
Fixes inefficiencies that made the html assistant exponentially slow for common scenarios
Removal of spurious comment
Added visibility for testing annotation
Added a real life example from timeanddate.com
Escapes the html code in the regex
> CATROID-793 Fix ANR of regex HTML assistant

- build.gradle
- catroid/build.gradle
- catroid/src/main/res/values/styles.xml
> CATROID-797: Android Material Components

- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/ProjectListener.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/HorizontalProjectsAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/MainMenuFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectsViewModel.kt
> CATROID-727 Refactoring of landing page

- catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenNfcBrick.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteAttributesActivity.java
- catroid/src/main/res/values-de/strings.xml
- catroid/src/main/res/values/strings.xml
- catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickSpinnerTest.java
Remove the NFC button from the code/looks/sounds menu in the sprite and move it into the brick spinner
https://jira.catrob.at/browse/CATROID-749
> CATROID-749 Relocate NFC tag list to brick spinner

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/VisualPlacementBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/VisualPlacementConditionTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/visualplacement/SpriteActivityVisualPlacementTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ShowTextBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ShowTextColorSizeAlignmentBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/UserVariableBrickWithVisualPlacement.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/VisualPlacementBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/brickspinner/BrickSpinner.java
- catroid/src/main/java/org/catrobat/catroid/stage/ShowTextActor.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
- catroid/src/main/java/org/catrobat/catroid/utils/ShowTextUtils.java
- catroid/src/main/java/org/catrobat/catroid/visualplacement/VisualPlacementActivity.java
- Refactor VisualPlacementActivity (split complicated onCreate() method into multiple methods)
- Convert text to bitmap in order to handle it as ImageView
- Create Utils class for displaying texts - otherwise it would have been necessary to call stage methods from UI context
Further notes:
- If no variable (new...) is selected in the spinner of the ShowVariable brick the visual placement option is not visible. (as this is not further specified in the ticket)
- Always the values of the variables from the last run are shown, as it is already the case for many other fields
https://jira.catrob.at/browse/CATROID-183
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this …
> CATROID-183 Add visual placement to ShowVariable bricks

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/VisualPlacementBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/visualplacement/VisualPlacementActivityTest.java
- catroid/src/main/java/org/catrobat/catroid/visualplacement/VisualPlacementActivity.java
- catroid/src/main/res/values/strings.xml
Changed the dialog options of visual placement from [No] [Yes] to [Cancel] [Save],
> CATROID-741 Change dialog options of visual placement

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RemoveTabsTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/tabs/SpriteActivityTabsTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/tabs/TabLayoutActionModeTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivityOnTabSelectedListener.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickCategoryFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
Remove TabLayout while in ActionMode (+ test).
Move adding and removing of the TabLayout in onAttach an onDetach
> CATROID-750 fix TabLayoutBug

- catroid/src/main/res/layout/fragment_user_defined_brick_list.xml
- catroid/src/main/res/layout/landing_page.xml
- catroid/src/main/res/layout/list_action_buttons.xml
- catroid/src/main/res/values/colors.xml
https://jira.catrob.at/browse/CATROID-819
> CATROID-819 Change action button color

- catroid/src/androidTest/java/org/catrobat/catroid/test/BricksHelpUrlTest.java
> Maintenance test fix

- catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
https://jira.catrob.at/browse/CATROID-822
Show landing page below the initial Terms of Use and Service dialog
> CATROID-822 Missing landing page below initial ToUaS dialog

- docker/Dockerfile.jenkins
- [] Include reasonable and readable tests verifying the added or changed behavior
- [] After the PR, verify that all CI checks have passed
> DEVOPS-456 jenkins catrobat build fail, docker image (ruby) fault

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/AddBrickFloatingBehaviorTest.java
https://jira.catrob.at/browse/CATROID-845
> CATROID-845 fix brick floating behavior test

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/tabs/SpriteActivityTabsTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivityOnTabSelectedListener.kt
> CATROID-846 fix TabLayout

- catroid/build.gradle
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PhiroColorBrickNumberTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SetPenColorBrickNumberTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/ShowTextColorSizeAlignmentBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/content/strategy/ShowColorPickerFormulaEditorStrategy.java
- catroid/src/main/java/org/catrobat/catroid/utils/ProjectManagerExtensions.kt
- catroid/src/main/java/org/catrobat/catroid/visualplacement/VisualPlacementActivity.java
- catroid/src/main/res/values/colors.xml
- catroid/src/main/res/values/styles.xml
* upgrade Paintroid and ColorPicker to 2.5.3
* fix some styles
> CATROID-795: Integrate color pipette

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/OpenUrlBrickTest.java
Ticket: https://jira.catrob.at/browse/CATROID-858
Fix Timeout error in OpenUrlBrickTest
> CATROID-858 Fix Timeout error in OpenUrlBrickTest

- catroid/src/androidTest/java/org/catrobat/catroid/test/BricksHelpUrlTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickCategoryTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/rtl/RtlBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/EditLookAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/PaintNewLookAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/PocketPaintAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/bricks/EditLookBrick.kt
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/res/layout/brick_edit_look.xml
- catroid/src/main/res/values/strings.xml
- catroid/src/test/java/org/catrobat/catroid/test/content/actions/EditLookActionTest.kt
The brick opens Pocket Paint and enables the user to edit the look
https://jira.catrob.at/browse/CATROID-756
> CATROID-756 Edit look brick

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/AboutDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/AboutDialogFragment.java
- catroid/src/main/res/layout/dialog_about.xml
- catroid/src/main/res/values/strings.xml
**### Description**
made changes in dialog_about.xml to the add text view
and set the value for the same in AboutDialogFragment.java for showing "catrobat language version".
**Jira Ticket Reference** : https://jira.catrob.at/browse/CATROID-828
Attached the screenshot for the same.
> CATROID-828 - Show supported Catrobat language version number in About

- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/DataListAdapter.java
https://jira.catrob.at/browse/CATROID-843
> CATROID-856 fix FormulaEditor crashes after selecting global variable

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SetVariableBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorKeyboardTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/FormulaEditorWrapper.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormulaKeyboardAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroid/src/main/res/drawable/formula_editor_toggle_functions_button.xml
- catroid/src/main/res/drawable/ic_keyboard_toggle_caret_down.xml
- catroid/src/main/res/drawable/ic_keyboard_toggle_caret_up.xml
- catroid/src/main/res/layout/formula_editor_keyboard.xml
- catroid/src/main/res/layout/fragment_formula_editor.xml
- catroid/src/main/res/values/colors.xml
- catroid/src/main/res/values/dimens.xml
- catroid/src/main/res/values/strings.xml
- catroid/src/main/res/values/styles.xml
Ticket: https://jira.catrob.at/browse/CATROID-776
Redesign the editor according to the mockups
> CATROID-776 Redesign of formula editor

- Jenkinsfile.releaseAPK
- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
Allows to upload Pocket Code beta to Google Play alpha of org.catrobat.catroid.test flavor
Like signed release, but debug flag for share.
> Jenkins script for Pocket Code beta release and upload

- catroid/src/main/res/layout/fragment_formula_editor.xml
https://jira.catrob.at/browse/CATROID-879
Minor design change
Because the formula editor is very bright compared to the app overall, the background of the formula editor was deleted.
> CATROID-879 Change formula editor input field

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickCategoryTest.java
https://jira.catrob.at/browse/CATROID-883
> CATROID-883 Fix BrickCategoryTest

- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
https://jira.catrob.at/browse/CATROID-884
- introduce a regular expression to replace the scriptIds as they are irrelevant for comparing the default projects
> CATROID-884 Fix DefaultProjectComparatorTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CatblocksScriptFragmentTest.java
Add some basic tests for Catblocks in Catroid.
https://jira.catrob.at/browse/CATROID-833
> CATROID-833 Missing tests for Catblocks integration

- catroid/src/androidTest/java/org/catrobat/catroid/test/web/AuthenticationCallsTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/loginFragment/LoginDialogFragmentTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/loginfragment/LoginDialogFragmentTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/login/LoginDialogFragment.java
- catroid/src/main/res/values/strings.xml
**Description**
Added cancel button on login dialog options.
**Jira Ticket Reference** :  https://jira.catrob.at/browse/CATROID-744
Attached Screenshot for the same.
> CATROID-744 - Change Login dialog options

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PlaySoundAndWaitBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PlaySoundBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/UserDataItemRVInteractionWrapper.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/DeleteLookDialogTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/DeleteSoundDialogTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/DeleteSpriteDialogTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteAllScenesTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteFirstSceneTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteLookTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteProjectTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteSoundTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackRecyclerViewFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/DataListFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ListSelectorFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/RecyclerViewFragment.java
- catroid/src/main/res/values/strings.xml
https://jira.catrob.at/browse/CATROID-739
> CATROID-739 Change dialog options for deletion

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorEditVariableTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/UserDataItemRVInteractionWrapper.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/DataListFragment.kt
- catroid/src/main/res/values/strings.xml
- catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickVariableUpdateTest.java
https://jira.catrob.at/browse/CATROID-556
Content (Value) of Variable is editable from data list, option will appear on long-press menu.
> CATROID-556 Edit variables

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CatblocksScriptFragmentTest.java
Disable Catblocks view after Catblocks tests.
https://jira.catrob.at/browse/CATROID-923
> CATROID-923 fix Catblocks test

- catroid/src/main/res/values/strings.xml
https://jira.catrob.at/browse/CATROID-931
Added a tag to all strings used by Catblocks since they should not be deleted in Catroid.
> CATROID-931 Add tags to strings.xml

- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java
> CATROID-854 Add "color touches color" to general properties

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CopyBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/BrickAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
https://jira.catrob.at/browse/CATROID-824
> CATROID-824 Copy connected bricks only

- catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/ForItemInUserListAction.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/ForVariableFromToAction.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/LoopAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/RepeatAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/RepeatParameterizedAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/RepeatUntilAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ForItemInUserListBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ForVariableFromToBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ForeverBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ParameterizedBrick.kt
- catroid/src/main/java/org/catrobat/catroid/content/bricks/RepeatBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/RepeatUntilBrick.java
- catroid/src/main/java/org/catrobat/catroid/utils/LoopUtil.kt
- catroid/src/test/java/org/catrobat/catroid/test/content/actions/RepeatActionTest.kt
- catroid/src/test/java/org/catrobat/catroid/test/content/actions/RepeatUntilActionTest.java
- catroid/src/test/java/org/catrobat/catroid/test/content/bricks/LoopDelayBricksTest.kt
Execute loop delays only if specific bricks are contained within
https://jira.catrob.at/browse/CATROID-760
> CATROID-760 Fast Loops

- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickCategoryFragment.java
With user defined bricks in the release version, we increase the Catrobat language version to 1.0 
> Catrobat language version 1

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/PenDownActionTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/PenUpActionTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/UserDefinedBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/common/FormulaElementOperations.kt
- catroid/src/main/java/org/catrobat/catroid/sensing/ColorCollisionDetection.kt
- catroid/src/test/java/org/catrobat/catroid/test/content/actions/DeleteItemOfUserListActionTest.kt
- catroid/src/test/java/org/catrobat/catroid/test/stage/ColorCollisionParameterTest.kt
Ticket: https://jira.catrob.at/browse/CATROID-972
> CATROID-972 Fix NPE in ColorCollisionParameterTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/UndoTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.java
https://jira.catrob.at/browse/CATROID-927
> CATROID-927 Incorrect loading of the script view after undo

- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ForItemInUserListBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ForVariableFromToBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/HideTextBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ShowTextBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ShowTextColorSizeAlignmentBrick.java
- catroid/src/main/java/org/catrobat/catroid/stage/ShowTextActor.java
- catroid/src/main/res/values/strings.xml
https://jira.catrob.at/browse/CATROID-334
Localize variable: NO_VARIABLE_SELECTED, with the updated string value.
> CATROID-334 Localize variable NO_VARIABLE_SELECTED

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/ProjectActivityTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectOptionsTest.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/content/Project.java
- catroid/src/main/java/org/catrobat/catroid/content/XmlHeader.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectUploadActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectDetailsFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
- catroid/src/main/res/drawable/button_background_selector_dark.xml
- catroid/src/main/res/drawable/divider.xml
- catroid/src/main/res/layout/fragment_project_options.xml
- catroid/src/main/res/layout/fragment_project_show_details.xml
- catroid/src/main/res/menu/menu_project_activity.xml
- catroid/src/main/res/values/colors.xml
- catroid/src/main/res/values/strings.xml
https://jira.catrob.at/browse/CATROID-788
- added project options view in project overflow menu and on long press in the project list overview
- removed show details on long press in the project list overview since it is reachable through the project options view
- added testcase
- removed duplicate menu items
- show existing tags, but not selectable
> CATROID-788 Add project options view

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorMultiplayerVariablesTest.java
https://jira.catrob.at/browse/CATROID-950
> CATROID-950 Fix testCannotSelectMultiplayerAndListTogether

- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java
- catroid/src/main/res/values/strings.xml
Renamed General Properties to Look Properties in the Properties list in the formula editor.
> CATROID-852 Rename General Properties to Look Properties

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/loginfragment/LoginDialogFragmentTest.java
https://jira.catrob.at/browse/CATROID-948
> CATROID-948 Fix cancelButtonTest

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/ReplaceExistingProjectDialogTest.java
https://jira.catrob.at/browse/CATROID-975
> CATROID-975 Fix testFragment[0]

- catroid/src/main/res/layout/dialog_formula_editor_intro.xml
- catroid/src/main/res/values/strings.xml
Changed the text of the first formula editor introduction page to: "With the formula editor, you can create mathematical and logical formulas that you can use in your bricks. Continue by tapping “NEXT” or exit with “SKIP”."
Also, changed the string of the introduction buttons "SKIP" and "NEXT" to uppercase letters and the font "Roboto" for buttons, text, and title.
https://jira.catrob.at/browse/CATROID-969
Signed-off-by: ritiksp2411 <ritik.rjt@gmail.com>
> CATROID-969 Change formula editor introduction buttons and text

- catroid/src/main/java/org/catrobat/catroid/content/bricks/UserDataBrick.java
Fix incorrect placeholder in for-each brick
https://jira.catrob.at/browse/CATROID-973
> CATROID-973 Fix incorrect placeholder in for-each brick

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/SortProjectsTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/rvutils/RecyclerViewInteractionWrapper.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/rvutils/RecyclerViewMatcher.java
- catroid/src/main/java/org/catrobat/catroid/common/ProjectData.java
- catroid/src/main/java/org/catrobat/catroid/common/SharedPreferenceKeys.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/ExtendedRVAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/RecyclerViewFragment.java
- catroid/src/main/res/menu/menu_projects_activity.xml
- catroid/src/main/res/values/strings.xml
Sorting local projects lexicographically by clicking the sort button in the menu and undo sorting by clicking againg on the unsort button in the menu.
https://jira.catrob.at/browse/CATROID-912
> CATROID-912 Sorting local projects

- catroid/src/main/java/org/catrobat/catroid/camera/CameraManager.kt
Ticket: https://jira.catrob.at/browse/CATROID-777
> CATROID-777 Crash due to usage of rear camera in combination with face sensors

- .github/workflows/sync_crowdin.yml
- crowdin.yml
> CATROID-946 Github crowdin integration

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorFragmentTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
https://jira.catrob.at/browse/CATROID-998
> CATROID-998 Invalid formula should not exit formula editor

- catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectSaveTask.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.java
https://jira.catrob.at/browse/CATROID-997
> CATROID-997 Show upload dialog after upload from the project options

- catroid/src/main/java/org/catrobat/catroid/common/SharedPreferenceKeys.java
- catroid/src/main/java/org/catrobat/catroid/common/Survey.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
- catroid/src/main/java/org/catrobat/catroid/transfers/GetSurveyTask.java
- catroid/src/main/java/org/catrobat/catroid/ui/BaseActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectUploadActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
- catroid/src/main/java/org/catrobat/catroid/web/CatrobatServerCalls.kt
- catroid/src/main/java/org/catrobat/catroid/web/ServerAuthenticationConstants.java
- catroid/src/test/java/org/catrobat/catroid/test/web/EmbeddedSurveyTest.kt
https://jira.catrob.at/browse/CATROID-895
- agreed with Stefan to only save the last two URLs independently of the language
> CATROID-895 Embedded survey campaign

- catroid/build.gradle
> AppId beta

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CurrentProjectTest.java
Ticket: https://jira.catrob.at/browse/CATROID-1009
> CATROID-1009 fixed testCurrentProjectAfterDownload

- catroid/src/main/java/org/catrobat/catroid/common/Survey.java
- catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
https://jira.catrob.at/browse/CATROID-1016
> CATROID-1016 Show survey always in a WebView

- catroid/src/main/java/org/catrobat/catroid/content/bricks/brickspinner/BrickSpinner.java
https://jira.catrob.at/browse/CATROID-1024
> CATROID-1024 Crash in org.catrobat.catroid.content.bricks.brickspinner.BrickSpinner.showUndo

- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
https://jira.catrob.at/browse/CATROID-1022
> CATROID-1022 Crash in org.catrobat.catroid.ui.SpriteActivity.createActionBarTitle

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/PrivacyPolicyDisclaimerTest.java
Ticket: https://jira.catrob.at/browse/CATROID-1015
Fix privacypolicydisclaimertest.java
> CATROID-1015 Fix privacypolicydisclaimertest.java

- catroid/src/androidTest/java/org/catrobat/catroid/test/io/asynctask/ProjectExportTaskTest.java
- catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectExportTask.java
https://jira.catrob.at/browse/CATROID-1010
> CATROID-1010 Locally saved project files contain spurious undo_code.xml file

- catroid/src/main/java/org/catrobat/catroid/ui/ProjectUtils.kt
https://jira.catrob.at/browse/CATROID-1023
> CATROID-1023 Crash in org.catrobat.catroid.ui.ProjectUtils.showWarningForSuspiciousBricksOnce

- catroid/src/main/java/org/catrobat/catroid/utils/ProjectDownloadUtil.kt
https://jira.catrob.at/browse/CATROID-1028
> CATROID-1028 Crash in kotlin.UninitializedPropertyAccessException

- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CatblocksScriptFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.java
Possible Fix to: https://jira.catrob.at/browse/CATROID-922
> CATROID-922 Very high frequency crash in catroid.ui.SpriteActivity.onCreate

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectOptionsTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.java
https://jira.catrob.at/browse/CATROID-1043
> CATROID-1043 CRITICAL/HOTFIX-REQUIRED: Severe loss of all edits after renaming project via "Project properties" from object overview interface

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/RecentBricksTest.java
Ticket: https://jira.catrob.at/browse/CATROID-1001
> CATROID-1001 Fix failing testcase in RecentBricksTest

- catroid/config/lint-baseline.xml
Fixing lint warnings due to PR 4081
https://jenkins.catrob.at/job/Catroid/job/PR-4081/7/analysis/
> Fixing lint warnings due to PR 4081

- Jenkinsfile
> DEVOPS-483 - Catroid Jenkins verbosity

- catroid/config/lint-baseline.xml
- catroid/src/androidTest/java/org/catrobat/catroid/test/stage/SearchParameterTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/ScriptFinder.java
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickCategoryFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.java
- catroid/src/main/res/drawable/ic_search.xml
- catroid/src/main/res/layout/fragment_script.xml
- catroid/src/main/res/layout/view_script_finder.xml
- catroid/src/main/res/menu/menu_script_activity.xml
- catroid/src/main/res/values/strings.xml
Ticket: https://jira.catrob.at/browse/CATROID-831
> CATROID-831 Add a search tool to scripts view

- catroid/src/main/java/org/catrobat/catroid/devices/mindstorms/ev3/EV3Reply.java
- catroid/src/main/java/org/catrobat/catroid/devices/mindstorms/nxt/NXTReply.java
- catroid/src/main/java/org/catrobat/catroid/devices/mindstorms/nxt/sensors/NXTI2CUltraSonicSensor.java
- catroid/src/main/java/org/catrobat/catroid/devices/raspberrypi/RaspberryPiService.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormulaTokenSelection.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormulaUtils.java
- catroid/src/main/java/org/catrobat/catroid/io/StageAudioFocus.java
- catroid/src/main/java/org/catrobat/catroid/pocketmusic/note/Project.java
- catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
Removing redundant if statements. https://jira.catrob.at/browse/CATROID-516
> CATROID-516 Remove redundant if statement

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/hardware/SensorTestArduinoServerConnection.java
- catroid/src/main/java/org/catrobat/catroid/common/ParameterizedData.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/ParameterizedAssertAction.kt
- catroid/src/main/java/org/catrobat/catroid/devices/mindstorms/ev3/EV3Command.java
- catroid/src/main/java/org/catrobat/catroid/devices/mindstorms/ev3/EV3Reply.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternToExternGenerator.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternToken.java
- catroid/src/main/java/org/catrobat/catroid/nfc/NfcHandler.java
- catroid/src/main/java/org/catrobat/catroid/sensing/CollisionInformation.java
- catroid/src/main/java/org/catrobat/catroid/stage/ShowBubbleActor.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageResourceHolder.java
- catroid/src/main/java/org/catrobat/catroid/utils/HtmlRegexExtractor.java
https://jira.catrob.at/browse/CATROID-519
> CATROID-519 Replace String Concatenation with StringBuilder

- catroid/src/embroideryDesigner/res/values/colors.xml
- catroid/src/main/res/values/colors.xml
- catroid/src/main/res/values/styles.xml
> CATROID-1060 Colorpicker dialog button Embroidery designer not visible

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/FormulaEditorColorSensorsComputeTest.kt
- catroid/src/main/java/org/catrobat/catroid/sensing/ColorAtXYDetection.kt
- catroid/src/main/java/org/catrobat/catroid/sensing/ColorCollisionDetection.kt
- catroid/src/main/java/org/catrobat/catroid/sensing/ColorDetection.kt
https://jira.catrob.at/browse/CATROID-1080
> CATROID-1080 Fix Crash when calling compute with color sensors

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/utils/BrickTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorSensorListTest.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java
- catroid/src/main/res/values/strings.xml
Ticket: https://jira.catrob.at/browse/CATROID-915
Before | After
-------| -----
> CATROID-915 Separation of Visual Sensors into Face & Text Sensors

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/UserDefinedBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/UserDefinedBrick.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
https://jira.catrob.at/browse/CATROID-1065
> CATROID-1065 There shall be no "Edit formula" option for user defined bricks without inputs

- catroid/src/main/java/org/catrobat/catroid/content/Scene.java
- catroid/src/test/java/org/catrobat/catroid/test/content/sprite/SpriteTest.java
https://jira.catrob.at/browse/CATROID-1085
> CATROID-1085 Fix crash on deleting sprite

- catroid/src/androidTest/java/org/catrobat/catroid/test/stage/SearchParameterTest.java
https://jira.catrob.at/browse/CATROID-1083
> CATROID-1083 Fix flaky SearchParameterTest

- catroid/src/main/java/org/catrobat/catroid/content/actions/AddItemToUserListAction.kt
https://jira.catrob.at/browse/CATROID-1068
The file `AddItemToUserListAction.java` was refactored from Java to Kotlin. The class is very small, so after the initial conversion from Android Studio only a few adjustments had to be made. The Setters were also removed since they are automatically created by Kotlin.
> CATROID-1068 Refactor AddItemToUserListAction to Kotlin

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/VisualPlacementBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/ClipboardTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorUndoTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/actionbar/ActionBarScriptTitleAfterExitingFormulaEditorOneSceneProjectTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/actionbar/ActionBarScriptTitleAfterExitingFormulaEditorTwoScenesProjectTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RemoveTabsTest.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormula.java
- catroid/src/main/java/org/catrobat/catroid/ui/FormulaEditorPopupMenu.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroid/src/main/res/layout/formula_editor_pop_up_menu.xml
- catroid/src/main/res/values/strings.xml
Ticket: https://jira.catrob.at/browse/CATROID-826
Cut/copy/paste for current session in formula editor
> CATROID-826 Cut/copy/paste in formula editor

- catroid/src/main/res/values/strings.xml
The tag tools:ignore="UnusedResources" resulted in a problem with CrowdIn. The tags are removed now.
https://jira.catrob.at/browse/CATROID-1119
> CATROID-1119 Revert string tagging

- catroid/src/main/java/org/catrobat/catroid/sensing/ColorAtXYDetection.kt
- catroid/src/main/java/org/catrobat/catroid/sensing/ColorCollisionDetection.kt
https://jira.catrob.at/browse/CATROID-1088
> CATROID-1088 REFACTOR ColorAtXYDetection and ColorCollisionDetection

- catroid/build.gradle
- catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickCategoryTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/LoadProjectAIExtensionSettingsTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SpeechAIExtensionSettingsBricksTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/rtl/RtlBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorSensorListTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/SettingsFragmentTest.java
- catroid/src/main/java/org/catrobat/catroid/ProjectManager.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/common/FormulaElementResources.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/settingsfragments/AISettingsFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/settingsfragments/SettingsFragment.java
- catroid/src/main/res/values/strings.xml
- catroid/src/main/res/xml/ai_preferences.xml
- catroid/src/main/res/xml/preferences.xml
- catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickSpinnerDefaultValueTest.java
Add an entry for "Artificial intelligence (AI) extension" in the settings, between Web access and Multiplayer extension.
https://jira.catrob.at/browse/CATROID-914
> CATROID-914 AI extension settings

- Jenkinsfile
> DEVOPS-489 Host Huawei Keyfile on Jenkins

- catroid/build.gradle
as discussed, removed the version from the build apk. needs this PR: https://github.com/Catrobat/Paintroid/pull/944/files
> PAINTROID-248 Update: Make "BUILD_WITH_CATROID" flag work again on Jenkins

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/MainMenuFragmentTest.kt
https://jira.catrob.at/browse/CATROID-1054
> CATROID-1054 Missing test case for back-button interaction after tapping on the upload button on the main page

- catroid/src/main/java/org/catrobat/catroid/io/StorageOperations.java
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
- catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectCopyTask.java
- catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectRenameTask.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/BrickAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/MultiViewSpriteAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/RVAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/SceneAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/draganddrop/TouchHelperAdapterInterface.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackLookFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackSceneFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackSoundFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.java
Ticket: https://jira.catrob.at/browse/CATROID-1077
Changed all usages of abrevation "dst" for destination, to "destination" and "src" to "source".
> Catroid-1077 Refactor use of abrevations "dst" and "src" 

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/AddNewActorOrLookDialogTest.kt
- catroid/src/catroid/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/createAtSchool/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/embroideryDesigner/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/lunaAndCat/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/main/res/drawable/ic_apps_white.xml
- catroid/src/main/res/layout/dialog_new_actor.xml
- catroid/src/main/res/values/strings.xml
- catroid/src/phiro/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/pocketCodeBeta/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/standalone/java/org/catrobat/catroid/common/FlavoredConstants.java
*Please enter a short description of your pull request*
https://jira.catrob.at/browse/CATROID-1136
> CATROID-1136 Import project feature - Edit Dialog

- catroid/src/mindstorms/java/org/catrobat/catroid/common/FlavoredConstants.java
> Change mindstorms share url

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/ImportObjectIntoProjectTest.kt
- catroid/src/main/java/org/catrobat/catroid/merge/ImportProjectHelper.kt
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/main/res/layout/dialog_import_rejected.xml
- catroid/src/main/res/values/strings.xml
https://jira.catrob.at/browse/CATROID-1137
> CATROID-1137 Import not possible Dialog

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/BrickSearchTest.kt
- catroid/src/main/AndroidManifest.xml
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddBrickFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDataToUserDefinedBrickFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickCategoryFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickSearchFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/UserDefinedBrickListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
- catroid/src/main/res/layout/fragment_brick_search.xml
- catroid/src/main/res/menu/menu_script_activity.xml
- catroid/src/main/res/menu/menu_search.xml
- catroid/src/main/res/values/strings.xml
- catroid/src/main/res/xml/searchable.xml
https://jira.catrob.at/browse/CATROID-1156
Implements a search functionality in addition to the BrickCategoryFragment, so that the user does not need to search for the bricks manually but just searches for the containing text in the provided searchbar.
> CATROID-1156 Brick Search

- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/ui/filepicker/FilePickerActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/filepicker/FilePickerAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/filepicker/FileVH.java
- catroid/src/main/java/org/catrobat/catroid/ui/filepicker/SelectActionModeCallback.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/RVAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
- catroid/src/main/res/layout/vh_file.xml
- catroid/src/main/res/values/strings.xml
CATROID-430 refactor project import
https://jira.catrob.at/browse/CATROID-430
Refactor project import so the user can import more than one project at once
> CATROID-430 refactor project import

- catroid/src/androidTest/java/org/catrobat/catroid/test/BricksHelpUrlTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickCategoryTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/rtl/RtlBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleAdditivityTest.kt
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/AdditiveParticleEffectAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/bricks/ParticleEffectAdditivityBrick.kt
- catroid/src/main/java/org/catrobat/catroid/io/BackwardCompatibleCatrobatLanguageXStream.java
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.kt
- catroid/src/main/res/layout/brick_additive_particle_effect.xml
- catroid/src/main/res/values/strings.xml
Ticket: https://jira.catrob.at/browse/CATROID-1155
"Turn the particle effect's additivity off/on" brick
> CATROID-1155 "Turn the particle effect's additivity off/on" brick

- catroid/src/androidTest/java/org/catrobat/catroid/test/formulaeditor/RecognizeFormulaInTextTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroid/src/main/res/values/arrays.xml
- catroid/src/main/res/values/strings.xml
recognizes :
- UserVariables, UserLists, MultiplaverVariables
- UserDefinedBrickInputs
- Formulas with arbitrary parameters in paranthesis
- Statements/Formulas without parameters
https://jira.catrob.at/browse/CATROID-829
> CATROID-829 Recognize when user enters formula as text

- catroid/src/main/res/layout/brick_assert_equals.xml
Fixed the `textAlignment` to change according to the language specified.
This was mentioned as a note in https://jira.catrob.at/projects/CATROID/issues/CATROID-1203, and is here fixed for the three-line parameter fields of the "Assert" brick, as of https://jira.catrob.at/browse/CATROID-1086 implemented in #4239.
Before the change:
After the change:
> Fix RTL and LTR alignment mentioned in note in CATROID-1203

- catroid/config/lint-baseline.xml
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/UserDataItemRVInteractionWrapper.java
- catroid/src/main/java/org/catrobat/catroid/ui/ScratchProgramDetailsActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/filepicker/FilePickerActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/RVAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackRecyclerViewFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/DataListFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ListSelectorFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/NfcTagListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/RecyclerViewFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SceneListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/scratchconverter/ScratchProgramsFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/scratchconverter/ScratchSearchResultsFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/viewholder/CheckableVH.java
- catroid/src/main/res/layout/vh_background.xml
- catroid/src/main/res/layout/vh_background_sprite.xml
- catroid/src/main/res/layout/vh_list.xml
- catroid/src/main/res/layout/vh_variable.xml
- catroid/src/main/res/layout/vh_with_checkbox.xml
modified the settings throughout the app to make them conform to the material design guidelines.
https://jira.catrob.at/browse/CATROID-1145
> CATROID-1145 Make object settings material design conform

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/BrickSearchTest.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddBrickFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickCategoryFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickSearchFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
https://jira.catrob.at/browse/CATROID-1201
implement the brick search also into the different brick categories
> Catroid-1201 Implement brick search for each Category

- catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
- catroid/src/main/res/layout/activity_network_error.xml
https://jira.catrob.at/browse/CATROID-677
Make "No internet" message easier to read
> CATROID-677 Make "No internet" message easier to read

- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/mindstorms/ev3/LegoEV3ImplTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/io/asynctask/ProjectExportTaskTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/physics/PhysicsObjectTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/physics/PhysicsObjectTypesTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/physics/collision/CollisionInformationTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/scratchconverter/WebSocketClientTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/sensing/TouchesFingerTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/utiltests/ExifDataTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/test/utiltests/ImageEditingTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/WhenNfcBrickStageTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/visualplacement/VisualPlacementActivityTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/actionbar/ActionBarTitleFullyDisplayedTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectOptionsTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/tabs/SpriteActivityTabsTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/UserVariableAssertions.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/hardware/SensorTestArduinoServerConnection.java
- catroid/src/test/java/org/catrobat/catroid/test/content/UtteranceProgressListenerContainerTest.kt
- catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickWithSecondaryListBroadcastMessageTest.java
- catroid/src/test/java/org/catrobat/catroid/test/formulaeditor/InternFormulaStateTest.java
- catroid/src/test/java/org/catrobat/catroid/test/formulaeditor/InternFormulaTokenSelectionTest.java
- catroid/src/test/java/org/catrobat/catroid/test/note/NoteEventTest.java
- catroid/src/test/java/org/catrobat/catroid/test/note/PocketMusicProjectTest.java
- catroid/src/test/java/org/catrobat/catroid/test/note/TrackTest.java
- catroid/src/test/java/org/catrobat/catroid/test/note/trackgrid/GridRowPositionTest.java
- catroid/src/test/java/org/catrobat/catroid/test/note/trackgrid/GridRowTest.java
- catroid/src/test/java/org/catrobat/catroid/test/note/trackgrid/TrackGridTest.java
- catroid/src/test/java/org/catrobat/catroid/test/utiltests/StringFinderTest.java
Simplified and refactored JUnit assertions throughout the Project.
[CATROID-517](https://jira.catrob.at/browse/CATROID-517)
> CATROID-517 Simplify & Refactor JUnit assertions

- catroid/src/main/java/org/catrobat/catroid/ui/ProjectUploadActivity.kt
https://jira.catrob.at/browse/CATROID-1249
> CATROID-1249 Fix crash on ProjectUpload

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/ClipboardTest.java
https://jira.catrob.at/browse/CATROID-1183
> CATROID-1183 Fix hidePasteWhenClipboardIsEmptyTest

- catroid/src/main/java/org/catrobat/catroid/io/BackwardCompatibleCatrobatLanguageXStream.java
Older Catrobat Language versions used deprecated xml nodes.
Convert xml-node spinnerSelectionID to new node.
Affected bricks:
- CameraBrick, convert spinnerSelectionID to spinnerSelectionON
- ChooseCameraBrick, spinnerSelectionID to spinnerSelectionFRONT
Ticket: [CATROID-1279](https://jira.catrob.at/browse/CATROID-1279)
> CATROID-1279 Project crash on edit

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/BrickSearchTest.kt
Fix testCategorySearch failing on Jenkins, view was not always loading fast enough. Changed testcase!
https://jira.catrob.at/browse/CATROID-1219
> CATROID-1219 Fix failing testCategorySearch

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorKeyboardTest.java
Ticket: https://jira.catrob.at/browse/CATROID-1290
> CATROID-1290 toggleFunctionalButtonsTest in FormulaEditorKeyboardTest keeps crashing in develop branch

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/ClipboardTest.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormula.java
Ticket: https://jira.catrob.at/browse/CATROID-1287
> CATROID-1287 Crash when pasting in formula editor

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/backwardcompatibility/XstreamParserTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PlaySoundBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PointToBrickAdditionalTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SceneBricksTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/looks/gallery/LookFromGalleryIntentTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/looks/gallery/SpriteFromGalleryIntentTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/looks/paintroid/PocketPaintNewLookIntentTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/looks/paintroid/PocketPaintNewSpriteIntentTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/sounds/gallery/SoundFromGalleryIntentTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/stage/LookUndoTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/NewSpriteVisuallyPlaceDialogTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CopySceneTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectOptionsTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameSceneTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/UserDefinedBrickTest.java
- catroid/src/main/java/org/catrobat/catroid/content/Project.java
- catroid/src/main/java/org/catrobat/catroid/content/backwardcompatibility/LegacyProjectWithoutScenes.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/SceneStartBrick.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/SceneTransitionBrick.java
- catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectImportTask.kt
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SceneController.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SceneListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/util/UniqueNameProvider.java
- catroid/src/main/res/values/strings.xml
- catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickSpinnerDefaultValueTest.java
- catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickSpinnerTest.java
- catroid/src/test/java/org/catrobat/catroid/test/utiltests/UniqueNameProviderTest.java
https://jira.catrob.at/browse/CATROID-1277
> CATROID-1277 No number appended for first unique name

- catroid/src/androidTest/java/org/catrobat/catroid/retrofittesting/CatroidWebServerAuthenticationTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/regression/activitydestroy/MainMenuFragmentActivityRecreateRegressionTest.java
- catroid/src/main/java/org/catrobat/catroid/koin/CatroidKoinHelper.kt
- catroid/src/main/java/org/catrobat/catroid/retrofit/RetrofitWebServer.kt
- catroid/src/main/java/org/catrobat/catroid/retrofit/models/AuthenticationDataClasses.kt
- catroid/src/main/java/org/catrobat/catroid/transfers/TokenTask.kt
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectUploadActivity.kt
- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
- catroid/src/main/java/org/catrobat/catroid/web/ServerAuthenticationConstants.java
- catroid/src/main/java/org/catrobat/catroid/web/ServerCalls.java
https://jira.catrob.at/browse/CATROID-1250
> CATROID-1250 Implement upgrade token API call

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/AddNewActorOrLookDialogTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/ImportLocalSpriteTest.kt
- catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
- catroid/src/main/java/org/catrobat/catroid/merge/ImportProjectHelper.kt
- catroid/src/main/java/org/catrobat/catroid/ui/ImportLaunchers.kt
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectListActivity.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/RecyclerViewFragment.java
- catroid/src/main/res/drawable/ic_library_add.xml
- catroid/src/main/res/layout/dialog_new_actor.xml
- catroid/src/main/res/values/strings.xml
import first actor from local project of choice 
https://jira.catrob.at/browse/CATROID-1149
*  first actor gets added
* added new test
> CATROID-1149 import object from local project into current

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/looks/paintroid/PocketPaintNewSpriteDiscardIntentTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/NewSpriteDialogFragment.kt
- catroid/src/main/res/values/strings.xml
https://jira.catrob.at/browse/CATROID-1089
> CATROID-1089 Object cannot be created without a look

- catroid/src/main/res/values-ml/strings.xml
- catroid/src/main/res/values-sr/strings.xml
Quick fix for static analysis error on 2 files which are not longer supported with our current crowdin config.
Unsure if there is a error with these files not bein supported anymore and will create a ticket to investigate
> Fix static analysis errors

- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
- catroid/src/main/java/org/catrobat/catroid/io/XStreamFormulaElementConverter.kt
- catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
https://jira.catrob.at/browse/CATROID-1298
> CATROID-1298 Fix Sensor Bug

- catroid/build.gradle
- catroid/src/androidTest/java/org/catrobat/catroid/test/devices/multiplayer/MultiplayerTest.kt
- catroid/src/main/java/org/catrobat/catroid/bluetooth/BluetoothDeviceFactoryImpl.java
- catroid/src/main/java/org/catrobat/catroid/bluetooth/BluetoothDeviceServiceImpl.java
- catroid/src/main/java/org/catrobat/catroid/bluetooth/ConnectBluetoothDeviceActivity.java
- catroid/src/main/java/org/catrobat/catroid/content/Project.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/ChangeVariableAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/SetVariableAction.java
- catroid/src/main/java/org/catrobat/catroid/devices/multiplayer/Multiplayer.kt
- catroid/src/main/java/org/catrobat/catroid/devices/multiplayer/MultiplayerInterface.kt
- catroid/src/main/java/org/catrobat/catroid/stage/StageLifeCycleController.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageResourceHolder.java
- catroid/src/main/res/layout/device_list.xml
- catroid/src/main/res/values/strings.xml
- catroid/src/test/java/org/catrobat/catroid/test/content/actions/BluetoothMultiplayerActionTest.kt
https://jira.catrob.at/browse/CATROID-544
https://jira.catrob.at/browse/CATROID-545
> CATROID-544 Establish Bluetooth connection for multiplayer apps

- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.kt
> fix draw action in new actor or object dialog.

- catroid/src/main/res/values/strings.xml
https://jira.catrob.at/browse/CATROID-1331
> CATROID-1331 Fix static analysis error

- catroid/src/main/java/org/catrobat/catroid/formulaeditor/function/BinaryFunction.kt
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/function/BinaryFunctionAction.kt
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/function/FormulaFunction.kt
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/function/FunctionProvider.kt
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/function/ObjectDetectorFunctionProvider.kt
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/function/TernaryFunction.kt
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/function/TernaryFunctionAction.kt
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/function/UnaryFunction.kt
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/function/UnaryFunctionAction.kt
https://jira.catrob.at/browse/CATROID-1317
> CATROID-1317 REFACTOR: Unary/BinaryFunction and its interfaces to Kotlin

- Jenkinsfile
> DEVOPS-669 Added build params and seperator

- Jenkinsfile
Fixed typos as requested - no jira ticket
> Jenkins params typos

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/ChromeCastDialogTest.kt
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/NewSpriteDialogFragment.kt
https://jira.catrob.at/browse/CATROID-1300
> CATROID-1300 Fix chromecast dialog appearing in wrong context

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/regression/activitydestroy/SoundFragmentActivityRecreateRegressionTest.java
https://jira.catrob.at/browse/CATROID-1360
> CATROID-1360 Fix testActivityRecreateRenameSoundDialog

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/regression/activitydestroy/SoundFragmentActivityRecreateRegressionTest.java
- catroid/src/main/res/layout/dialog_new_sound.xml
- catroid/src/main/res/values/strings.xml
Added string and replaced it
[https://jira.catrob.at/browse/CATROID-1337](https://jira.catrob.at/browse/CATROID-1337)
> CATROID-1337 "Looks" shown instead of "Sounds"

- Jenkinsfile
[DEVOPS-677] Introduce Jenkinsfile file check and disable publish checks
> [DEVOPS-677] Introduce Jenkinsfile file check and disable publish checks

- catroid/src/androidTest/java/org/catrobat/catroid/retrofittesting/CatroidWebServerAuthenticationTest.kt
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/retrofit/RetrofitWebServer.kt
- catroid/src/main/java/org/catrobat/catroid/retrofit/models/AuthenticationDataClasses.kt
- catroid/src/main/java/org/catrobat/catroid/transfers/TokenTask.kt
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectUploadActivity.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/login/LoginDialogFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/login/RegistrationDialogFragment.kt
- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
https://jira.catrob.at/browse/CATROID-1362
> CATROID-1362 Implement Refresh Token API call

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/UploadUnmodifiedExampleProjectTest.kt
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectUploadActivity.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/MainMenuFragment.kt
https://jira.catrob.at/browse/CATROID-773
> CATROID-773 Upload unmodifed example project

- catroid/src/main/java/org/catrobat/catroid/ui/ScratchProgramDetailsActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/DataListAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/RVAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/UserDataRVAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackRecyclerViewFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/DataListFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/RecyclerViewFragment.java
- catroid/src/main/res/layout/view_holder_sprite_group_item.xml
Make the 3 dots and ripples disappear when the user goes into select mode(copy/delete etc.)
https://jira.catrob.at/browse/CATROID-1342
> CATROID-1342 Make 3dots and ripples disappear on select mode

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/ConnectBluetoothDeviceActivityTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/matchers/DrawableMatchers.java
- catroid/src/debug/AndroidManifest.xml
- catroid/src/main/java/org/catrobat/catroid/bluetooth/ConnectBluetoothDeviceActivity.java
- catroid/src/main/java/org/catrobat/catroid/common/SharedPreferenceKeys.java
- catroid/src/main/res/drawable/ic_close.xml
- catroid/src/main/res/layout/bluetooth_connection_screen.xml
- catroid/src/main/res/layout/device_list.xml
- catroid/src/main/res/layout/dialog_multiplayer_bluetooth.xml
- catroid/src/main/res/menu/menu_bluetooth_connection.xml
- catroid/src/main/res/values/colors.xml
- catroid/src/main/res/values/dimens.xml
- catroid/src/main/res/values/strings.xml
https://jira.catrob.at/browse/CATROID-1150
> CATROID-1150 Redesign of Bluetooth Screen

- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/BrickSearchTest.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickSearchFragment.kt
Implement progressive Brick search + test
https://jira.catrob.at/browse/CATROID-1214
> CATROID-1214 implement progressive Bricksearch

- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/CatroidApplication.java
- catroid/src/main/java/org/catrobat/catroid/camera/CatdroidImageAnalyzer.kt
- catroid/src/main/java/org/catrobat/catroid/camera/FaceTextPoseDetectorHuawei.kt
- catroid/src/main/java/org/catrobat/catroid/camera/VisualDetectionHandler.kt
- catroid/src/main/java/org/catrobat/catroid/camera/mlkitdetectors/Detector.kt
- catroid/src/main/java/org/catrobat/catroid/camera/mlkitdetectors/FaceDetector.kt
- catroid/src/main/java/org/catrobat/catroid/camera/mlkitdetectors/ObjectDetector.kt
- catroid/src/main/java/org/catrobat/catroid/camera/mlkitdetectors/PoseDetector.kt
- catroid/src/main/java/org/catrobat/catroid/camera/mlkitdetectors/TextDetector.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/SetListeningLanguageAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/StartListeningAction.kt
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/function/ObjectDetectorFunctionProvider.kt
- catroid/src/main/java/org/catrobat/catroid/koin/CatroidKoinHelper.kt
- catroid/src/main/java/org/catrobat/catroid/stage/HmsSpeechRecognitionHolder.kt
- catroid/src/main/java/org/catrobat/catroid/stage/HuaweiTextToSpeechHolder.kt
- catroid/src/main/java/org/catrobat/catroid/stage/SpeechSynthesizer.kt
- catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageLifeCycleController.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageResourceHolder.java
- catroid/src/main/java/org/catrobat/catroid/utils/TextBlockUtil.kt
- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
Temporarily removed the inclusion of the ML libraries and commented out the sections where they were used.
https://jira.catrob.at/browse/CATROID-1408
> CATROID-1408 Replace ML libraries with dummy libraries

- catroid/src/main/AndroidManifest.xml
> [Maintenance] Makes Paintroid "build with Catroid" working again

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorEditTextTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/DataListFragment.kt
> CATROID-1384 Continuously update parameter field in formula editor

- catroid/src/main/res/values/dimens.xml
See https://github.com/Catrobat/Catroid/pull/4521
> CATROID-554 Data overview in formula editor becomes unusable

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/ProjectUploadDialogTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectUploadActivity.kt
- catroid/src/main/res/values/strings.xml
https://jira.catrob.at/browse/CATROID-1376
> CATROID-1376 Default Project Name in Upload error message is wrong

- catroid/src/androidTest/java/org/catrobat/catroid/test/io/asynctask/ProjectExportTaskTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectOptionsTest.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.kt
Export projects to Downloads-directory
https://jira.catrob.at/browse/CATROID-1394
> CATROID-1394 Export projects to Downloads-directory

- catroid/src/catroid/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/createAtSchool/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/embroideryDesigner/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/lunaAndCat/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/web/requests/HttpRequests.kt
- catroid/src/mindstorms/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/phiro/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/pocketCodeBeta/java/org/catrobat/catroid/common/FlavoredConstants.java
- catroid/src/standalone/java/org/catrobat/catroid/common/FlavoredConstants.java
https://jira.catrob.at/browse/CATROID-1390
> CATROID-1390 Upload projects via upload.catrob.at only

- catroid/src/androidTest/java/org/catrobat/catroid/test/embroidery/EmbroideryFileExporterTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/ExportLaunchers.kt
https://jira.catrob.at/browse/CATROID-1399
DUplicate of https://github.com/Catrobat/Catroid/pull/4524 + fixed the failing test
> CATROID-1399 Bluetooth export (.catrobat, .dst)

- catroid/build.gradle
- fastlane/Fastfile
> Fix release filename

- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
- catroid/src/main/java/org/catrobat/catroid/ui/adapter/PrototypeBrickAdapter.java
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickSearchFragment.kt
- catroid/src/main/res/layout/fragment_brick_search.xml
https://jira.catrob.at/browse/CATROID-1425
Increase the performance of the bricksearch
- [X ] Include the name of the Jira ticket in the PR’s title
- [] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer
> CATROID-1425 Fix Performance of BrickSearch

- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
Patch to increase the Catrobat language version (missed in https://github.com/Catrobat/Catroid/pull/4566 )
> CATROID-1424 'Start sound PULLDOWN at XX seconds' brick

- build.gradle
- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/CatroidApplication.java
- catroid/src/main/java/org/catrobat/catroid/camera/CameraManager.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/SetListeningLanguageAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/SpeakAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/SpeakAndWaitAction.kt
- catroid/src/main/java/org/catrobat/catroid/content/actions/StartListeningAction.kt
- catroid/src/main/java/org/catrobat/catroid/koin/CatroidKoinHelper.kt
- catroid/src/main/java/org/catrobat/catroid/stage/SpeechRecognitionHolderFactory.kt
- catroid/src/main/java/org/catrobat/catroid/stage/StageResourceHolder.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java
- catroid/src/main/java/org/catrobat/catroid/utils/MobileServiceAvailability.kt
- catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
> Remove huawei libs

- catroid/src/main/res/layout/view_holder_list.xml
- catroid/src/main/res/layout/view_holder_variable.xml
> CATROID-1467 Checkboxes for deleting variables missing

- build.gradle
- catroid/src/main/AndroidManifest.xml
- catroid/src/test/java/org/catrobat/catroid/stage/SpeechRecognitionHolderFactoryTest.kt
- catroid/src/test/java/org/catrobat/catroid/utils/MobileServiceAvailabilityTest.kt
> Fix manifest and remove Huawei vestiges

- catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.kt
Fixxes also failing tests RTLOptionMenuIconTest
https://jira.catrob.at/browse/CATROID-1498
> CATROID-1498 Option's Icons aren't shown

- catroid/build.gradle
Same issue as with UI-tests also came up in Unit tests. For detailed description see this [PR-4672](https://github.com/Catrobat/Catroid/pull/4672) 
> [MAINTENANCE] Fix for cannot resolve symbol in unit tests

- catroid/src/main/java/org/catrobat/catroid/content/actions/CloneAction.kt
- catroid/src/test/java/org/catrobat/catroid/test/content/actions/CloneActionTest.kt
Jira ticket: https://jira.catrob.at/browse/CATROID-1069
> CATROID-1069 REFACTOR CloneAction to Kotlin

- catroid/build.gradle
Jira ticket: https://jira.catrob.at/browse/CATROID-1519
Fixed unresolved imports in org.catrobat.catroid(test) file
> CATROID-1519 fixed unresolved imports in org.catrobat.catroid(test) file

- catroid/src/main/java/org/catrobat/catroid/content/actions/SceneStartAction.kt
I have refactored the SceneStartAction form Java to Kotlin , I have got rid of !! made sure that there isn't any NPE
Jira ticket : https://jira.catrob.at/browse/CATROID-1318
> Refactored SceneStartAction to kotlin

- Jenkinsfile
> Remove debug info from logs

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/FormulaEditorComputeDialogUserDefinedBrickInputTest.kt
The test was broken by some refactoring. 
[IDE-199](https://jira.catrob.at/browse/IDE-199)
> IDE-199 fix FormulaEditorComputeDialogUserDefinedBrickInputTest

- Jenkinsfile
[IDE-30](https://jira.catrob.at/browse/IDE-30) Build-parameter to build Catroid PRs with Paintroid develop branch on Jenkins
This PR has been migrated from https://github.com/Catrobat/Catroid/pull/4568.
The configuration adds the option to build the project with the most recent commit from `Paintroid/develop` into the "Parameters" Menu in Jenkins.
> IDE-30 Build-parameter to build Catroid with Paintroid develop

- Jenkinsfile
- catroid/src/main/java/org/catrobat/catroid/content/WhenBounceOffScript.java
- Do not run the Paintroid build by defaut
- Fix the linter errors
https://jira.catrob.at/browse/IDE-204
> IDE-204  Fix build Pipeline

- catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickAddCategoryTest.java
Fix the test.
https://jira.catrob.at/browse/IDE-206
> IDE-206 Fix BrickAddCategoryTest.categoriesTest

- catroid/src/main/java/org/catrobat/catroid/TrustedDomainManager.kt
- catroid/src/test/java/org/catrobat/catroid/test/utiltests/TrustedUserDomainsTest.kt
https://jira.catrob.at/browse/IDE-207
> IDE-207 Fix TrustUserDomainsTest

- Jenkinsfile
- catroid/build.gradle
- catroid/gradle/emulator.gradle
Improve pipeline
- Improve the handling of the emulator
- Add a gradle task to disable the animations
- Log the output of the emulator
- Remove the shared .gradle volume
>  Improve pipeline

- catroid/build.gradle
- catroid/src/catroid/res/drawable/ic_assistant.xml
- catroid/src/main/java/org/catrobat/catroid/ui/BottomBar.kt
- catroid/src/main/java/org/catrobat/catroid/ui/ProjectListActivity.kt
- catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CatblocksScriptFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/DataListFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ListSelectorFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
- catroid/src/main/res/layout/list_action_buttons.xml
https://jira.catrob.at/browse/IDE-174
https://jira.catrob.at/browse/CATAI-1
A button for the AI assistant in script view was added, the functionality will be added as soon as the GSoC project (Flutter module) is finished.
Currently the button is only visible in the Debug mode.
> IDE-174 Add floating AI assistant button

- catroid/gradle/emulator.gradle
Update the the versions in the TargetAPI annotations. 
Only run 'disableAnimations' when the task is executed.
> Fix disableAnimations task,

- catroid/src/main/java/org/catrobat/catroid/stage/TextActor.kt
Jira ticket: https://jira.catrob.at/browse/IDE-145
> IDE-145 Refactor TextActor to kotlin

- catroid/src/main/java/org/catrobat/catroid/stage/TestResult.kt
Jira ticket: https://jira.catrob.at/browse/IDE-146
> IDE-146 Refactor TestResult to kotlin

- catroid/src/androidTest/java/org/catrobat/catroid/test/utils/StopwatchTest.kt
- catroid/src/main/java/org/catrobat/catroid/utils/Stopwatch.kt
Jira ticket: https://jira.catrob.at/browse/IDE-151
> IDE-151 Refactor Stopwatch.java to kotlin

- catroid/src/main/java/org/catrobat/catroid/web/Cookie.kt
- catroid/src/test/java/org/catrobat/catroid/test/web/CookieTest.kt
jira ticket: https://jira.catrob.at/browse/IDE-149
> IDE-149 Refactor Cookie.java to kotlin

- catroid/src/androidTest/java/org/catrobat/catroid/test/content/backpack/BackpackUserDefinedBricksTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/test/content/messagecontainer/BackpackBroadcastMessageTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/ui/BackpackTest.kt
- catroid/src/main/java/org/catrobat/catroid/common/Backpack.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
- catroid/src/main/java/org/catrobat/catroid/koin/CatroidKoinHelper.kt
- catroid/src/main/java/org/catrobat/catroid/ui/controller/BackpackListManager.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackScriptFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SpriteController.java
also fixes IDE-90 Variable gets falsely renamed when unpacked
Rebirth of https://github.com/Catrobat/Catroid/pull/4392
https://jira.catrob.at/browse/IDE-40
> IDE-40 Variables in backpacks removed

- catroid/src/androidTest/java/org/catrobat/catroid/test/physics/actions/IfOnEdgeBouncePhysicsActionTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/physics/actions/SetBounceFactorActionTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/test/stage/ScreenshotSaverTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/test/utiltests/DefaultProjectComparatorTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/stage/StageScreenshotTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/stage/StageSimpleTest.java
- catroid/src/embroideryDesigner/java/org/catrobat/catroid/common/defaultprojectcreators/DefaultExampleProject.java
- catroid/src/main/java/org/catrobat/catroid/camera/VisualDetectionHandler.kt
- catroid/src/main/java/org/catrobat/catroid/common/ScreenValues.java
- catroid/src/main/java/org/catrobat/catroid/common/defaultprojectcreators/ChromeCastProjectCreator.java
- catroid/src/main/java/org/catrobat/catroid/common/defaultprojectcreators/DefaultProjectCreator.java
- catroid/src/main/java/org/catrobat/catroid/content/Project.java
- catroid/src/main/java/org/catrobat/catroid/content/actions/GoToRandomPositionAction.java
- catroid/src/main/java/org/catrobat/catroid/physics/PhysicsWorld.java
- catroid/src/main/java/org/catrobat/catroid/stage/ShowTextActor.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
- catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
- catroid/src/main/java/org/catrobat/catroid/ui/MarketingActivity.java
- catroid/src/main/java/org/catrobat/catroid/ui/dialogs/StageDialog.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
- catroid/src/main/java/org/catrobat/catroid/utils/ProjectManagerExtensions.kt
- catroid/src/main/java/org/catrobat/catroid/utils/Resolution.kt
- catroid/src/main/java/org/catrobat/catroid/utils/ScreenValueHandler.java
- catroid/src/main/java/org/catrobat/catroid/utils/TextBlockUtil.kt
- catroid/src/main/java/org/catrobat/catroid/visualplacement/VisualPlacementActivity.java
- catroid/src/test/java/org/catrobat/catroid/test/content/actions/TurnLeftActionTest.java
- catroid/src/test/java/org/catrobat/catroid/test/content/actions/TurnRightActionTest.java
- catroid/src/test/java/org/catrobat/catroid/test/utiltests/ResolutionTest.kt
https://jira.catrob.at/browse/CATROID-581
In the StageActivity there exist a few methods which are responsible for resizing the project's resolution in order the fit the mobile device's screen.
This code was extracted into a new class (-> Resolution) and tests were created. Same or similar calculations in other places throughout the code base were refactored to use this new class in order to consolidate the responsibility for resizing in one single place.
> CATROID-581 Refactor handling of screen sizes in StageActivity

- .idea/vcs.xml
- README.md
- automationScripts/createBetaTestingPocketCodeAPK.py
- automationScripts/increaseVersionByOne.py
> [DEVOPS-819] Replace old Jira and Confluence links

- Jenkinsfile.BuildStandalone
- Jenkinsfile.ManualTests
- Jenkinsfile.OutgoingNetworkCallsTests
- Jenkinsfile.SensorboxTests
- Jenkinsfile.buildMetadata
- Jenkinsfile.releaseAPK
Copy the working docker parameters from Jenkinsfile to other Jenkinsfiles
> [DEVOPS-825] Copy unified dockerparameters from Jenkinsfile to other Jenkinsfiles

- Jenkinsfile
> [DEVOPS-830] Fix name of colorpicker

- Jenkinsfile
> [DEVOPS-830] Fix path of colorpicker 

- Jenkinsfile
> [DEVOPS-830] Fix path of colorpicker

- Jenkinsfile
> [DEVOPS-830] Fix path of build with Paintroid

- Jenkinsfile
> [DEVOPS-830] Fix path of build with Paintroid 

- catroid/build.gradle
- gradle.properties
> [DEVOPS-830] Add jvm setting

- catroid/build.gradle
- gradle.properties
> Remove maxmetaspacesize

- Jenkinsfile
> Add reuse node true

- catroid/build.gradle
- gradle.properties
> Add more jvm memory

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/MainMenuFragmentTest.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/MainMenuFragment.kt
- catroid/src/main/res/drawable/ic_play_circle.xml
- catroid/src/main/res/layout/fragment_main_menu.xml
- catroid/src/main/res/values/strings.xml
- Add ic_play_circle android vector image
- Add imageview to fragment_main_menu.xml
- Add Click logic to MainMenuFragment
- Add Test to MainMenuFragmentTest
> IDE-154 Add a play button to the landing page

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/ShowTextColorSizeAlignmentBrickTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorColorVisualizeTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorKeyboardTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorUndoTest.java
- catroid/src/main/java/org/catrobat/catroid/content/bricks/FormulaBrick.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaSpannableStringBuilder.kt
- catroid/src/main/java/org/catrobat/catroid/formulaeditor/VisualizeColorString.kt
- catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- catroid/src/main/res/values/strings.xml
- Visualize ColorStrings in ScriptView
- Visualize ColorStrings in FormulaEditor
- Add FormulaSpannableStringBuilder Object-Class
- Add VisualizeColorString Class
- Add VisualizeColorImageSpan Class
- Add logic to getView in FormulaBrick
- Add logic to updateTextAndCursorFromInternFormula in FormulaEditorEditText
- Add logic to refreshFormulaPreviewString in FormulaEditorFragment
- Add FormulaEditorColorVisualizeTest
> IDE-116 Visualize the color code in formulas

- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/utils/BrickTestUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CopyLookTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CopySoundTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteLookTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteProjectTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteSoundTest.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectCopierTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/SpriteListFragmentWithObjectTest.kt
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/actionutils/ActionUtils.java
- catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/tabs/TabLayoutActionModeTest.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/RecyclerViewFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SceneListFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.kt
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.kt
In case of having only one option for an action (copy, delete, etc), apply it without asking the user to select the option.
https://jira.catrob.at/browse/CATROID-986
> CATROID-986 If there is only a single choice, do not ask the user which one

- catroid/build.gradle
> Migrate targetSDKVersion 34 and minSDKVersion 31

- catroid/build.gradle
- catroid/src/main/java/org/catrobat/catroid/common/Constants.java
> Increase Version Code and Version Number

- catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormula.java
- catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.kt
- catroid/src/main/res/values-de/strings.xml
There is no Jira ticket, since these are fixes of issues, that have been found on the team day, which means some of the checkboxes below cannot be fulfilled.
Changes:
- Fixed a few German strings
- Added new German string translation
- Removed "Add from local" option from the actors/objects popup menu
- Fixed a crash which happened when trying to paste empty clipboard
> Teamday fixes

- catroid/build.gradle
- catroid/src/main/AndroidManifest.xml
- catroid/src/main/java/org/catrobat/catroid/transfers/project/ProjectDownloadService.kt
draft PR for targetSDK upgrade in order to explore and evaluate necessary adaptations
> IDE-264 Migrate targetSDKVersion 34

- catroid/build.gradle
> Increase defaultVersionCode to 97

- README.md
As I was looking at the Read.md file I found out that there is no Apple store link provided in the description so I added it
> Added the Apple store link

- Jenkinsfile.releaseAPK
> [JENKINS-391] Update Jenkinsfile.releaseAPK
