catroid/src/org/catrobat/catroid/camera/CameraManager.java, catroid/src/org/catrobat/catroid/facedetection/FaceDetectionHandler.java, catroid/src/org/catrobat/catroid/stage/PreStageActivity.java, catroid/src/org/catrobat/catroid/stage/StageListener.java
* [Nullpointerexception caused in Stagelistener.menuPause()
triggered by FaceDetectionSettingTest fixed.](https://jenkins.catrob.at/job/Catroid-PartialEmulatorUITest/8850/console)
* Refactoring of some Log.e() calls.
The [message](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/lang/Throwable.java#311) of the exception can be null.
[Test ![Green](https://jenkins.catrob.at/static/a6652cc0/images/24x24/blue.png)] (https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/1349/)
=> Nullpointerexception in Stagelistener.menuPause()

catroid/src/org/catrobat/catroid/physics/PhysicsLook.java, catroidTest/src/org/catrobat/catroid/test/physics/PhysicsLookTest.java
There occured a bug after merging the new libgdx with the setX setY and setPosition.
=> CAT-1355 Fix wrong coordinate setting behaviour

catroid/src/org/catrobat/catroid/content/Look.java, catroid/src/org/catrobat/catroid/physics/PhysicsLook.java, catroid/src/org/catrobat/catroid/physics/PhysicsObject.java, catroid/src/org/catrobat/catroid/physics/shapebuilder/PhysicsShapeBuilder.java, catroid/src/org/catrobat/catroid/physics/shapebuilder/PhysicsShapeBuilderStrategyFastHull.java, catroidTest/src/org/catrobat/catroid/test/content/actions/HideActionTest.java, catroidTest/src/org/catrobat/catroid/test/content/actions/ShowActionTest.java, catroidTest/src/org/catrobat/catroid/test/content/sprite/StartResumeSpriteTest.java, catroidTest/src/org/catrobat/catroid/test/physics/PhysicsActiveStageAreaTest.java, catroidTest/src/org/catrobat/catroid/test/physics/PhysicsLookTest.java, catroidTest/src/org/catrobat/catroid/test/physics/actions/SetSizeToActionTest.java, catroidTest/src/org/catrobat/catroid/test/physics/actions/conditional/HideActionAndCollisionTest.java
add getBoundaryBoxDimensions method to PhysicsObject
add public static scaleCoordinate method for Vector2 and float
physicsObject circumference stored as Box2DCoordinate, getter returns NormalCoordinate
calculate physicsObject base shapes according to accuracyLevels
calculate base shapes in separate thread, adjust PhysicsShapeBuilderStrategyFastHull for simultaneous calls
remove public boolean visible in class which extends another with private boolean with same name
add invisible conditions to physicsObjects
handling physicsObjectStates for very small objects
update PhysicsObjectStates after every call to PhysicsObject.setType
downscale large Pixmaps when creating physicsObject Shapes to increase performance
adjust physics tests
correct calculation of PhysicsObjectStateHandler's …
=> CAT-1157 Physics Issue

catroid/src/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
setHasOptionsMenu() triggers a callback (onPrepareOptionsMenu()) which uses the variable formulaEditorEditText. This variable was unassigned when calling setHasOptionsMenu() at the beginning of onCreate().
Now the Test passes:
https://jenkins.catrob.at/job/Catroid-Multi-Job-Custom-Branch-RELOADED/1688/#showFailuresLink
JIRA issue:
https://jira.catrob.at/browse/CAT-1353
=> CAT-1353 fix UserBrickScriptActivityTest

catroidTest/src/org/catrobat/catroid/test/content/actions/BroadcastActionTest.java
added WaitBrick(5) to the broadcast script, this seems to fix a timing issue on some devices with this test
JIRA:
https://jira.catrob.at/browse/CAT-1347
Jenkins:
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/1840/?auto_refresh=false#showFailuresLink
=> CAT-1347 fix BroadcastActionTest.testWhenScriptRestartingItself

catroid/src/org/catrobat/catroid/common/Constants.java, catroid/src/org/catrobat/catroid/web/ServerCalls.java
The URLs for the sharing site as well as the test server have been changed due to new framework deployment of Web team
Tests:
https://jenkins.catrob.at/job/Catroid-Multi-Job-Custom-Branch-RELOADED/1856/#showFailuresLink
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-CustomEmulator-Single-ClassAndPackage-Test/372/
=> CAT-1400 Changed URLs

catroid/src/org/catrobat/catroid/utils/DownloadUtil.java
"fixed" error: everytime when the user downloads a project all previous projects are also loading again in the notification status bar (only loading/not downloading). These lines fix only the display of the additional loading bars, but it needs further debugging why the method onReceiveResult() is called nevertheless for every previous project
=> fixed error in notification statusbar

catroid/src/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
`onPrepareOptionsMenu` gets called before `onCreateView` and
causes a `Nullpointerexception`, because the EditText View of
the Formula Editor is not created yet.
=> CAT-1339 Bricks crashes on Galaxy S3 Mini

catroidBluetoothTestServer/src/org/catrobat/catroid/bluetoothtestserver/BTServer.java, catroidSourceTest/src/org/catrobat/catroid/test/code/CheckForVerifiesOrAssertionsTest.java, catroidSourceTest/src/org/catrobat/catroid/test/code/SystemOutTest.java, catroidSourceTest/src/org/catrobat/catroid/test/utils/Utils.java, catroidTest/src/org/catrobat/catroid/common/bluetooth/BluetoothConnectionProxy.java, catroidTest/src/org/catrobat/catroid/common/bluetooth/BluetoothLogger.java, catroidTest/src/org/catrobat/catroid/common/bluetooth/BluetoothTestUtils.java, catroidTest/src/org/catrobat/catroid/common/bluetooth/ConnectionDataLogger.java, catroidTest/src/org/catrobat/catroid/common/bluetooth/LocalConnectionProxy.java, catroidTest/src/org/catrobat/catroid/common/bluetooth/ObservedInputStream.java, catroidTest/src/org/catrobat/catroid/common/bluetooth/ObservedOutputStream.java, catroidTest/src/org/catrobat/catroid/test/content/bricks/UserBrickTest.java, catroidTest/src/org/catrobat/catroid/test/utils/SimulatedSensorManager.java, catroidTest/src/org/catrobat/catroid/test/utils/StatusBarNotificationManagerTest.java, catroidTest/src/org/catrobat/catroid/test/utiltests/ImageEditingTest.java, catroidTest/src/org/catrobat/catroid/test/utiltests/UtilFileTest.java, catroidTest/src/org/catrobat/catroid/test/utiltests/UtilsTest.java, catroidTest/src/org/catrobat/catroid/test/web/ServerCallsTest.java, catroidTest/src/org/catrobat/catroid/uitest/stage/SwitchToLookCrashTest.java, catroidTest/src/org/catrobat/catroid/uitest/ui/activity/MainMenuActivityTest.java, catroidTest/src/org/catrobat/catroid/uitest/ui/activity/MyProjectsActivityTest.java, catroidTest/src/org/catrobat/catroid/uitest/ui/activity/ProjectActivityTest.java, catroidTest/src/org/catrobat/catroid/uitest/ui/fragment/LookFragmentTest.java, catroidTest/src/org/catrobat/catroid/uitest/ui/fragment/ScriptFragmentTest.java, catroidTest/src/org/catrobat/catroid/uitest/util/SensorTestServerConnection.java, catroidTest/src/org/catrobat/catroid/uitest/util/UiTestUtils.java, catroidTest/src/org/catrobat/catroid/uitest/web/ProjectUpAndDownloadTest.java, config/pmd_logging.xml, gradle/code_quality_tasks.gradle
JIRA issue: 
https://jira.catrob.at/browse/CAT-1275
Jenkins run:
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/1595/
introduced pmd java-logging ruleset
removed system out test
renamed interface org.catrobat.catroid.common.bluetooth.Logger to org.catrobat.catroid.common.bluetooth.BluetoothLogger to make it distinguishable from java.util.logging.Logger for pmd checks
=> [CAT-1275] Introduce pmd java-logging ruleset

catroid/res/values/strings.xml
@thmq Please fix translations at crowdin (Also in german it should be named "Funktionen")
=> CAT-1531 Renamed "Math"-String to "Functions" in FE

catroid/res/values/strings.xml
@thmq Please fix translation files in crowdin (all have the ":" added at the end of new_"project_name-String")
=> CAT-907 Removed colon as proposed

catroid/src/org/catrobat/catroid/content/bricks/ChangeVariableBrick.java, catroid/src/org/catrobat/catroid/content/bricks/SetVariableBrick.java, catroidTest/src/org/catrobat/catroid/uitest/content/brick/ChangeVariableTest.java, catroidTest/src/org/catrobat/catroid/uitest/content/brick/SetVariableTest.java
Multirun manual start:
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/2115/
=> CAT-1443 Set/change variable fixed

catroid/src/org/catrobat/catroid/ProjectManager.java, catroid/src/org/catrobat/catroid/content/bricks/LegoNxtMotorMoveBrick.java, catroid/src/org/catrobat/catroid/content/bricks/PhiroMotorMoveBackwardBrick.java, catroid/src/org/catrobat/catroid/content/bricks/PhiroMotorMoveForwardBrick.java, catroid/src/org/catrobat/catroid/content/bricks/PhiroPlayToneBrick.java, catroid/src/org/catrobat/catroid/content/bricks/PhiroRGBLightBrick.java, catroid/src/org/catrobat/catroid/facedetection/FaceDetectionHandler.java, catroid/src/org/catrobat/catroid/ui/SettingsActivity.java, catroidTest/src/org/catrobat/catroid/test/devices/phiro/PhiroSettingsTest.java, catroidTest/src/org/catrobat/catroid/test/facedetection/FaceDetectionSettingsTest.java, catroidTest/src/org/catrobat/catroid/test/ui/CategoryBricksFactoryTest.java, catroidTest/src/org/catrobat/catroid/uitest/devices/mindstorms/nxt/LegoNXTPreferencesTests.java, catroidTest/src/org/catrobat/catroid/uitest/facedetection/FaceDetectionSettingTest.java
facedetection works now even if it is disabled in the settings. The facedetection setting affects now only the sensor list, i.e. if the facedetection sensors are visible or not
Additionally:
- fix phiro resource issue
- phiro and facedetection gets enabled in the settings if a program with a resource of them are opened
- added tests for new behavior of facedetection and phiro
- fixed 2 nxt tests issues due to new orientation dialog
[Jenkins Test Run](https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/2349/)
=> facedetection fix and resource fixes, mainly needed for standalone apk

.idea/codeStyleSettings.xml
The Android Studio formatter separates static import groups (android,
com, java, ...) by an empty newline now. Like it already does with
normal imports. Checkstyle also requires separated static import groups.
=> Adapt formatter to separate static import groups

config/checkstyle.xml
According to our .gitattributes configuration, checking out files will
convert line endings to native ones and committing will convert line
endings back to LF. Therefore, checking out files on Windows will
convert line endings to CRLF locally. Checkstyle doesn't permit CRLF
line endings and will show lots of errors when ran locally. Since git
normalize line endings on commits automatically, there is no need to
check for unified line endings.
- Remove Windows line ending regexp check
- Adapt NewlineAtEndOfFile check to allow any newline style.
=> Remove Windows line ending checks

catroid/src/org/catrobat/catroid/stage/StageListener.java
If you click in a landscape program on the play button, the activity started twice (first in portrait, then he changed to landscape mode) and so we have incorrect calculations. For this reason we have to reset all data objects at first start and the bug is fixed.
=> CAT-1575 Landscape programs: incorrect calculations

build.gradle
Fixes an issue that prevents gradle.build form running on en_US locale systems because of using the wrong/german quotation marks “” surrounding some statements
=> CAT-1651 Fixed en_US locale gradle build issue

catroid/src/org/catrobat/catroid/common/Constants.java, catroid/src/org/catrobat/catroid/transfers/ProjectUploadService.java, catroid/src/org/catrobat/catroid/ui/dialogs/UploadProjectDialog.java, catroid/src/org/catrobat/catroid/utils/Utils.java, catroid/src/org/catrobat/catroid/web/ServerCalls.java
Trying to log in for upload with restricted profile crashed app.
Restricted profiles are used in school classes on shared tablets.
Quickfix:
- If email returned by AccountManager is null, replace with empty
string, to prevent the null exception.
Further changes to handle arising problems:
- Automaticall invalidate TOKEN to "log out" users again right after
upload, failed upload, and canceled upload. (since without this there
is no possibility to log out to prepare tablets for next class)
Limitations:
- Not possible to register new users using a restricted profile.
- Maybe not automatically logged out if upload process is disrupted.
- Log in error messages for restricted users propably misleading,
eg. not existing username triggers "invalid email adress" error.
=> CAT-1655 Fix upload for restricted profile

catroid/src/org/catrobat/catroid/ui/dialogs/NewSpriteDialog.java
Original bug cannot be reproduced, this fixes behaviour to stay in
project view when adding a new sprite, instead of being forwared
into the script view of the newly added sprite.
=> CAT-1652 Fix behaviour after adding new sprite

build.gradle, catroid/res/values/strings.xml, catroidSourceTest/build.gradle, config/checkstyle.xml, gradle/adb_tasks.gradle, gradle/code_quality_tasks.gradle, gradle/intellij_config_tasks.gradle, settings.gradle
- Add gradle file extension to Checkstyle.
- Add tabs for indentation check for gradle files.
- Add unnecessary multiple newline check for XML files. Maximum is 2 to conform with (almost all) current XML files.
@jonny911: Since there is a change in the strings.xml file, is there any problem with crowdin?
=> Adapt checkstyle rules

catroid/src/org/catrobat/catroid/content/Sprite.java, catroidTest/src/org/catrobat/catroid/test/content/bricks/UserBrickTest.java
This removes the init() method entirely. If the Sprite is created
normally, all members are initialized. If it's loaded by XStream, the
default constructor will be called and all members are initialized as
well. However, they will be replaced by the value in the XML afterwards.
=> Init Sprite members directly in declaration

catroid/src/org/catrobat/catroid/ui/ProjectActivity.java
Timing related problem, happened because onPrepareOptionsMenu of
projectActivity could be called before its onCreateOptionsMenu when
tapping on menu button right after loading the project.
=> CAT-1679 Tapping on menu right after opening a project crashes app

catroidTest/src/org/catrobat/catroid/uitest/content/brick/LedBrickTest.java, catroidTest/src/org/catrobat/catroid/uitest/content/brick/VibrationBrickTest.java
When LedBrickTest is run right after InserItemIntoUserMenuListTest
it throws an exception and ends the local testrun. This is annoying
since jenkins isnt working properly and it prevents me from running
all tests locally overnight.
=> CAT-FIX Fix exception by LedBrickTest when run together with other tests

catroid/res/values-de/strings.xml, catroid/res/values/strings.xml, catroid/src/org/catrobat/catroid/camera/CameraManager.java, catroid/src/org/catrobat/catroid/facedetection/FaceDetectionHandler.java, catroid/src/org/catrobat/catroid/stage/PreStageActivity.java
Fix program crash that happens when no or only one camera is available
on device in following cases:
- restart any program
- resume any program
- start program that utilizes facedetection
Also added message shown on program start if facedetection is to be used
but no camera is available on device.
=> CAT-1673 Program crashes on resume if no or only one camera available

catroid/res/layout/activity_pocketmusic.xml, catroidTest/src/org/catrobat/catroid/uitest/ui/activity/PocketMusicTest.java
added GUI element placeholder for the new musicdroid GUI according to the mockups given from UX-Team.
The GUI exists of a piano, a button grid and a play button on the bottom.
These placeholder elemnts need to be replaced by the original elements in another task.
=> MUS-177 Add Placeholder for musicdroid elements.

.idea/codeStyleSettings.xml, config/checkstyle.xml
By using special comments, the Android Studio code formatter can be
disabled for code blocks. Checkstyle will also be disabled in these
blocks.
// @formatter:off
...
// @formatter:on
https://youtrack.jetbrains.com/issue/IDEA-56995
=> Enable comment markers to disable code formatting per region

catroid/src/org/catrobat/catroid/common/BrickValues.java, catroid/src/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
Fixed the Bug which appears when you don't use PocketCode in english, now we
check before we create all the Bricks in the Category Sound if there is a difference between the constant value for the Brick  and our translated Value. If there is a difference we use the value from the translation file.
=> CAT-1697 Fix translation in CategoryBrickFactory

catroid/src/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion098AndBefore.java
GlideTo bricks were wrongfuly replaced with setText bricks, effectifely
breaking the programs xml and crashing pocketcode.
=> CAT FIX - Repair glideTo bricks for downloaded programs

catroid/src/org/catrobat/catroid/utils/FlashUtil.java
Flash incorrectly started on restart if previous program had it
turned on.
=> CAT-1770 Fix flash for restarting programs

catroid/res/layout/dialog_new_look.xml, catroid/src/org/catrobat/catroid/ui/dialogs/NewLookDialog.java, catroid/src/org/catrobat/catroid/ui/dialogs/NewSpriteDialog.java
Drone video is displayed in add look dialog if it is not enabled in
settings, and also if it is deactivated in build file.
=> CAT 1759 - Drone video in add look dialog

catroid/src/org/catrobat/catroid/ui/SettingsActivity.java
NXT bricks and sensors were not displayed although activated in
settings.
=> CAT-1792 Fix NXT bricks and sensors not displayed

catroid/src/org/catrobat/catroid/web/ProgressResponseBody.java
The problem was that the progress was reported after each read, even if it was the same percentage, that resulted in roughly 200 notification updates per second.
The check introduces a mechanism where progress is only reported if it is at least 1% further than the last update. It has to be in this deep level in the code, cause even checking in the `onReceiveResult()` in `DownloadUtil.java` causes a massive amount of function calls within the android system until it gets there which - in the end - has no effect at all
=> CAT-1775 resolved device freeze on download

catroid/src/org/catrobat/catroid/stage/Passepartout.java
Looks and the passepartout share the same batch during drawing the
stage. Each Look sets the color and alpha value of the batch according
to its settings before drawing itself [1]. The passepartout however
doesn't and therefor uses the alpha value set by the previous Look. So,
when the previous Look sets the alpha value to 0.5, the passepartout
will also be drawn with an alpha value of 0.5 and the background and
other images are shining through it.
By explicitely setting the color of the batch to black and the alpha
value to 1 before drawing the passepartout, the passepartout will remain
black.
[1] https://github.com/libgdx/libgdx/blob/97d6e8d/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Image.java#L119
https://jira.catrob.at/browse/CAT-1078
=> CAT-1078 Fix transparent passepartout issue

catroid/src/org/catrobat/catroid/ui/adapter/BackPackSpriteAdapter.java, catroid/src/org/catrobat/catroid/ui/fragment/BackPackLookFragment.java, catroid/src/org/catrobat/catroid/ui/fragment/BackPackScriptFragment.java, catroid/src/org/catrobat/catroid/ui/fragment/BackPackSoundFragment.java
Context menu in backpack now opens right after it has been clicked (not when it has been released).
=> CAT-1797 Open backpack context menu right after click

catroid/src/org/catrobat/catroid/stage/PreStageActivity.java, catroid/src/org/catrobat/catroid/utils/VibratorUtil.java
If you want to turn on the flashlight on the front camera, but you doesn't have a flashlight there and you also have an vibration brick in your program, you will get an error, the stage will be destroyed, but the vibrator doesn't stop. So i added an check to pause the vibration.
=> CAT-1868 Fix the camera front, flashlight, vibration bug

catroid/src/org/catrobat/catroid/physics/PhysicsCollision.java, catroid/src/org/catrobat/catroid/physics/content/bricks/CollisionReceiverBrick.java
changing the Collision Identifier from the zero-byte to the byte with value 9 (\t) in order to be usable with xml 1.0
locally tested with https://share.catrob.at/pocketcode/program/9546 and https://share.catrob.at/pocketcode/program/9547.
=> HOT - change collision identifier from \0 to \t for XML v1.0

catroid/src/org/catrobat/catroid/common/Constants.java, catroid/src/org/catrobat/catroid/ui/WebViewActivity.java
There's a problem with the WhatsApp sharing link on the Website when started from Pocket Code in WebView. When the share button is clicked, an error is triggered because the WebView doesn't handle custom URI's and start external apps by default.
=> CAT-2006 Handle WhatsApp custom URI scheme in WebView

.idea/codeStyleSettings.xml
Disable import on demand (.*) in Android Studio
The Android Studio Formatter converts imports to a star import if the
configured limit has been exceeded. Since it has in the StorageHandler,
the limit has been highly increased and can be considered disabled now.
https://github.com/Catrobat/Catroid/pull/1770/#issuecomment-228997145
=> Disable import on demand (.*) in Android Studio

catroid/res/layout/brick_if_begin_if.xml, catroid/res/values-de/strings.xml, catroid/res/values/strings-global.xml, catroid/src/org/catrobat/catroid/ProjectManager.java, catroid/src/org/catrobat/catroid/content/Script.java, catroid/src/org/catrobat/catroid/content/actions/IfLogicAction.java, catroid/src/org/catrobat/catroid/content/bricks/IfLogicBeginBrick.java, catroid/src/org/catrobat/catroid/content/bricks/IfThenLogicBeginBrick.java, catroid/src/org/catrobat/catroid/content/bricks/IfThenLogicEndBrick.java, catroid/src/org/catrobat/catroid/io/StorageHandler.java, catroid/src/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion099AndBefore.java, catroid/src/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java, catroidTest/src/org/catrobat/catroid/test/ui/CategoryBricksFactoryTest.java, catroidTest/src/org/catrobat/catroid/uitest/content/brick/IfThenBrickTest.java
**this reopens PR #1766 after rebasing** as requested by @thmq 
New Brick:
- IF-then without ELSE
reuses a lot of the standard if-else brick via inheritance. uses the same Action as the existing brick
This PR includes a TestCase
reviewed & refactored
Tests:
- [jenkins package 'test' results](https://jenkins.catrob.at/job/CatroidSinglePackageEmulatorTest/2170/)
- this pull does not break any tests
-- the two failing tests already fail in the current develop branch (June 23rd): [results for 'develop' branch](https://jenkins.catrob.at/job/CatroidSinglePackageEmulatorTest/2170/)
=> CAT-1954 IF-Then brick without ELSE

catroid/src/org/catrobat/catroid/content/Project.java, catroid/src/org/catrobat/catroid/content/XmlHeader.java, catroid/src/org/catrobat/catroid/transfers/GetTagsTask.java, catroid/src/org/catrobat/catroid/ui/dialogs/UploadProjectDialog.java, catroid/src/org/catrobat/catroid/ui/dialogs/UploadProjectTagsDialog.java, catroid/src/org/catrobat/catroid/utils/UtilFile.java, catroid/src/org/catrobat/catroid/web/ServerCalls.java, catroidTest/src/org/catrobat/catroid/uitest/ui/dialog/UploadDialogTest.java
* Use List<String> for tags instead of a single String or String[].
* Parse tags from a JSONObject.
* Fix endless loop in UploadDialogTest.
* Change ServerCalls.useTestUrl value back to false.
Additional but unimportant cleanup
* Remove unnecessary logs.
* Add log TAGs.
* Use primitives instead of wrappers.
https://github.com/Catrobat/Catroid/pull/1797
$
If a single commit isn't k, let me know. :smile_cat:
I have _not_ tested the code.
@LauraBebek, please review the changes.
=> CAT-REF Refactor tagging code from PR#1797

catroid/src/org/catrobat/catroid/ui/DynamicListView.java, catroid/src/org/catrobat/catroid/ui/ProgramMenuActivity.java
Multitouch bug was a one line fix, which just prevents multitouching for the ListView.
The rename option was maybe lost during a rebase or something and is now back.
=> Fixes DragNDrop Multitouch and Rename Bug

catroid/src/org/catrobat/catroid/content/actions/WaitUntilAction.java
fixes an issue where WaitUntil actions did not always work correctly
at the second time they are executed (e.g. in a loop)
Attention: in a LibGDX action, reset() calls restart(), not the other way round ;-)
=> CAT-FIX fix wait-until action

catroid/src/org/catrobat/catroid/transfers/ProjectDownloadService.java, catroid/src/org/catrobat/catroid/ui/dialogs/OverwriteRenameDialog.java, catroid/src/org/catrobat/catroid/utils/DownloadUtil.java
When downloading a project that already exists, the downloaded, renamed
project did not save any changes and could not be modified since
project name was never updated in project xml.
=> CAT-2073 fix renamed downloaded project not modifiable

catroid/res/layout/formula_editor_keyboard.xml, catroid/res/values/styles.xml, catroid/src/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
There are formulaeditor-uitests that fail, but they also fail using the develop branch, so it is very likely that this has nothing to do with the layoutchanges.
=> CAT-1740 Refactor Formulaeditor

catroid/src/org/catrobat/catroid/stage/StageActivity.java
The error occurred for devices without hardware buttons (menu, back, home).
Previously in a landscape program, a white area was visible that did not
belong to the stage.
Recomputing the screen dimensions in the StageActivity fixes that problem.
=> CAT-1629 fix landscape mode for devices without HW-buttons

catroid/res/values/strings-global.xml
[as requsted by @wslany]
the Raspberry Pi feature contains a link to a help page in the preferences.xml (SettingsActivity).
This changes the link from a confluence Wiki-Page to the shortened URL
http://catrob.at/RaspberryPi
which can be easily redirected to other pages (without touching the Pocket Code app).
=> ARDUINO-FIX Raspberry Pi change URL in SettingsActivity

catroid/src/androidTest/java/org/catrobat/catroid/test/ui/CategoryBricksFactoryTest.java, catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java, catroid/src/main/java/org/catrobat/catroid/content/BroadcastHandler.java, catroid/src/main/java/org/catrobat/catroid/content/Project.java, catroid/src/main/java/org/catrobat/catroid/content/Scene.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/content/WhenClonedScript.java, catroid/src/main/java/org/catrobat/catroid/content/actions/CloneAction.java, catroid/src/main/java/org/catrobat/catroid/content/actions/DeleteThisCloneAction.java, catroid/src/main/java/org/catrobat/catroid/content/actions/GoNStepsBackAction.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/CloneBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/DeleteThisCloneBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/PlaySoundBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/UserBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenClonedBrick.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/DataContainer.java, catroid/src/main/java/org/catrobat/catroid/io/CatroidFieldKeySorter.java, catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java, catroid/src/main/java/org/catrobat/catroid/io/XStreamToSupportCatrobatLanguageVersion0991AndBefore.java, catroid/src/main/java/org/catrobat/catroid/nfc/NfcHandler.java, catroid/src/main/java/org/catrobat/catroid/physics/PhysicsCollisionBroadcast.java, catroid/src/main/java/org/catrobat/catroid/physics/content/bricks/CollisionReceiverBrick.java, catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java, catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java, catroid/src/main/java/org/catrobat/catroid/utils/TouchUtil.java, catroid/src/main/res/layout/brick_clone.xml, catroid/src/main/res/layout/brick_delete_this_clone.xml, catroid/src/main/res/layout/brick_when_cloned.xml, catroid/src/main/res/values/strings.xml
**reopens  #1823**
- create a clone of a Sprite (= Object) via a special Brick
- create a special "Clone" brick that clones the Object in which it is
- all Scripts, Sounds, Variables etc are copied
- add a "When i start as a clone" brick
- is a script-brick that is only executed when Object is cloned
- "When started" ScriptBricks are NOT executed for the clone
- add "Delete this clone" brick
- when executed, the cloned object containing this brick
is deleted
- global variables are shared, local (=per object) variables are copied
for clones.
=> CAT-1938 Clone Sprites Feature

catroid/src/androidTest/java/org/catrobat/catroid/test/io/CatroidFieldKeySorterTest.java, catroid/src/main/java/org/catrobat/catroid/content/Project.java, catroid/src/main/java/org/catrobat/catroid/content/Scene.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/io/CatroidFieldKeySorter.java, catroid/src/main/java/org/catrobat/catroid/io/XStreamFieldKeyOrder.java, catroid/src/main/java/org/catrobat/catroid/io/XStreamMissingSerializableFieldException.java
See commit messages for more details.
> ...If there is an alias defined for the field, the alias has to be used in the annotation.
No real reason behind that. I just think that renaming an alias is less likely then renaming a member variable. So it would be less error prone... But if you guys prefer the member name, let me know.
I created two commits, because the CatroidFieldKeySorter wasn't tested at all. So I tested the general case and then **extended** it to work with annotation as well. I can create two separate Pull Requests if preferred.
@p4p4 :wink: 
Reopens https://github.com/Catrobat/Catroid/pull/1423
=> CAT-1636 Order xstream fields by annotation

catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/SetLookActionTest.java
Previously the test checked if the Sprites Look is not null which has
nothing to do with the SetLookAction itself. Now, the test checks if
the correct LookData has been set for the Look.
=> CAT-FIX Fix wrong assert check in SetLookActionTest

catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenConditionBrick.java
the condition of the WhenConditionBrick was "0" after adding the ScriptBrick.
Now, the default-condition from the categorybricksfactory ("1<2") is used
instead.
=> CAT-FIX WhenConditionBrick - small cosmetic fix

catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/RepeatUntilActionTest.java, catroid/src/main/java/org/catrobat/catroid/content/actions/RepeatUntilAction.java
[CAT-2085](https://jira.catrob.at/browse/CAT-2085)
Previously the repeat until condition has been checked too often.
Because of that, the execution of the loop has been stopped immediately
whenever the condition became true. Now, the condition is only checked
after a _complete_ loop iteration.
added a new test to check previously susceptible situations
=> CAT-2085 Fix incorrect repeat until behavior

catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/GoToBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/PenBricksTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/PlaySoundAndWaitBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/SayBubbleTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/SayForBubbleTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/SceneStartBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/SceneTransitionBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/SetRotationStyleTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/SpeakAndWaitBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/StopScriptBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/ThinkBubbleTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/content/brick/ThinkForBubbleTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/stage/UserBricksExecutionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/ui/fragment/ScenesListFragmentTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/util/UiTestUtils.java
Fixed failing ui tests cause by
* ClassCastException: android.widget.ExpandableListConnector cannot be cast to org.catrobat.catroid.ui.adapter.BrickAdapter
* Sprites not shown in the Sprites Fragment
=> CAT-FIX Fix failing ui tests

catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorCategoryListFragment.java
Disable 'distance to' in formula editor until the possibility to choose other sprites via menu is added.
=> Disable distance to in formula editor

catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/ShowTextActionTest.java, catroid/src/main/java/org/catrobat/catroid/ProjectManager.java, catroid/src/main/java/org/catrobat/catroid/content/Project.java, catroid/src/main/java/org/catrobat/catroid/content/Scene.java, catroid/src/main/java/org/catrobat/catroid/content/SupportProject.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/DataContainer.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/SupportDataContainer.java, catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java, catroid/src/main/java/org/catrobat/catroid/io/XStreamSpriteConverter.java
- Hotfix variables/lists (remove null and double entries when loading old programs)
- Convert sprites of old programs to SingleSprites in XStreamSpriteConverter to prevent double entries in dataContainer
=> CAT-FIX Hotfix variables/lists for release

catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java
Programs of an older catrobat language version are converted to the new one.
For this purpose, it is necessary to create a DefaultScene.
The migration did not copy images and sounds due to double-escaping the path.
This led to situations where e.g. "Foo:bar" was first escaped to "Foo%3ABar" and then in the second
step, the '%' was (erroneously) escaped again, resulting in "Foo%253ABar", which is NOT a valid file path anymore. This commit fixes that issue.
=> HOTFIX conversion problems special chars in project name

catroid/src/main/java/org/catrobat/catroid/content/Look.java, catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
Previously a cloned object always appeared at the origin of the coordinate
system. Now the position is copied as well.
Also copied: transparancy, rotation, color
Last minute request by @wslany for more scratch compatibility in clone brick
Edit: this seems to be an old ticket: [CAT-1384](https://jira.catrob.at/browse/CAT-1384)
=> CAT-1384 HOTFIX cloned object look: copy all properties 

catroid/src/main/java/org/catrobat/catroid/content/bricks/GoToBrick.java
The GoTo brick did not copy the spinner-selection, which caused crashes when
appearing in a WhenCloned script (and potentially also in other features
like backpack, copy brick etc). This should fix the issue.
This is a very HOT HotFix ;)
=> HOTFIX GoTo brick crash with clone - spinner value not copied

catroid/src/main/java/org/catrobat/catroid/content/bricks/SetBackgroundBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/SetLookBrick.java
1. commit introduced in PR #1923 broke the SetBackgroundBrick
-> fixed
2. commit 6c25a4e448e8f0dc165a05b688e6271d87d5784f replaced wrong strings on brick: ´
should be `Switch to Background [...] and wait`, not `Switch to look [...] Background`
=> HOTFIX set Background brick did not work anymore

catroid/src/main/res/values-es/strings.xml
Scene names get escaped with \" in translation. This shouldn't happen and is only translated like that in Spanish.
=> Fix scene escaping

catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
after a Sprite is cloned (using the clone brick), it is necessary to reset the sprite because it might contain Physics-bricks. This creates a PhysicsLook instead of a Look (otherwise Pocket Code would crash). The look properties have to be copied *after* the instantiation of the look.
After this PR, please also merge #1980 
suggested by @robertpainsi in #1972
=> HOTFIX clone looks with physics bricks

catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
It is important that the LookDatas are cloned before the Bricks are
cloned. Otherwise the SetLookBrick LookData would refer to an origin
LookData instead of a cloned one.
It is also important that the Look is created and cloned after the
Bricks are cloned. Otherwise always a Look instance is created instead
of a Look or PhysicsLook.
To fix this problem, first, the LookDatas are cloned, then the Bricks,
then the Look.
https://github.com/Catrobat/Catroid/pull/1973#issuecomment-256002440
=> CAT-FIX Fix LookData reference in Bricks for clones

catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
This Pull Requests builds on https://github.com/Catrobat/Catroid/pull/1973 and is just a info that it should be merged before the next release. After https://github.com/Catrobat/Catroid/pull/1973 has been merged, I'll rebase and update the changes accordingly. I'll add a comment when everything is ready and also will remove this text.
###
When cloning a Sprite in the Stage or IDE [1], all current values of the
Sprite should be copied as well. This commit only addresses the current
LookData because it will fix a NullPointerException.
`E/BaseExceptionHandler: unhandled exception
java.lang.NullPointerException: Attempt to invoke virtual method 'com.badlogic.gdx.graphics.g2d.TextureRegion org.catrobat.catroid.common.LookData.getTextureRegion()' on a null object reference
at …
=> Set look data when cloning

catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
Formulas are evaluated using the sceneToPlay. When in the IDE, the
sceneToPlay always has to be the currentScene so Formulas in the formula
editor are evaluated correctely. During the Stage, the sceneToPlay may
be set to a scene different from the currentScene in the IDE. So, when
leaving the Stage, the sceneToPlay has to be reset to the currentScene.
=> CAT-FIX Set sceneToPlay to currentScene when leaving the Stage

catroid/src/main/java/org/catrobat/catroid/formulaeditor/Formula.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormulaParser.java
sceneToPlay always has to be used in Formulars because this member
represents the currently playing Scene in the Stage.
=> CAT-FIX Fix wrong scene reference

catroid/build.gradle
The FEATURE_ACCESSIBILITY_SETTINGS_ENABLED flag needs to be removed from the release config.
As from the documentation (http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Building-and-Tasks) values get overridden in the order:
1. assembleCreateatschoolDebug (flavor + build type)
2. assembleDebug / assembleRelease (build type)
3. assembleCreateatschool (flavor)
That's why we have to remove the flag from the release config = 3 (it overwrites the flavor config = 2).
=> CAT-FIX release config

catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/GlideToActionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/WaitActionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/project/ProjectManagerTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/SpriteTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/StartScriptTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/io/StorageHandlerTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/stage/PauseResumeInStageTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/ui/activity/MainMenuActivityTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uitest/util/UiTestUtils.java, catroid/src/main/java/org/catrobat/catroid/content/Look.java, catroid/src/main/java/org/catrobat/catroid/content/Script.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
The paused member was used in the old implementation when we handled the
action execution by threads. A long time ago we switched to libGDX
actions. So there is no need for the member anymore.
The only case where the member is used, is in Look.doTouchDown [1].
However, when pausing the stage, a grey overlay covers the whole stage.
All touch events are captured by this overlay and no stage touch events
are fired.
It's important that no touch events are fired when the stage is paused
for Sprites and TouchUtil.
[1] [Look.java#L164-L166](https://github.com/Catrobat/Catroid/blob/2ce3242fda5f8c020757a9e31fd6d78f111822c5/catroid/src/main/java/org/catrobat/catroid/content/Look.java#L164-L166)
###end-of-commit-message###
Do not ask me what all the pause tests did because the pause/resume logic in …
=> CAT-REF Remove paused member from Script and Sprite

catroid/src/main/java/org/catrobat/catroid/common/LookData.java
Special thanks to inspection `Suspicious variable/parameter name combination`
=> CAT-FIX Fix wrong parameter order height, width when creating thumbnails

catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/LookTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/utils/TestUtils.java, catroid/src/main/java/org/catrobat/catroid/content/Look.java
Consider an image with width 1. Since 0 <= x < width, the value x can
only be 0. When the image is flipped, the x value has to be 0 as well.
Old formula: x = -x + width
New formula: x = (width - 1) - x
width = 1, x = 0
Old formula: -0 + 1 = 1 // Out of bounce!
New formula: (1 - 1) - 0 = 0 // Correct!
The valid x values for an image with width 2 are [0, 1].
width = 2, x = 0
Old formula: -0 + 2 = 2 // Out of bounce!
New formula: (2 - 1) - 0 = 1 // Correct!
width = 2, x = 1
Old formula: -1 + 2 = 1
New formula: (2 - 1) - 1 = 0 // Correct!
=> CAT-FIX Fix touch down on flipped look 1 pixel off

catroid/config/checkstyle.xml, catroid/config/checkstyle_suppressions.xml, catroid/src/main/res/values/strings.xml
The ellipsis character … is much more readable and therefore should be
used in java and xml files instead of `&#8230;`. Translated strings.xml
files are ignored because they are handled by Crowdin.
=> Add checkstyle check to use ellipsis character … instead of &#8230;

catroid/build.gradle
The versionName 0.1.3 causes a failing upload (app version too old) --> There's no need to overwrite the versionName of Pocket Code in the create@school version
=> Fix NOLB-versionName

catroid/src/androidTest/java/org/catrobat/catroid/uitest/ui/activity/PocketMusicTest.java, catroid/src/main/java/org/catrobat/catroid/pocketmusic/PocketMusicActivity.java
When opening up PocketMusicActivity an empty track grid should be provided not the dummy track grid as it used to be.
=> MUS-206 Creating an empty track grid

catroid/src/androidTest/java/org/catrobat/catroid/test/merge/MergeTaskTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/scratchconverter/WebSocketClientTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/utiltests/UtilsTest.java, catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/content/XmlHeader.java, catroid/src/main/java/org/catrobat/catroid/merge/MergeTask.java, catroid/src/main/java/org/catrobat/catroid/ui/MarketingActivity.java, catroid/src/main/java/org/catrobat/catroid/utils/Utils.java, catroid/src/main/res/layout/fragment_scratch_search_projects_list.xml
For a detailed description about the issue, please see the following URL: https://jira.catrob.at/browse/CAT-2149
=> CAT-2149 Fixes remix-data in header of merged programs

catroid/src/main/java/org/catrobat/catroid/content/bricks/FormulaBrick.java, catroid/src/main/java/org/catrobat/catroid/ui/dialogs/UploadProgressDialog.java
Prevent call to RatingDialog when two programs have been uploaded
Prevent xstream-serialization of backpacked data
=> CAT-NOLB RatingDialog & Backpacked data

catroid/src/main/java/org/catrobat/catroid/common/LookData.java, catroid/src/main/java/org/catrobat/catroid/common/SoundInfo.java, catroid/src/main/java/org/catrobat/catroid/common/defaultprojectcreators/DefaultProjectCreatorDefault.java, catroid/src/main/java/org/catrobat/catroid/common/defaultprojectcreators/DefaultProjectCreatorDrone.java, catroid/src/main/java/org/catrobat/catroid/common/defaultprojectcreators/DefaultProjectCreatorPhysics.java, catroid/src/main/java/org/catrobat/catroid/ui/controller/LookController.java, catroid/src/main/java/org/catrobat/catroid/ui/controller/SoundController.java
The name and file name are nearly always set immediately after creating
a LookData or SoundInfo. A parameterized constructor comes in handy to
remove these set calls.
=> CAT-REF Add parameterized constructor to LookData and SoundInfo

catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormula.java
`internFormulaTokenSelection = null` wasn't executed where needed, so FormulaEditor still thought something is highlighted although it wasn't. Added this line and refactored `setCursorPositionAndSelectionAfterInput` to make it a little bit more slim and understandable.
=> CAT-2087 fix for crash related to TRUE and FALSE in conditional brick

catroid/src/androidTest/java/org/catrobat/catroid/test/sensing/CollisionFormulaConversionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/utils/TestUtils.java, catroid/src/main/java/org/catrobat/catroid/ProjectManager.java, catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/content/GroupSprite.java, catroid/src/main/java/org/catrobat/catroid/content/Project.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/Formula.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormula.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormulaParser.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternToExternGenerator.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternToken.java, catroid/src/main/java/org/catrobat/catroid/sensing/CollisionDetection.java, catroid/src/main/java/org/catrobat/catroid/ui/ProgramMenuActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorCategoryListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/SpritesListFragment.java, catroid/src/main/java/org/catrobat/catroid/utils/ImageEditing.java, catroid/src/main/res/values/strings.xml
The wording of the collision formula changed from "object_a touches object_b" to "touches_object(object_b)"
To do this, the CatrobatLanguageVersion is now 0.993f (was 0.992f).
Old projects are converted to the new version when loaded.
This also fixes problems with downloaded programs, which where created by an android device with a different language.
Collision now also works with groups. (returns true if one of the sprites in the group collides)
=> Changing wording of Collision Formula. Fixes CAT-2179, CAT-2180, CAT-2181.

catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormula.java
the "cursorPositionInternTokenIndex" should be set after the "internFormulaTokenSelection" is created.
(was before)
=> CAT-2254 fixes crash in formula editor when adding multiple functions

catroid/src/main/java/org/catrobat/catroid/physics/content/bricks/CollisionReceiverBrick.java
The sprites were taken from the current stage instead of the current scene
=> CAT-2249: fixes selection of sprites in when physical collision with brick

catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/GoNStepsBackActionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/formulaeditor/LookSensorValuesInterpretationTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/formulaeditor/ParserTestObject.java, catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/content/Look.java, catroid/src/main/java/org/catrobat/catroid/content/actions/ComeToFrontAction.java, catroid/src/main/java/org/catrobat/catroid/content/actions/GoNStepsBackAction.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
This is more like a quick fix, with the current implementation it works.
The StageListener sneaks in a PenActor on top of the background layer which caused the offset.
Other bricks which adds actors (display text, etc) put the actor over the Passepartout, which does not cause further Problems.
If we want to have this fix in the release, this is the easiest solution and the way to go.
I'd work on my first approach right after the release to provide a clean solution for that problem.
Since Actor is a LibGDX class and we are using that directly in Z order readout, a refactoring of all types of actors with introduction of an intermediate layer would be needed for a clean solution.
~~//EDIT:~~
~~please put label "Under Discussion" as i still have to adapt the Layer Unit Tests~~
=> CAT-2173 fixed Layer order

catroid/src/main/res/values/strings.xml
Updated Strings for EV3 Move Motor brick to match the naming of the corresponding NXT brick.
Updated formula editor strings for EV3 Sensors to match the naming-standard of all other devices.
=> EV3 Sensor String fixes for release

catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
The undo/redo functions just weren't called when the undo or redo button
was pressed.
To speed up the reviewing process: The changes were just restored from https://github.com/Catrobat/Catroid/commit/22186ad0c#diff-d5336e4f047445d9085f6c015edeb69eL699
=> CAT-2207 Fix Formula Editor history

catroid/src/androidTest/java/org/catrobat/catroid/test/devices/mindstorms/ev3/LegoEV3MotorTest.java
According to the linter the operator | should be on the next line here.
=> Fixes lint issue.

catroid/src/main/java/org/catrobat/catroid/content/Look.java
Calling a method with sprite.look.x() in the Look itself is the same as
calling it directly with x(). All occurrences have been updated.
=> CAT-REF Directly call Look methods in Look

catroid/src/main/java/org/catrobat/catroid/devices/arduino/ArduinoListener.java
Firmata sends a value containg the aggregate status of all pins
of a given port that are configured as input pins. Thus that value
can be in the range of 0-255.
This fixes the problem of always reading low for pin 7 and
additionally fixes problems if multiple pins are set to inputs and
read HIGH (which might result in a value > 64, even without pin 7).
=> CAT-2163 Enable reading Arduino pin 7

catroid/src/main/java/org/catrobat/catroid/physics/content/actions/SetFrictionAction.java, catroid/src/main/java/org/catrobat/catroid/physics/content/bricks/SetFrictionBrick.java
The PhysicsObject.setFriction trims the friction value to the correct
range [1]. All other places are just duplicate code, will lead to
inconsitancy and have been removed.
[1] [PhysicsObject.java#L268-L273](https://github.com/Catrobat/Catroid/blob/b10f22e2bd81e6f7ce70a7a2c68d0add6901c7ab/catroid/src/main/java/org/catrobat/catroid/physics/PhysicsObject.java#L268-L273)
=> CAT-REF Remove duplicate range checks for friction

catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/PointToActionTest.java, catroid/src/main/java/org/catrobat/catroid/content/actions/PointToAction.java
This PR contains two fixes:
* Both Sprite on same position → direction = 90 (previously direction = 0)
* pointedSprite is invalid (e.g. doesn't exist) → don't change direction (previously direction = 0)
Base can also be changed to `release-0.9.28`
=> Fix PointToAction special cases

catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/LookTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/physics/PhysicsLookTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/physics/PhysicsObjectTest.java, catroid/src/main/java/org/catrobat/catroid/content/Look.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/physics/PhysicsLook.java, catroid/src/main/java/org/catrobat/catroid/physics/PhysicsObject.java
When cloning a Sprite in the Stage or in the IDE, values like position,
direction, mass, etc have to be copied as well.
* Clone missing value size in Look. All other values are already cloned.
[1][2]
* Clone all values in PhysicsLook and PhysicsObject
The LookData can't be cloned *in* the Look because each Look has to
refer to its Sprites LookData. It is already correctly cloned in the
Sprite. [2]
[1] https://github.com/Catrobat/Catroid/pull/1972
[2] https://github.com/Catrobat/Catroid/pull/1980
https://jira.catrob.at/browse/CAT-1384
###end-of-commit-message###
Please double-check if all values are copied now.
=> CAT-1384 Copy all Look/PhysicsLook/PhysicsObject values when cloning

catroid/src/androidTest/java/org/catrobat/catroid/test/io/CatroidFieldKeySorterTest.java, catroid/src/main/java/org/catrobat/catroid/io/CatroidFieldKeySorter.java
CAT-FIX XStream sort by annotation with derived classes
Derived classes do not inherit annotations and therefore will always be
sorted alphabetically. The CatroidFieldKeySorter fixes this problem by
searching for the XStreamFieldKeyOrder annotation in the class hierarchy
now. If a derived class adds new members, which aren't specified in a
base class, a XStreamMissingSerializableFieldException is thrown.
This fix currently addresses only the Sprite and its subclasses. The
Sprite specifies a custom field order but the subclasses don't and
therefore the fields were always sorted alphabetically. Now, each
Subclass looks for the XStreamFieldKeyOrder annotation in a base class,
the Sprite, and sorts it accordingly.
The @Inherited would've also solved this problem but is easily forgotten
and …
=> CAT-FIX XStream sort by annotation with derived classes

catroid/src/main/java/org/catrobat/catroid/devices/arduino/ArduinoImpl.java
This PR contains a fix for CAT-2301, based off PRs 2120 and 2121
=> Fix for CAT-2301 Writing a PWM pin doesn't set its pin mode

catroid/gradle/standalone_apk_tasks.gradle
This somehow got messed up during merging. See https://github.com/Catrobat/Catroid/pull/2118
=> CAT-FIX Fix standalone icon and splashscreen

catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
To be compatible with Scratch, the clone is added behind the original
Object. Previously a clone was added to the top. I didn't add a test for
this behavior.
Beware, cloning will change the z-index of the original Look.
=> CAT-2242 Add clone behind origin

catroid/src/main/java/org/catrobat/catroid/ui/fragment/LookFragment.java
The problem was that the condition in the if clause checked the name (string) of the currentSprite. The string name change regarding to the application language (every language has different string.xml) the creator of the programm uses. So if we download a programm written with an english string.xml on the application that uses a german string.xml we have a comparison between e.g. "Background" and "Hintergrund".
So I changed the condition and now we check if the index of the currentSprite is 0. Due to the fact, that the Background sprite is every time in the first place of a programm.
=> CAT-2175 use right url if new background will be added to downloaded programm

catroid/gradle/intellij_config_tasks.gradle
The gradle tasks `gitSkipWorktreeForIntellijConfigFiles` and
`gitNoSkipWorktreeForIntellijConfigFiles` use a list now to update the
affected files. Furthermore the tasks use the _Task.doLast(Action)_ rather
than _Task.leftShift(Closure)_ as the latter is deprecated and will be
removed in Gradle 5.0, see [gradle doc](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#sec:build_scripts_are_code)
Furthermore the tasks `gitSaveStashSwitchingToOldBranch ` and `gitApplyStashSwitchingToOldBranch ` have been removed due to reasons explained in [CAT-2258](https://jira.catrob.at/browse/CAT-2258?focusedCommentId=19986&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19986)
=> CAT-2258 Clean up gradle task for IntelliJ files

catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java, catroid/src/main/res/values/strings.xml
Social sharing via the WhatsApp button on details page in the webview crashes PocketCode when WhatsApp is not installed on the phone.
*Added code to check WhatsApp installation before starting the share intent.
=> CAT-2151 Fixed crash when whatsapp not installed

catroid/src/main/java/org/catrobat/catroid/common/LookData.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
Overloaded the LookData's clone function and Sprite's cloneLooks function so it would take a boolean flag that specifies if the usage counter should be increased.
Called the overloaded function in cloneForCloneBrick function.
Did some minor refactoring (LookData equals method, Sprite createWhenScriptActionSequence and getBricksRequiringResource method).
=> CAT-2162 Cloning a sprite should not increase the usage counter (FileChecksumContainer)

catroid/src/main/java/org/catrobat/catroid/content/Look.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/content/actions/RepeatAction.java, catroid/src/main/java/org/catrobat/catroid/content/actions/StopAllScriptsAction.java
Added a nullcheck to RepeatAction (because it would run into null pointer when an action is reset).
Added a method to Look, that resets all broadcast- and when-scripts to what they were before running the "stop all scripts" block. Before that, stop all scripts would result in none of the scripts working anymore.
=> CAT-2169 Stop All Scripts Bugs

catroid/src/main/java/org/catrobat/catroid/content/Project.java, catroid/src/main/java/org/catrobat/catroid/content/Scene.java, catroid/src/main/java/org/catrobat/catroid/merge/MergeTask.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/ScriptFragment.java
Before this change there were issues with broadcast messages that were used in one scene, but not in the other. The reason for this was that all broadcast messages not used in scene 1 were simply removed (when pausing scene 1's ScriptFragment) leaving scene 2 with invalid broadcast messages used in its scripts. (for further consequences see the ticket)
Added removeUnusedBroadcastMessages() to **Project** to remove all broadcast messages that are not used in any of the scenes.
Added addUsedMessagesToList(...) to **Scene** to add all used messages to a given list and removed removeUnusedBroadcastMessages().
Replaced call to scene.removeUnusedBroadcastMessages() with call to project.removeUnusedBroadcastMessages() in **MergeTask** and moved the new call to a different position (where the …
=> CAT-2353 Broadcast messages are only removed if they don't exist in any scene of a project

catroid/src/androidTest/java/org/catrobat/catroid/test/utiltests/ImageEditingTest.java, catroid/src/main/java/org/catrobat/catroid/io/ProjectAndSceneScreenshotLoader.java, catroid/src/main/java/org/catrobat/catroid/transfers/ProjectUploadService.java, catroid/src/main/java/org/catrobat/catroid/ui/dialogs/UploadProgressDialog.java, catroid/src/main/java/org/catrobat/catroid/utils/ImageEditing.java, catroid/src/main/java/org/catrobat/catroid/utils/StatusBarNotificationManager.java, catroid/src/main/java/org/catrobat/catroid/utils/UtilFile.java
To get all screenshots we need to know which scenes the project has (screenshots are in their scenes' respective folders) - therefore we pass an array of scene names to the ProjectUploadService and scale all images accordingly. The scaling method had to be adjusted, because it didn't provide scaling to a specific width/height. Also the justScaleDown feature of getScaledBitmapFromPath(...) was implemented as the flag was previously passed without doing anything.
**ProjectAndSceneScreenshotLoader**: Made getScreenshotFile(...) method of inner class ScreenshotLoader accessible to public. This method is needed for retrieving the screenshot Files by their project and scene name.
**ProjectUploadService**: Retrieve an array of scene names from the intent, loop through all the scene names and get …
=> CAT-1152 Reduce size of screenshots

catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormulaParser.java
Parsing only happens when editing a Formula through the
FormulaEditorFragment in the UI. So the InternFormulaParser uses
getCurrentScene only for now on.
Normally you can use getCurrentScene or getSceneToPlay in the UI. Both
are always refering to the same Scene Object when in the UI. However,
for correctness getCurrentScene is used because it represents the
currently opened Scene.
=> CAT-FIX Use getCurrentScene in InternFormulaParser

catroid/build.gradle, catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/ThinkSayBubbleActionTest.java, catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java, catroid/src/main/java/org/catrobat/catroid/content/actions/ThinkSayBubbleAction.java, catroid/src/main/java/org/catrobat/catroid/content/actions/WaitForBubbleBrickAction.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/Brick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ThinkBubbleBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ThinkForBubbleBrick.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormulaParser.java, catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java, catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
This is the second pull request for this issue, as I could not reopen the other one (https://github.com/Catrobat/Catroid/pull/2256) after force pushing.
I had to make quite a few changes to the code to make it testable, so please bear with me ;)
Added **ThinkSayBubbleActionTest** testing new behaviour (bubble disappears if ThinkSayBubble with text "" is created)
**ThinkSayBubbleAction**: moved BubbleActor creation to seperate method (for better testability); moved some code concerning adding/removing BubbleActors to StageListener
**WaitForBubbleBrickAction**:  moved some code concerning adding/removing BubbleActors to StageListener
**Brick**: added a new array that contains all BrickFields that expect a string value & a method that returns a boolean value if a field expects a string value …
=> CAT-2250 Don't display a think/say bubble when the text equals ""

catroid/src/androidTest/java/org/catrobat/catroid/test/formulaeditor/ParserTestOperators.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
CAT-2270 Evaluating -0 = 0 to True 
Earlier -0 and 0 evaluates to False (-0 = 0 is False) and now after the correction -0 and 0 evaluates to True (-0 = 0 is True).
Note: This pull request also includes test file.
=> CAT-2270 Correcting the negative zero(-0) and positive zero(0) evaluation

catroid/build.gradle, catroid/google-services-template.json, catroid/src/main/AndroidManifest.xml
Standalone APKs are allowed to be installed without affecting the
current Pocket Code installation.
This is useful for testers to have different versions installed in parallel.
Automating this process (https://confluence.catrob.at/x/KoGT) makes it more
accessible and allows Jenkins to provide such standalone APKs.
./gradlew -Pindependent assembleDebug
The created catroid-catroid-debug.apk file has an internal application name
that depends on the current date and time.
The user displayed label is of the form "Code MMdd HH:mm" in UTC.
Alternatively you can provide an application name yourself:
./gradlew -Pindependent="Code Design Nr 2" assembleDebug
The application name and the package name are stored as placeholders in
android manifest and also in the google-services-template.json. …
=> CAT-2400 Automatize the creation of standalone APKs.

catroid/src/main/java/org/catrobat/catroid/common/LookData.java, catroid/src/main/java/org/catrobat/catroid/common/SoundInfo.java, catroid/src/main/java/org/catrobat/catroid/ui/adapter/LookAdapter.java, catroid/src/main/java/org/catrobat/catroid/ui/adapter/SoundAdapter.java
Removes the member 'name/title' from the **hashCode** function of **LookData** and **SoundInfo**.
Reason: LookData & SoundInfo are used as keys in a HashMap. 
If the hash changes when renaming a look or a sound, we will not be able to find the object in the HashMap.
This resulted in a NPE for renaming a sound. There was a workaround in place for renaming a Look - it has now been replaced with a proper solution (not changing the hash value of the object).
This is not an issue for Sprites, Scenes, Project or NfcTags, as their hashcode function is not overridden or does not include their names.
Very minor cosmetic changes.
=> [CAT-2099] Fix crash when Sound/Look is renamed

catroid/src/androidTest/java/org/catrobat/catroid/test/ui/BaseExceptionHandlerTest.java, catroid/src/main/java/org/catrobat/catroid/ui/BaseExceptionHandler.java
This pull request includes the implementation of test to check if an exception is stored in CrashReporter after uncaughtException.
=> CAT-2466 Test for BaseExceptionHandler.uncaughtException

catroid/src/main/java/org/catrobat/catroid/ui/SettingsActivity.java
This pull request includes an updated settings file where the settings option for enabling/disabling CrashReporter will be disabled if flag (CRASHLYTICS_CRASH_REPORT_ENABLED) is disabled.
=> CAT-2489 Hiding CrashReporter Setting on flag disabled

catroid/build.gradle
Earlier the flag CRASHLYTICS_CRASH_REPORT_ENABLED was set to false in
debug mode. In SettingsActivity the checkbox button (which
enables/disables the Crashlytics crash reporting) is either visible or
hidden depending upon the flag value (visible if true and hidden if
false).
As the checkbox was hidden (hidden for false), it resulted in failure of
different espresso test cases where checkbox was required to perform the
UI test. Moreover, espresso testrun is green because the auto-generated
AllEspressoTestsSuite.java file isn't up-to-date and doesn't contain the
SettingsActivityTest.
=> CAT-FIX Set Crashlytics flag to True in debug mode

catroid/src/androidTest/java/org/catrobat/catroid/test/ui/BaseExceptionHandlerTest.java, catroid/src/main/java/org/catrobat/catroid/ui/BaseActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/BaseExceptionHandler.java
When the app crashes, the RECOVERED_FROM_CRASH flag has to be set to
true and then every Activity is finished until the app is back in the
MainMenuActivity. If the RECOVERED_FROM_CRASH flag is not set, the app
will go into an infinite loop, where it tries to start an activity over
and over again because the activity crashes but never finises. The
problem was only reproducible in specific activities, e.g. when throwing
an exception in ScriptActivity.create.
Setting the RECOVERED_FROM_CRASH flag to true when the app crashes fixes
the infinite loop. It has been unintentionally removed during improving
the Crash Reporter[1].
[1] https://github.com/Catrobat/Catroid/pull/2366/files#diff-d61e5ef6cdb376657aae60af754655d0L136
=> CAT-FIX Fix infinite loop when app crashes

catroid/src/main/java/org/catrobat/catroid/ui/adapter/LookAdapter.java
This section was removed in #2352 
Although it's ugly code, it had the purpose of fixing a crash when returning to Pocket Code after a look was edited in Pocket Paint.
I'd keep this for now, as the Adapters will be refactored anyway.
=> Revert changes which broke Pocket Paint editing

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/testsuites/PullRequestTriggerSuite.java
that excludes upcoming sensor hardware test box tests, and other
tests that require additional hardware or permission action by user.
=> CAT-FIX Add dedicated PullRequestTrigger test suite

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/stage/BroadcastReceiverRegressionTest.java, catroid/src/main/java/org/catrobat/catroid/common/BroadcastSequenceMap.java
The bug appeared when there were multiple receive broadcast bricks with the same broadcast message in the same sprite.
The list of actions was overriden, instead of of being extended, so only the script of the last added receive brick was executed.
=> fixed receiving the same broadcast multiple times

catroid/src/androidTest/java/org/catrobat/catroid/test/utils/CrashReporterTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/utils/SettingsActivityCrashReporterTest.java, catroid/src/main/java/org/catrobat/catroid/ui/SettingsActivity.java, catroid/src/main/java/org/catrobat/catroid/utils/CrashReporter.java, catroid/src/main/java/org/catrobat/catroid/utils/CrashReporterInterface.java, catroid/src/main/java/org/catrobat/catroid/utils/CrashlyticsCrashReporter.java
This pull request includes the test file for settings activity which tests the enable and disable functionality of Crash Report system.
=> CAT-2468 Testing that the CrashReporter is initialized when enabled through settings

catroid/src/androidTest/java/org/catrobat/catroid/test/utils/CrashReporterTest.java
Tests for CrashReporter's sendUnhandledCaughtException is added.
=> CAT-FIX Added test for sending unhandled caught exception

catroid/build.gradle
Cloud messaging is currently not ready to be enabled in releases.
=> CAT-FIX Disable Cloud Messaging in releases

catroid/build.gradle, catroid/src/androidTest/java/org/catrobat/catroid/test/utils/CrashReporterTest.java
org.mockito.runners.MockitoJUnitRunner is now deprecated, so replaced it
with org.mockito.junit.MockitoJUnitRunner. 
Note:- 
org.mockito:mockito-core:1.10.19 is upgraded to org.mockito:mockito-core:2.8.47
com.linkedin.dexmaker:dexmaker-mockito:1.5.1 is upgraded to com.linkedin.dexmaker:dexmaker-mockito:2.2.0
=> CAT-FIX Updated MockitoJUnitRunner In CrashReporterTest

catroid/src/androidTest/java/org/catrobat/catroid/test/cloudmessaging/CloudMessagingTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/cloudmessaging/SettingsActivityCloudNotificationTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/SettingsActivityTest.java, catroid/src/main/java/org/catrobat/catroid/CatroidApplication.java, catroid/src/main/java/org/catrobat/catroid/cloudmessaging/CloudMessaging.java, catroid/src/main/java/org/catrobat/catroid/cloudmessaging/CloudMessagingInterface.java, catroid/src/main/java/org/catrobat/catroid/cloudmessaging/FirebaseCloudMessaging.java, catroid/src/main/java/org/catrobat/catroid/ui/SettingsActivity.java, catroid/src/main/res/values/strings.xml, catroid/src/main/res/xml/preferences.xml
Added the feature for enabling/disabling the notifications through settings. It uses the firebase cloud messaging's topics subscribe/unsubscribe feature to enable/disable notifications.
Note: This PR also includes the test file.
=> CAT-2473 Setting for enable disable cloud notifications

catroid/src/androidTest/java/org/catrobat/catroid/test/common/LookDataTest.java, catroid/src/main/java/org/catrobat/catroid/common/LookData.java
Disposing the LookDatas pixmap value first and then assigning it to null
value.
=> CAT-2372 Dispose LookDatas Pixmap Correctly

catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
progressDialog.show() was throwing an exception on activity finished.
Error URL:
https://console.firebase.google.com/u/0/project/firebase-catrobat/monitoring/app/android:org.catrobat.catroid/cluster/e0c21001
=> CAT-FIX ProgressDialog Error On Activity Finished

catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddBrickFragment.java
This resulted in copied bricks being inserted into the wrong script.
https://jira.catrob.at/browse/CAT-1398
=> CAT-1398 Fix currentScript being set to the wrong script

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/testsuites/AllEspressoTestsSuite.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/LanguageSwitchMainMenuTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/RtlUiTestUtils.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/SettingsActivityTest.java, catroid/src/main/java/org/catrobat/catroid/CatroidApplication.java, catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/ui/SettingsActivity.java, catroid/src/main/res/values/strings.xml, catroid/src/main/res/xml/preferences.xml
The app must provide an interface that handles user input to switch languages independent of the smartphone’s global settings. This feature should list all languages supported by the app including languages not yet supported by the operating system.
=> CAT-2345 Multilingual Feature on Application Level

catroid/src/androidTest/java/org/catrobat/catroid/test/utiltests/UtilFileTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/testsuites/AllEspressoTestsSuite.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/ArabicStringAsSizeUnitLooksTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/ArabicStringAsSizeUnitSoundsTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/ArabicTextAsSizeUnitMyProjectActivityTest.java, catroid/src/main/java/org/catrobat/catroid/ui/adapter/LookListAdapter.java, catroid/src/main/java/org/catrobat/catroid/ui/adapter/ProjectListAdapter.java, catroid/src/main/java/org/catrobat/catroid/ui/adapter/SoundListAdapter.java, catroid/src/main/java/org/catrobat/catroid/ui/controller/LookController.java, catroid/src/main/java/org/catrobat/catroid/ui/controller/SoundController.java, catroid/src/main/java/org/catrobat/catroid/ui/dialogs/UploadProjectDialog.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/ShowDetailsFragment.java, catroid/src/main/java/org/catrobat/catroid/utils/UtilFile.java, catroid/src/main/res/values-ar/strings.xml, catroid/src/main/res/values/strings.xml
In the course of localizing software, all strings should be declared as resources and separated from the source code. In Pocket Code, program size is expressed in units of measurement (KB, MB, GB, etc.), these units are implemented as a hard-coded string.
=> CAT-2355 Removing Hard-Coding String

catroid/build.gradle, catroid/google-services.json, catroid/src/main/AndroidManifest.xml
This reverts commit f78114277b7d82a529bf2e1e0f4e481c9cde09fd.
Adding the JumpingSumo Drone Support collides with the initial commit.
Even worse: This commit broke the standalone APK creation.
Thus the most sensible way is to revert it and find a better solution.
More details are outlined at CAT-2400.
=> Revert "CAT-2400 Automatize the creation of independent APKs."

catroid/src/androidTest/java/org/catrobat/catroid/test/formulaeditor/ParserTestUserLists.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
To be Scratch compatible, an empty list evaluates to an empty string "".
Previously was 0.0.
=> CAT-2558 Evaluate empty list to empty string ""

catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
Fixes CAT-2573 by using the [Scratch random function implementation](https://github.com/LLK/scratch-vm/blob/c807f02e37b4746bc503929ae10059de5baa5105/src/blocks/scratch3_operators.js#L80-L91) to
generate random numbers within a specific range.
___
I manually tested it with `[0,1], [0,10], [1,10], [-1,1], [-1.5,1.5], [0, 10.0]`. Please test it as well.
JFI: If you use e.g. `10.0`, the random value will be a double with decimal places, whereas using `10` will result in integers.
=> CAT-2573 Use Scratch random function

catroid/build.gradle
If one of the native libs is loaded for arm64-v8a, the app expects all libs to be available for that architecture. Only some libs were available (from the parrot sdk) - the app crashed when looking for libgdx.so.
This way 32bit libs are used on 64 bit devices. 
This is a quick fix - to support 64 bit, we need to include the remaining native libs for 64 bit architecture.
=> [CAT-2571] Exclude native libs with arm64-v8a architecture 

catroid/src/main/java/org/catrobat/catroid/content/BroadcastHandler.java, catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
When clones were removed, their corresponding entries in the ScriptSprite map were not removed up until now (due to incorrect usage of Map.remove(...)). 
This pull requests now removes those entries, fixing a minor memory leak.
=> [CAT-2366] Remove script-sprite pair from script-sprite-map when removing cloned sprites

catroid/src/main/java/org/catrobat/catroid/ui/fragment/SoundFragment.java
Setting the soundName in addSoundChooseFile() is unnecessary and may lead to a crash --> it will be set in onActivityResult correctly after a sound has been choosen.
=> CAT-2203 Fix crash when adding a sound from file system

catroid/src/main/java/org/catrobat/catroid/utils/CrashReporter.java
**Issue**
The app crashes when opening some projects like:
https://share.catrob.at/pocketcode/program/40654
https://share.catrob.at/pocketcode/program/26670
but only on first application startup.
**Explanation**
This happens because Crashlytics is disabled per default -> therefore it is not initialized.
However in onCreate of MainMenuActivity Crashlytics is enabled by writing R.xml.preferences to the SharedPreferences.
When a crash occurs, the app thinks Crashlytics is enabled (because the SharedPreferences say so) and tries to log with it. This results in a crash because it isn't initialized.
**Solution**
If no SharedPreference is set for Crashlytics yet, we assume true so that it will be initialized. (On first startup it  (= the shared preference) will be initialized to true by onCreate …
=> CAT-FIX Crash when opening project on first app startup

catroid/src/main/java/org/catrobat/catroid/io/XStreamBrickConverter.java
It only make sense to report an exception, if the brick can't be found
in any of the packages containing bricks.
=> Only report exception if brick can't be found during loading program

catroid/src/main/java/org/catrobat/catroid/ui/dialogs/FormulaEditorComputeDialog.java
This was pure luck that this has ever worked correctly.
The height of the computeTextView was calculated wrong.
First the height in px was calculated (heightPixels). 
Then the heightPixels were divided by 2 (whyever someone wants to do this) and converted from dp to pixel with TypedValue.applyDimension(...)
In other words: The pixels were converted into pixels.
I removed this calculation and just used the heightPixels as TextView height and added a height margin (50% of calculated line height) to it so it looks better.
=> CAT-2625 Fix computeTextView height bug

catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
Instead of starting a new main menu activity, the onBackPressed() method from the Activity class is called.
Also renamed the callMainMenu to allowGoBack.
=> CAT-2611 fixed switch back to last activity on icon press

catroid/src/main/java/org/catrobat/catroid/ui/fragment/CheckBoxListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/ListActivityFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/LookFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/NfcTagFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/SceneListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/SoundFragment.java
There were two issues why this did not work.
1. The actionModeTitle was not set correctly. thats why a null pointer exception is thrown on actionModeTitle.length()
2. The CHOICE_MODE_SINGLE is not handled correctly in the CheckBoxListFragment. The isRenameActionMode was implemented in a very dirty way, even tho this variable is not necessary. The updateActionModeTitle() should not be called if the "SelectMode" equals CHOICE_MODE_SINGLE, because there is nothing to update if the "SelectMode" equals CHOICE_MODE_SINGLE.
I removed the isRenameActionMode, because "if(getSelectMode() == ListView.CHOICE_MODE_SINGLE)" should be used instead of "if(isRenameActionMode)"
isRenameActionMode is removed everywhere, except in the SpritesListFragment, because it seems to be necessary there.
=> CAT-2350 Fixed "Rename Program" bug

catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
* The minSDKVersion is 17. Checking for e.g. HONEYCOMB (version 11) is not
necessary anymore.
* Fixes lint warning _WrongConstant_
=> CAT-FIX Update outdated OS version code

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/DeleteItemOfUserListBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/ReplaceItemInUserListTest.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/AddItemToUserListBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ChangeVariableBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/DeleteItemOfUserListBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/InsertItemIntoUserListBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ReplaceItemInUserListBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/SetVariableBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/UserListBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/UserVariableBrick.java
Fix spinner selection for UserListBricks and UserVariableBricks, by switching the order of if statements in both classes.
Refactor UserListBricks to use the same Touch / ItemSelected-Listeners.
Fix corresponding tests.
=> CAT-2359 Fix UserListBrick/UserVariableBrick keeping old index selected when adding new list/variable

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/WhenBrickTest.java
Created a mapping between brick classes and brick ressource ids.
Add all bricks ressource ids, which should be tested, to a list.
For each ressource id in the list a drag and drop test is performed.
Try to drag and drop when bricks (should not be possible).
=> CAT-2595 WhenBrickTest rewritten from Robotium to Espresso

catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormula.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternToken.java, catroid/src/main/java/org/catrobat/catroid/ui/dialogs/RenameVariableDialog.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
The problem was that the FormulaEditorEditText field is not getting updated after renaming variables or lists.
All tokens inside the InternFormula are changed which share the same name as the renamed variable (before renaming)
Inside the RenameVariableDialog the updateVariableReferences(...) or updateListReferences(...) is called, which updates all tokens inside the InternFormula object.
=> CAT-2083 Fixed rename variables bug

catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
A Sprite created through the CloneBrick action, is correctly created
but it is never added to the Sprite List in the ProjectManager Class.
When the draw function of the PenActor Class is called to perform the
Pen Brick actions it looks through the List of Sprites in the
ProjectManager Class, and performs the necessary actions according to
the values of the PenConfiguration Flags of every Sprite in the List.
Since the Cloned Sprite is not in the List, no Pen actions are
performed for it. To resolve this issue the Cloned sprite is added to
the Sprite List of the ProjectManager Class. This way when the draw
function is called, the the Cloned Sprite is also found in the List and
the necessary Pen Brick actions(PenUP/down/Stamp..) are Performed.
=> CAT-2524 Pen bricks should also work for clones

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorRenameVariableTest.java
This tests the issue reported in [CAT-2083](https://jira.catrob.at/browse/CAT-2083).
The user variable is created/renamed and checked if it was also renamed in the FormulaEditorEditTextView
=> CAT-2643 Implement FormulaEditorRenameVariableTest

Jenkinsfile
Due to the updates to gradle (commit 5ea8847) the path to the APKs changed.
- 'build/outputs/apk/catroid-catroid-debug.apk' to 'build/outputs/apk/catroid/debug/catroid-catroid-debug.apk'
- 'build/outputs/apk/catroid-standalone-debug.apk' to 'build/outputs/apk/standalone/debug/catroid-standalone-debug.apk'
=> [Build] Respect new locations of APKs due to gradle update

catroid/src/androidTest/java/org/catrobat/catroid/test/utils/CrashReporterTest.java, catroid/src/main/java/org/catrobat/catroid/ui/BaseActivity.java, catroid/src/main/java/org/catrobat/catroid/utils/CrashReporter.java
Just renaming, improving log output, access modifiers and splitting code
into methods.
___
Wanted to do this a long time ago :wink: I tested it with a custom Crashlytics project.
Automatically reported
* http://crashes.to/s/781a6e78c2c
* http://crashes.to/s/198ca0651ac
Manually reported
* http://crashes.to/s/ce230838cf1
I don't know why these public reports don't show a stacktrace. Maybe they will later…
All crash reports will show a stacktrace once logged in.
=> CAT-REF Clean up CrashReporter

Jenkinsfile
Run build inside docker container for better isolation of PR builds.
Removed the parallelism due to additional wait times, as the SDK needed to be updated on all slaves.
=> JENKINS-101: Run build inside a docker container

catroid/src/main/java/org/catrobat/catroid/io/StorageHandler.java
The unused member "userVariableName" has been removed from ShowTextBrick
and HideTextBrick in commit 20638ec4f. Loading older programs (Catrobat
language <= 0.991) which stored this member in the code.xml will crash
on load.
Omiting the member in XStream fixes the crash.
=> CAT-2671 Fix Show/HideTextBrick not backward compatible

Jenkinsfile, buildScripts/log_parser_rules, catroid/build.gradle, catroid/gradle/code_quality_tasks.gradle
Currently the static analysis run fails if there are PMD/Checkstyle issues. Therefore the whole build stops after the static analysis. The build should be marked as unstable (already done but superseded by the error) but continue.
The emulator tests should also pass, if an error occurs. As gradle does not differ between failures of a single test or eg an emulator crash the parsing rules got introduces to mark the build erroneous if a problem occurs (needs to be updated if needed).
=> Failed tests should not fail gradle run

catroid/src/main/java/org/catrobat/catroid/content/bricks/PlaySoundAndWaitBrick.java
With the int division the calculated duration was very inaccurate.
=> CAT-2729 Replace integer division with float division in PlaySoundAndWaitBrick

Jenkinsfile, catroid/build.gradle, catroid/gradle/android_tasks.gradle, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/pocketmusic/PocketMusicActivityTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/AboutDialogTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/SystemAnimations.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/rules/BaseActivityInstrumentationRule.java, catroid/src/main/AndroidManifest.xml
For UI-Tests the animations shall be disabled, currently this was done programmatically, but the approach was broken.
For now the animations are disabled on emulator startup and are programmatically switched on again for PocketMusicActivityTest, because it highly depends on animations.
In the future (for Oreo and later and when PocketMusicActivityTest does not need animations for the tests) this can be done via testOptions.disableAnimations and all other code can be removed.
=> CAT-2732: Testing: Disable animations via emulator

catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/EventActionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/ForeverActionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/IfLogicActionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/RepeatActionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/RepeatUntilActionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/StopScriptActionsTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/WaitUntilActionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/script/StartScriptTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/script/WhenBackgroundChangesScriptTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/script/WhenConditionScriptTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/script/WhenScriptTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/script/WhenTouchDownScriptTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/physics/PhysicsCollisionBetweenTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/physics/actions/IfOnEdgeBouncePhysicsActionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/WhenGamepadButtonBrickTest.java, catroid/src/main/java/org/catrobat/catroid/cast/CastManager.java, catroid/src/main/java/org/catrobat/catroid/common/ActionScheduler.java, catroid/src/main/java/org/catrobat/catroid/content/Look.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/content/StartScript.java, catroid/src/main/java/org/catrobat/catroid/content/WhenClonedScript.java, catroid/src/main/java/org/catrobat/catroid/content/WhenGamepadButtonScript.java, catroid/src/main/java/org/catrobat/catroid/content/WhenNfcScript.java, catroid/src/main/java/org/catrobat/catroid/content/actions/StopAllScriptsAction.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenGamepadButtonBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenNfcBrick.java, catroid/src/main/java/org/catrobat/catroid/content/eventids/GamepadEventId.java, catroid/src/main/java/org/catrobat/catroid/content/eventids/NfcEventId.java, catroid/src/main/java/org/catrobat/catroid/nfc/NfcHandler.java, catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
- Let StartScript, WhenClonedScript, WhenGamepadButtonScript and
WhenNfcScript implement EventScript and create corresponding EventIds
- Fire Start event at the beginning of the stage
- Fire Clone event when cloning of a sprite is done
- Fire Nfc event and GamepadEvent at the appropriate places
- Refactor WhenGamepadButtonBrick and CastManager (minor)
- Remove old methods for action creation from Sprite
=> CAT-2730 Refactor WhenStartedBrick, WhenClonedBrick, WhenNfcBrick and WhenGamepadButtonBrick to use the new event system

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/annotations/FlakyTestTest.java
Convert test for FlakyTest-annotation to non-flaky itself by not relying on a random number.
Instead use a simple static variable and let the test fail for the defined number of times.
With the random number it can still be the case, that the test fails.
=> CAT-2736 Convert test for FlakyTest-annotation to non-flaky itself

.gitignore, Jenkinsfile, buildScripts/build_helper_functions.py, buildScripts/build_helper_run_tests_on_emulator, buildScripts/build_helper_stop_emulator, buildScripts/build_step_create_independent_apk, buildScripts/build_step_create_standalone_apk, buildScripts/build_step_install_android_sdk, buildScripts/build_step_run_static_analysis, buildScripts/build_step_run_tests_on_emulator__pr_test_suite, buildScripts/build_step_run_tests_on_emulator__test_pkg, buildScripts/emulator_config.ini, buildScripts/jenkins-android-helper/LICENSE, buildScripts/jenkins-android-helper/README, buildScripts/jenkins-android-helper/android_emulator_helper_functions.py, buildScripts/jenkins-android-helper/ini_helper_functions.py, buildScripts/jenkins-android-helper/jenkins_android_cmd_wrapper, buildScripts/jenkins-android-helper/jenkins_android_emulator_helper, buildScripts/jenkins-android-helper/jenkins_android_helper_commons.py, buildScripts/jenkins-android-helper/jenkins_android_sdk.py, buildScripts/jenkins-android-helper/jenkins_android_sdk_installer
The developer needs to be easily able to run the same build steps on the dev machine like they are run on Jenkins. This requirement includes using the same emulator setting and the same build options like Jenkins.
Therefore the logic of the build steps from the Jenkinsfile is moved to separate script per step ( `buildScripts/build_*`-scripts). Those scripts are capable of running inside a Jenkins build and on a local developer machine. The script are intended to work on Linux/Mac/Windows.
The scripts take care of creating and starting the emulator. The AVD to use can be configured via the `buildScripts/emulator_config.ini`-file.
To avoid external dependencies the Jenkins-Android-Helper: https://github.com/redeamer/jenkins-android-helper (used to handle the SDK installation and the …
=> Move build steps to scripts, which run on Jenkins like on the local machine

Jenkinsfile, docker/Dockerfile.jenkins
This removes external dependencies and the need of an own docker-hub account.
As all the build-scripts are now reside inside of the repository, the Dockerfile is simply the jdk-8 image with python and lsof installed for the buildScripts and a hook that the Jenkins-User is added to avoid problems with programs which rely on an existing user (eg ssh-agent).
=> [JENKINS-194] Add Dockerfile for building to repository

catroid/src/main/java/org/catrobat/catroid/ui/fragment/ScriptFragment.java
-scroll position of brick list view is retained when
navigating to formula editor and back
=> CAT-FIX retain scroll position of brick list when changing fragments

catroid/src/main/java/org/catrobat/catroid/common/LookData.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.java
paint.
- whenever the user edited a look via pocket paint the thumbnail was not
refreshed, because the Bitmap was cached in the LookData.
+ now image data is invalidated (set to null) before the intent to
pocket paint is called -> this causes some unnecesary recalculations of
the bitmap (e.g whenever pocket paint is called and exited without
changes) but it still is a minimally invasive fix.
=> [FIX] Invalidated outdated thumbnails for LookData after edits with

catroid/src/main/java/org/catrobat/catroid/CatroidApplication.java
Just reordering code and removing unused code.
The parrot (drone) ApplicationSettings is initialized but never used.
Looking at the source code[1], initilaizing doesn't affect anything else
(e.g. static variables). So the ApplicationSettings variable has been
removed.
[1] https://github.com/kbogert/ardrone/blob/f9a6685530e9dcb4c466ac52601d036b0262a6e3/Examples/Android/trunk/FreeFlight2/src/com/parrot/freeflight/settings/ApplicationSettings.java#L66-L72
=> Small clean ups

catroid/src/main/java/org/catrobat/catroid/transfers/GooglePlusLoginHandler.java
-prevent status code SIGN_IN_CURRENTLY_IN_PROGRESS from showing
error message
=> CAT-FIX Handle google login 'in progress' status code

catroid/src/main/java/org/catrobat/catroid/ui/SignInActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java, catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
When the device is not connected to a network,
ConnectivityManager.getActiveNetworkInfo will return null which will
result in a NullPointerException. Added null checks to prevent this
crash.
There is a small behavior change when an error occurs in the WebView.
Previously, the additional info '…Check your Internet connection.' was
only shown if the device is not connected to a network. Now the info is
also shown if the device is connecting to a network. IMO and in this
case, the difference is almost non-existent. Also, if the device is
connecting to a network, it doesn't mean it will get a connection. So
showing the additional info in both cases is fine.
=> CAT-FIX Fix crash when not connected to a network

Jenkinsfile, Jenkinsfile.PullRequest, buildScripts/build_helper_run_tests_on_emulator, buildScripts/build_helper_run_unit_tests, buildScripts/build_step_run_unit_tests__all_tests
Currently the unit-tests automatically started when device/emulator tests are running. As for a PR two different device tests are started (different sets of classes), the unit tests would also run multiple times.
Therefore move the local unit test call to a separate build step.
Additionally call the tests only for the catroid debug suite. To avoid even more duplications of the unit test results.
=> JENKINS-221: Do not run Unit-test multiple times

catroid/src/main/java/org/catrobat/catroid/ProjectManager.java, catroid/src/main/java/org/catrobat/catroid/content/CollisionScript.java
How to reproduce the error
* Download https://share.catrob.at/pocketcode/program/28126
* Open and immediately press run (don't go in any script view)
* Press the ball. You can move the Players by touch down and move them.
--
* Instead of normally bouncing of, the ball moves around and behind the player.
The problem is, [`CollisionScript`](https://github.com/Catrobat/Catroid/blob/develop/catroid/src/main/java/org/catrobat/catroid/content/CollisionScript.java) has two members
```java
private String spriteToCollideWithName;
private transient Sprite spriteToCollideWith;
```
where only the name is serialized. When deserializing, only the name is deserialized and the Sprite itself will remain null which is equal to 'collide with anything'. When opening the Sprites Script View (maybe scroll to …
=> [Under discussion] Hotfix for CollisionScript references not set correctly

buildScripts/jenkins-android-helper/jenkins_android_sdk.py, catroid/build.gradle
* Exclude MIPS architecture binary files from builds
- MIPS support has been removed from NDK >= 17, builds will fail if you have NDK installed as it tries to strip the MIPS binaries
---
* ~~Remove some unused files (eclipse configuration files, outdated gradle files in a wrong folder)~~
- Moved to #2913
* ~~Migrate the build.gradle file to gradle >= 3.0.0 according to this guideline: https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration~~
- Moved to #2914
=> [GSoC18] Remove MIPS

catroid/src/main/java/org/catrobat/catroid/content/Scene.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/LookController.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SceneController.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SoundController.java
- this also fixes the Backpack in general: i.e.
comparison of objects with File references were broken, after
refactoring, this now re-introduces comparison by checksum
to verify if two images have same content instead of same
path only.
- when unpacking a Scene that contains a SpinnerBricks
a crash occured because the Spinner selection and the Object reference
are not synchronized.
- this is ONLY a hotfix. it prevents the crash, but does not correctly
set up the references. this will be fixed during Spinner refactoring.
=> [HotFix] Fixed Crash when Unpacking Scene

build.gradle, catroid/build.gradle
* Migrate the build.gradle file to gradle >= 3.0.0 according to this guideline: https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration
* The Firebase plugin still uses the `compile` command, this can be fixed
by upgrading to firebase >= 4.0.0 but has other implications on the build process
=> [GSOC18] Migrate build.gradle to gradle >=3.0.0

catroid/src/main/java/org/catrobat/catroid/io/StorageOperations.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/NewLookDialogFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/NewSoundDialogFragment.java
- fixed crash when importing images or sounds from
any file browser.
- looks and sounds now have a default name instead
of filename.
=> CATROID-38 Fixed Crash when importing from Storage

catroid/build.gradle, catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenBackgroundChangesBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenNfcBrick.java, catroid/src/main/java/org/catrobat/catroid/ui/ScratchProgramDetailsActivity.java
* Replace `espresso-core` dependency with `espresso-idling-resource`
* Why: `espresso-core` should not be a `compile`/`implementation` dependency,
only idling resources should be accessible in production
* Fix usages of `espresso-core` usages in production code
=> [GSoC18] Fix espresso core dependency

Jenkinsfile
Currently there are two different NDK behaviors in place, one to keep NDK r16b, which was needed because of the removal of armeabi and MIPS support and one to always use the latest NDK, which is the suggestion from the NDK documentations.
Therefore two different SDK locations on the host are currently in place:
NDK r16b  : /var/local/container_shared/android-sdk
NDK latest: /var/local/container_shared/android-sdk-ndk-latest
As android-sdk was used from the beginning and is already 'released' this can't be changed to eg android-sdk-ndk-r16b and must be kept to the previously used value
=> JENKINS-232: Use different SDK mappings for different NDK versions

build.gradle, catroid/build.gradle
* Move `google-services` classpath to project
* Remove outdated, unused `gradle:2.3.3` from project buildscript dependencies
* Merge `android` section
* Move commonly used versions to `ext.*Version` variables
* Use specific version for `androidasync` dependency
* Group dependencies
* Explicitely supply versions for some `com.android.support.*` libraries to avoid different versions being used. (See `GradleCompatible` lint rule)
* Remove some lint ignores
* `GradleDynamicVersion`: It should be necessary to supply a specific library version so library upgrades don't happen without anyones knowledge
* `DefaultLocale`: This rule doesn't get violated anyways
Depends on #2934
=> [GSoC18] Clean up build.gradle files

build.gradle, catroid/build.gradle, catroid/src/main/res/layout/dialog_brick_editor_edit_element.xml, gradle.properties, gradle/wrapper/gradle-wrapper.properties
* Update android gradle plugin to `3.1.4`
* See https://android.googlesource.com/platform/ndk/+/ndk-release-r18/CHANGELOG.md#known-issues on why this is necessary
* Update gradle to `4.4` (Needed for android gradle plugin `3.1.x`)
* See https://developer.android.com/studio/releases/gradle-plugin#updating-gradle on why this is necessary
* Set `android.enableD8MainDexList` to false in `gradle.properties`
* This is a workaround to allow tests being run in multidex apps on API <21
* See https://issuetracker.google.com/u/0/issues/78108767 for more info
* Remove `buildToolsVersion` as it's ignored/obsolete with android gradle plugin `3.1.x`
=> CATROID-67 Fix builds failing on ndk r18

catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/SetLookByIndexBrickTest.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/SetBackgroundByIndexBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/SetLookByIndexBrick.java
The SetLookByIndexAction was created by calling
`ProjectManager.getInstance().getCurrentSprite()` which will always
return the sprite currently open/editing in the IDE. This lead to
crashes or unexpected behavior when run.
Fixed by using the passed sprite parameter instead when calling
addActionToSequence. Reverting the changes made to addActionToSequence
(SetLookByIndexBrick and SetBackgroundByIndexBrick) in 33700038a.
=> CATROID-46 SetLookByIndexAction created with wrong sprite reference

catroid/build.gradle
* Use the latest hotfix release, including an "about" dialog and
a fix for devices with display notch(es), preventing you from
switching the current tool.
=> PAINT-332: Update Pocket Paint dependency

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/SceneTransitionBrickStageTest.java, catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
- Changed object references -> backup now holds new list containing
references instead of a reference to the original list.
- Removed stage object from backup, because now only one stage is used,
where state is restored from actors.
- Removed and simplified some code.
=> CATROID-72 Fix ContinueSceneBrick

catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
- null check to avoid "random" crashes.
- no test because it cannot be reproduced consistantly.
=> CATROID-83 Added null check crash in showLegoSensorConfig

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/ImportProjectsFromExternalStorageTest.java, catroid/src/catroid/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/createAtSchool/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/lunaAndCat/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/main/AndroidManifest.xml, catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/common/SharedPreferenceKeys.java, catroid/src/main/java/org/catrobat/catroid/io/StorageOperations.java, catroid/src/main/java/org/catrobat/catroid/ui/ImportLaunchers.kt, catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java, catroid/src/main/java/org/catrobat/catroid/utils/CopyProjectsTask.java, catroid/src/main/java/org/catrobat/catroid/utils/ImportProjectsFromExternalStorage.java, catroid/src/main/res/values/strings.xml, catroid/src/main/res/xml/file_paths.xml, catroid/src/phiro/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/standalone/java/org/catrobat/catroid/common/FlavoredConstants.java
CATROID-59 Exposing file uris
* implementing FileProvider
CATROID-56 Import old Pocket Code folder into app-private storage.
CATROID-55Use app-storage instead of folder on external memory
UiTest included.
=> CATROID-55,56,59 private Storage tickets

Jenkinsfile.ManualTests
The job dsl has to create paramters for the git repository/branch.
Yet these two paramters clear all other paramters, also those defined in the Jenkinsfile.
Since the job dsl is run once per day it could result in users having
to start the ManualTests job twice.
Once to create the necessary paramters and a second time to fill in these paramters.
To avoid such inconvenience it is better to manage the paramters soley
via the job dsl.
=> CATROID-101 Remove paramters to not clash with the job dsl.

Jenkinsfile
The new name is "#BUILD_NUMBER BRANCH_NAME".
The build-number is first to ensure that it is visible even for longer branch names.
This should make it easier to identify which build an APK is related to.
In the previous case the APKs would always have an application name of
"Code Nightly #BUILD_NUMBER" which is confusing for PRs as it is not clear
which PR they refer to.
Testing done:
Installed APKs generated that way on my local device.
Names that were fully visible "#12 PR-12345" "#1234 develop".
Longer branch names were cut off.
For these cases the application has to be started to get the full name.
=> CATROID-109, JENKINS-272 The application name for debug APKs includes the branch name.

catroid/src/androidTest/java/org/catrobat/catroid/test/formulaeditor/FormulaEditorDataListAdapterArraysValueTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/formulaeditor/ParserTestUserLists.java, catroid/src/androidTest/java/org/catrobat/catroid/test/utiltests/NumberFormatsTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SetVariableTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorEditTextTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorFragmentTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/FormulaEditorComputeDialogTest.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/Formula.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java, catroid/src/main/java/org/catrobat/catroid/ui/ScratchProgramDetailsActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/dialogs/FormulaEditorComputeDialog.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/ListRVAdapter.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/VariableRVAdapter.java, catroid/src/main/java/org/catrobat/catroid/utils/NumberFormats.java, catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
* 32-In Say and Think bubbles, no trailing zeroes (.0 etc) should be shown
* 33-Compute" in the formula editor should show no trailing zeroes (.0 etc)
* Strip any trailing 0 from numbers before converting them into text strings
* Do not show any trailing 0 in the list of values of variables and lists
=> CATROID-32/33/34/35

Jenkinsfile.buildDebugApks
The APKs can be installed independently of the released APKs since they
have a name based on the branch that was built.
=> CATROID-120, JENKINS-274 Add Jenkinsfile to build all flavours and archive them.

catroid/src/androidTest/java/org/catrobat/catroid/test/ui/brickadapter/BrickAdapterDragAndDropTest.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/BrickAdapter.java
- when the user drags an empty script by its script brick and
adds it somewhere in another script, this other script is split
at the next possible (after nested brick - i.e. control structures)
position (similar to the bahavior before scripts were draggable).
=> CATROID-124 Split script when dragging empty script 

catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickCloneTest.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/FormulaBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenConditionBrick.java
WhenConditionBrick has a ConcurrentFormulaHashMap because it's extended
from Formula. WhenConditionScript has a ConcurrentFormulaHashMap because
the map is serialized. To work correctly, both members have to point to
the same instance.
When cloning a WhenConditionBrick, these two members pointed to
different ConcurrentFormulaHashMap thus causing CATROID-108.
___
- You can find the same info but a little more detailed (or phrased differently) at [CATROID-108](https://jira.catrob.at/browse/CATROID-108).
- Feel free to comment(criticize) on the test implementation :wink: 
Please consider a fix for [CATROID-108](https://jira.catrob.at/browse/CATROID-108) for the next release :grimacing:
=> CATROID-108 Fix "When becomes true" looses formula

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/BricksWithMultipleBrickFieldsEditFormulaTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/utils/BrickDataInteractionWrapper.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ArduinoSendDigitalValueBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ArduinoSendPWMValueBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveBackwardBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveDownBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveForwardBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveLeftBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveRightBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneMoveUpBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneTurnLeftBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/DroneTurnRightBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/FormulaBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/GlideToBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/InsertItemIntoUserListBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/JumpingSumoMoveBackwardBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/JumpingSumoMoveForwardBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/LegoEv3PlayToneBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/LegoNxtPlayToneBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/PhiroRGBLightBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/PlaceAtBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/RaspiPwmBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/RaspiSendDigitalValueBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ReplaceItemInUserListBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/SetPenColorBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ShowTextBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ThinkForBubbleBrick.java, catroid/src/main/java/org/catrobat/catroid/physics/content/bricks/SetGravityBrick.java, catroid/src/main/java/org/catrobat/catroid/physics/content/bricks/SetVelocityBrick.java
Tap on a brick with multiple formulas to open the menu and select Edit Formula. The Formula Editor opens and the "default formula" will be selected. This formula was once explicitly defined in the code, now isn't (kinda random now, e.g. the default formula of the PlaceAtBrick is Y now).
Simply use the first formula parameter, from the left.
=> CATROID-63 The formula when selecting Edit Formula in the menu for bricks with multiple formulas isn't properly defined

Jenkinsfile.SensorboxTests
Initial Issue
=============
Initially there was only support for one HardwareSensorBox and even just one
Android device per slave.
This was due to the ANDROID_SERIAL being set on the Slave itself.
Adding further devices would be very complicated in such a setup, as the
ANDROID_SERIAL would have to be set to a different value.
Solution
========
The solution is to create one resource per device in "Configure System" of Jenkins.
This resource has the Android serial as its name.
Then it has two labels
* HardwareSensorBox-${NAME_OF_SLAVE_THE_RESOURCE_IS_PRESENT_ON},
e.g. HardwareSensorBox-Slave1-HardwareSensorBox, to run tests on the
hardware sensor box.
* AndroidDevice-${NAME_OF_SLAVE_THE_RESOURCE_IS_PRESENT_ON},
e.g. AndroidDevice-Slave1-HardwareSensorBox, to run tests directly on
Android …
=> CATROID-123, JENKINS-277 Add support for multiple hardware sensor boxes.

Jenkinsfile, Jenkinsfile.BuildStandalone, Jenkinsfile.ManualTests, Jenkinsfile.SensorboxTests, Jenkinsfile.buildDebugApks, Jenkinsfile.buildMetadata, Jenkinsfile.releaseAPK, buildScripts/checkUrlExists.sh
From the story:
The Jenkinsfiles already have some cruft.
So clean them up.
* One that changes everything to whitespaces.
* Fewer environment variables. Instead use local variables where useful.
* Better stages, i.e. one for tests with sub stages for the different kinds of tests. This makes it easier to parallelize these stages later on.
* Helper functions to make what is used clearer. Especially avoid moving results etc!
=> CATROID-129, JENKINS-278 - Cleanup Jenkinsfiles

catroid/src/androidTest/java/org/catrobat/catroid/test/content/project/ProjectTest.java, catroid/src/main/java/org/catrobat/catroid/content/Project.java, catroid/src/main/java/org/catrobat/catroid/content/XmlHeader.java
The Android platform version is an integer and has been stored in the
XmlHeader as double. However, the iOS platform version has a format like
MAJOR.MINOR.PATCH[1]. Programs with such a format can't be loaded by
Catroid.
XStream doesn't store any information about the type of the platform
version in the XmlHeader, e.g. <platformVersion>26.0</platformVersion>.
Simply changing the type from double to String is sufficient to allow
any version format.
[1] https://en.wikipedia.org/wiki/IOS_version_history
___
As you can see, no test. Once you verified everything works as expected (I verified a few random programs and also one with `<platformVersion>26.0.1 beta</platformVersion>`) , testing this is like testing XStream, imo.
=> CATROID-65 Support iOS and other platform version formats in XmlHeader

catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java
* the 3 Projects, which mentioned in the ticket's description, have an old structure (no scene folder, see attached screenshot) (I didn't know that before ^_^).
* the problem was, the method FileUtils.copyFileToDir(File srcFile, File destFile) somehow doesn't work.
=> CATROID-117 Manual thumbnails (preview screenshots) lost after entering project (including in Tic Tac Toe Master)

catroid/src/main/java/org/catrobat/catroid/ui/fragment/ScriptFragment.java
After first brick was added, if second brick was of ScriptBrick type then adapter.updateItems(sprite) was not being called which was fixed .
=> CATROID-139 Fix second brick not being visible

Jenkinsfile, Jenkinsfile.BuildStandalone, Jenkinsfile.ManualTests, Jenkinsfile.SensorboxTests, Jenkinsfile.buildMetadata, Jenkinsfile.releaseAPK, catroid/build.gradle, docker/Dockerfile.jenkins
* All Android dependencies are handled inside of Docker
* Uses faster emulator settings
* Parallelize the build, often leading to build times of 13 minutes.
=> CATROID-141, JENKINS-246 Improve the performance of the Catroid Job and moves dependencies to Docker

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorDiscardChangesTest.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorHistory.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/UndoState.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
Cancelling Formula Editor changes doesn't revert all formulas or spinner
selections. To solve the bug a class named UndoState was implemented for
saving the initalStates in a map.
The map stores all inital values of brickfields so if user discards
changes the old ones are used which are taken from the initialstates
map.
=> CATROID-49 bug regarding discarding changes

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
- file picker fails to recognize some .catrobat files as zip files.
- removed file picker and replaced it with custom implmentation
(that we already used on devices running apis < 17) to
curcumvent this problem.
=> QUICKFIX Removed OS file picker for project import

catroid/src/main/AndroidManifest.xml
- used to be necessary to correctly handle cases
where pocket paint was not installed on device.
=> UTIL Removed REORDER_TASKS permission.

catroid/src/main/java/org/catrobat/catroid/web/ServerCalls.java
"tags" are no longer available in the scratch metadata, it doesn't seem there is any replacement for them. Removing them solves the "Whoops Server did not reply" and missing metadata.
=> STCC-182 Fetching Meta Data in Pocket Code fails

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/LookController.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SoundController.java
references.
- added a workaround to prevent crashes in backpack.
=> QUICKFIX Fixed null pointer exception when unpacking bricks with

Jenkinsfile
The other static analysis plugins are deprecated and succeeded by warnings-ng.
With JENKINS-55436 fixed we can use warnings-ng ourselves, without breaking
existing jobs.
=> JENKINS-269 Use the warnings-ng plugin.

Jenkinsfile
The legacy tests are there to detect regressions with older Android versions,
in this case for Android 19.
=> JENKINS-296 Add legacy tests to the Catroid job.

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/MainMenuFragment.java
After opening a downloaded project via the notification, the back-button won't work anymore.
(The application loads the project again)
This line solves the problem.
=> CATROID-FIX Fix notification start downloaded project

catroid/build.gradle, catroid/src/main/java/org/catrobat/catroid/camera/CameraManager.java, catroid/src/main/java/org/catrobat/catroid/stage/StageResourceHolder.java, catroid/src/main/java/org/catrobat/catroid/utils/FlashUtil.java, catroid/src/main/res/values/strings.xml, catroid/src/test/java/org/catrobat/catroid/test/utiltests/FlashUtilTest.java
When camera device has no flash available, the flash brick action should simply be ignored.
e.g. emulators or tablets
Added tests for FlashUtil so CameraManager and Camera are PowerMocks for simulating environment.
=> CATROID-88 Devices without Flash should ignore FlashBrick

catroid/src/main/java/org/catrobat/catroid/content/ListWithoutDuplicates.java, catroid/src/main/java/org/catrobat/catroid/content/Project.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/DataListAdapter.java, catroid/src/test/java/org/catrobat/catroid/test/content/ListWithoutDuplicatesTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/userdata/UserListTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/userdata/UserVariableTest.java
Custom implementation of an ArrayList which acts like a HashSet. 
- RecyclerView-Adapter needs a list, so some functions which HashSet doesnt provide can be used. (Index-based array operations)
- Theres also an internal HashSet running in background so that checks for duplicates can be executed in O(1). List.contain(...) needs O(n).
- The tests added should check the behaviour of the custom list, to act like kind of a HashSet. Operation comparison between custom List and java HashSet. Tests are parameterized so tests for every new object that uses this list implementation can be added within 4 lines of code.
- HashSet does automatically sort the data after operations. Since we need logic of a programming language, this should be users task and we'll keep insertion order like a list.
- …
=> CATROID-224 ListWithoutDuplicates Implementation for RV

catroid/src/main/AndroidManifest.xml, catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
tested on Devices with SDK 21, 23, 26 , 
Emulators with SDK 24, 25, 26, 27, 28
not testable on emulators with SDKs below 24 because of : the web-view doesn't support the new design of share website.
if you got a msg like "could n't install the Apk || or App not installed" please disable the play protect feature from play store.
=> CATROID-194 Downloaded APKs cannot be installed via notification area

catroid/src/androidTest/java/org/catrobat/catroid/test/common/LookDataTest.java, catroid/src/main/java/org/catrobat/catroid/common/LookData.java, catroid/src/main/java/org/catrobat/catroid/sensing/CollisionInformation.java, catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.java, catroid/src/test/java/org/catrobat/catroid/test/common/LookDataTest.java
- collision information gets already calculated in the background
on look creation/edition
- file ending gets extracted over mime type (png relevant)
- small test for the collision functionality
Edited recently opened PR [#3198](https://github.com/Catrobat/Catroid/pull/3198) of Patrick S. and modified files by the requested changes:
- [PRODUCTION] `getImageMimeType()` is now function of `LookData` Object
- [TESTS]                Now running sepparately on emulator and local JVM
- [TESTS]                No more references to Project or Sprite, image gets created in cache directory
- [TESTS]                `tearDown()` method to clear cache directory afterwards
Pocket Code test program to show touches object now working: [TouchesObject](https://share.catrob.at/pocketcode/program/86900) …
=> CATROID-104 touches_object not working correctly anymore

catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
Use `URLUtil.guessFileName()` to detect correct file name for media-library downloads.
It prefers content disposition header.
=> Fix Media-Library download filename

catroid/src/main/java/org/catrobat/catroid/ui/ProjectUploadActivity.java
When uploading a project, you can change description in the upload dialog. But Changes were made only locally.
The web server doesn't fetch the projectDescription Tag of the HTTPRequest. It fetches the description from the code.xml, which was saved only "after" Upload. So the old description still remained in Upload (code.xml)
=> CATROID-282 Description not updated/uploaded correctly

Jenkinsfile.releaseAPK
Fixes bug preventing CreateAtSchool and Phiro release apks being
uploaded to the alpha track on Google Play. Extra \ characters in
lines made sh put two fastlane commands into one line, thereby
effectively ignoring the second command.
=> JENKINS-317 Fix APKs not being uploaded to Google Play

catroid/src/main/AndroidManifest.xml
This permission gets merged from libARDiscovery and is a system permission starting from 21.
=> CATROID-293: Fix GET_TASKS permission warning

catroid/build.gradle, catroid/src/main/AndroidManifest.xml
As far as i can test it seems like there are no problems with just updating the reference. But to be aware, we are currently restricted, so it's still the same error message as before.
=> CATROID-307 Upgrade Facebook SDK to v5.1.1

catroid/src/main/res/layout/formula_editor_keyboard.xml, catroid/src/main/res/values/styles.xml
* Fixes the margins of the delete key in formula editor
| Before | After |
|----------|--------|
| <img src="https://user-images.githubusercontent.com/30626927/63383926-1240da80-c39e-11e9-9813-b25766f33f39.png" width="300" /> | <img src="https://user-images.githubusercontent.com/30626927/63383933-17058e80-c39e-11e9-8f61-5899293463b6.png" width="300" /> |
=> Fix layout margins of delete key in formula editor

catroid/src/main/java/org/catrobat/catroid/content/eventids/SetBackgroundEventId.java, catroid/src/test/java/org/catrobat/catroid/test/content/script/EventIDHashCodeTest.java
- add null check in setBackGroundEventId
- add testcase for hashCode Function
=> CATROID-365 fix crash of WhenBackGroundChanges without selection

catroid/src/androidTest/java/org/catrobat/catroid/test/web/AuthenticationCallsTest.java
* New web test server returns StatusCode 803 (Username valid but not found)
See https://github.com/Catrobat/Catroweb-Symfony/blame/1d420c9b075aca14ff203226792bc988082bdd21/src/Catrobat/StatusCode.php#L77
* Fix test to reflect this change
* Neither the old status code nor the new one are used in production, so production is left unchanged
=> MAINTENANCE: Fix Authentication test

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorTest.java, catroid/src/main/java/org/catrobat/catroid/utils/NumberFormats.java, catroid/src/test/java/org/catrobat/catroid/test/formulaeditor/FormulaTest.java
* Bracket Elements get initialized with empty string instead of null. String compare operations now don't crash anymore with brackets.
=> CATROID-239 Formula Editor does not crash after wrapping anything in Brackets

catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickCollisionUpdateTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickWithSecondaryListCollisionUpdateTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/UpdateCollisionActorScriptBrickTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/UpdateCollisionActorTest.java
- add check in RecyclerViewFragment to call rename instead of setter
- change renameSpriteInCollisionFormulas iteration over bricks
- add Testcases similar to CATROID-258
=> CATROID-338 fix touches actor name change does not affect formulas

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/OpenFromShareLinkTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/PrivacyPolicyDisclaimerTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/LanguagePickerTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/RTLMainMenuTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/AboutDialogTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/OrientationDialogTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/TermsOfUseDialogTest.java, catroid/src/main/java/org/catrobat/catroid/common/SharedPreferenceKeys.java, catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
When User updates PocketCode the AGREED_TO_PRIVACY_POLICY_PREFERENCE_KEY is already set to true so need additional check with the versionCode which is changed in each release
=> CATROID-401:  Privacy policy update 

catroid/src/main/java/org/catrobat/catroid/io/StorageOperations.java
- ContentResolver.query(..) seems to throw a runtime exception
because of some security issue -> as seen in Play Console.
This catches said exception.
=> CATROID-420 Catch runtime exception in ContentResolver.

catroid/src/debug/AndroidManifest.xml
Fixed like proposed on [Stack Overflow](https://stackoverflow.com/questions/16932248/crashlytics-could-not-be-initialized-api-key-missing-from-androidmanifest-xml).
=> CATROID-427: Fix fabric logged crashes in logs on debug builds

catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
currently second highest crash in play console, again cascading crash after an actual crash for some other reason.
=> CATROID-439 - StageActivity onDestroy crashes when no current project

catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/stage/ShowTextActor.java
With this update the ShowVariable brick are now correctly displaying empty variables/formulas as such instead of the predefined text "No value set". 
Examples: 
The formula "5" still results in "5". 
The formula "" now results in "", instead of "No value set".
=> Empty formulas are now correctly displayed, if the ShowVariable brick is used

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/BroadcastBrickMessageUpdateTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/utils/BrickSpinnerDataInteractionWrapper.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/messagecontainer/BroadcastAndWaitBrickMessageContainerTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/messagecontainer/BroadcastMessageBrickTestUtils.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/messagecontainer/BroadcastReceiveBrickMessageContainerTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/messagecontainer/BroadcastSendBrickMessageContainerTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/matchers/BrickSpinnerMatchers.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/BroadcastMessageBrick.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/BroadcastMessageBrickTest.java
- Add a UI test for correct lexicographic order
- Rename createNewBroadcastMessageOnBrick() and withNameableValues() as there were spelling mistakes.
- Rename BroadcastMessageBrickUtils to BroadcastMessageBrickTestUtils to prevent misleading.
=> CATROID-387 Show messages of BroadcastMessageBricks in lexicographic order

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/GlideToBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/VisualPlacementBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorDiscardChangesTest.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/FormulaBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/VisualPlacementBrick.java, catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
- Adapt FormulaEditorDiscardChangesTest so that it works correctly again with the new functionalty of the formula editor
- Add further testcases in VisualPlacementBrickTest
- Separate a GlideToBrickTest from VisualPlacementBrickTest because this one cannot be parameterized
=> CATROID-468 Make visual placement option available in formula editor

catroid/build.gradle
With the current version of the android gradle plugin it's now possible to set a default flavor dimension for android studio (used only at the first time you open the project).
This should fix the recurring issue we have with people having set `arduinoDebug` as default flavor by accident.
See the issue tracker for the related feature request:
https://issuetracker.google.com/issues/36988145
- [-] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer
=> MAINTENANCE: Set default flavor dimension for Android Studio

catroid/src/androidTest/java/org/catrobat/catroid/test/embroidery/ZigZagParametrizedTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/embroidery/ZigZagRunningStitchTest.java, catroid/src/main/java/org/catrobat/catroid/embroidery/RunningStitchType.java, catroid/src/main/java/org/catrobat/catroid/embroidery/SimpleRunningStitch.java, catroid/src/main/java/org/catrobat/catroid/embroidery/TripleRunningStitch.java, catroid/src/main/java/org/catrobat/catroid/embroidery/ZigZagRunningStitch.java
The implemented ZigZag Stitch was not really a ZigZag Stitch. It was a Z Stitch. This ticket fixed it. https://jira.catrob.at/browse/CATROID-510
- [ x] Include the name of the Jira ticket in the PR’s title
- [ x] Include a summary of the changes plus the relevant context
- [ x] Choose the proper base branch (*develop*)
- [ x] Confirm that the changes follow the project’s coding guidelines
- [ x] Verify that the changes generate no compiler or linter warnings
- [ x] Perform a self-review of the changes
- [ x] Verify to commit no other files than the intentionally changed ones
- [ x] Include reasonable and …
=> Catroid 510 - Correction of ZigZag Stitch

catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickCategoryTest.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java, catroid/src/main/res/layout/brick_web_request.xml
The WebRequestBrick is now a red DataBrick and is removed from the ControlBrickList. It's now present in the DataBrickList and in the TestingBrickList.
https://jira.catrob.at/browse/CATROID-499
=>  Catroid-499 Send web request _ and store answer in _" brick should be in red Data category of bricks

catroid/src/main/java/org/catrobat/catroid/sensing/CollisionPolygonCreationTask.java, catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java, catroid/src/main/res/values/strings.xml
Crash while creating a new Actor . Ticket Fixed is https://jira.catrob.at/browse/CATROID-458  
**Summary**
**Previous Behavior** While choosing a picture from the device it was possible to select a svg graphic which crashed the creation of the actor and it jumped back to the main menu
**Current Behavior** If you select file which cannot be decoded by Bitmap Factory (svg file etc) then it will popup message "Image format not supported" without crashing application and will remain on the same menu.  
**Branch** develop
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this …
=> CATROID-458:Crash while creating a new Actor

catroid/src/main/AndroidManifest.xml, catroid/src/main/java/org/catrobat/catroid/ui/ProjectListActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
The Pocket Code App should be able to import files with .catrobat file extension.
When Other apps encounter .catrobat files they will call implicit intent to pocket code app. The pocket code app will open in the Project List Activity (ProjectListActivity).
--
--
files by Google:
Tested on:
Pixel 3 Api29 Emulator
ZTE blade mini Android 7.0 Api24
Nexus 6P Android 7.1.1 Api25 Emulator
Nexus S Android 6 Api23 Emulator
=> CATROID-336 "Open" .catrobat extension files

catroid/src/main/java/org/catrobat/catroid/content/Look.java, catroid/src/main/java/org/catrobat/catroid/sensing/CollisionInformation.java, catroid/src/test/java/org/catrobat/catroid/test/content/sprite/LookTest.java
Refactored some point to point distance calculations. One testcase for the function 'getDistanceToTouchPositionInUserInterfaceDimensions()' got deleted, because it asserted always true. For the other function(s), no additional testcases were added, because there are already at least one for each edited function.
=> CATROID-511 Refactor some distance calculations

catroid/src/main/res/values/strings.xml
**Description:**
Corrected typo in string in strings.xml, referenced in RegistrationDialogFragment.java.
**Before:**
Email address cannot be used as user names
**After:**
Email address cannot be used as username
**File:**
catroid\src\main\res\values\strings.xml
**Screenshot for Change:**
=> Fix Typo in Registration Dialog

catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java, catroid/src/main/java/org/catrobat/catroid/content/actions/WebRequestAction.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/WebRequestActionTest.java
Moved the interpretation of the input formula of the WebRequestBrick
from the ActionFactory to the action, so that the formula is
interpreted at run-time.
[CATROID-500](https://jira.catrob.at/browse/CATROID-500)
=> CATROID-500 Fix variable interpretation in WebRequestBrick

catroid/src/main/java/org/catrobat/catroid/formulaeditor/Formula.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/Functions.java
This PR is solving the issue that some list functions could not be interpreted, if used the "Compute"-button in the formula editor.
Update: Implemented all the feedback from @christophsiegl. I also killed my own testcases, which I added in a previous PR, since there are already similar testcases or they provided not enough value. 
=> CATROID-402 Fix Error on Compute for list functions

catroid/src/main/java/org/catrobat/catroid/content/actions/AssertEqualsAction.java
Fixes behavior where assert brick would not consider -0 and 0 to be equal
=> CATROID-551 Assert brick behavior differs from equality sign in formula

catroid/build.gradle, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/VariableBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorMultiplayerVariablesTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorVariableScopeTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/SettingsFragmentTest.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/brickspinner/UserVariableBrickTextInputDialogBuilder.java, catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/settingsfragments/SettingsFragment.java, catroid/src/main/res/layout/dialog_new_user_data.xml, catroid/src/main/res/values/strings.xml, catroid/src/main/res/xml/preferences.xml
[CATROID-542](https://jira.catrob.at/browse/CATROID-542) 
- Add multiplayer variables feature flag
- Add multiplayer extension preference to settings screen
- Add multiplayer scope to "New variable" dialogs
- Fix typo in FormulaEditorVariableScopeTest class name
This is the first step of implementing Bluetooth multiplayer feature. This PR adds only the base - feature flag, item in settings and the UI for multiplayer variables in "New variable" dialogs (bot in the Data category in formula editor and by pressing "new..." on a brick).
=> CATROID-542 Introduce multiplayer variables setting and UI to create it

catroid/src/main/java/org/catrobat/catroid/stage/EmbroideryActor.java, catroid/src/test/java/org/catrobat/catroid/stage/EmbroideryActorCircleTest.java, catroid/src/test/java/org/catrobat/catroid/stage/EmbroideryActorLineTest.java
Fixes bug where stitches from different embroidery needles would be connected.
=> CATROID-476 Line gets drawn between successive layers

catroid/src/androidTest/java/org/catrobat/catroid/test/BricksHelpUrlTest.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/UserDefinedBrick.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddBrickFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserBrickFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDataToUserBrickFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/UserBrickListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/BrickAdapter.java, catroid/src/main/res/layout/brick_user_brick.xml, catroid/src/main/res/layout/fragment_add_new_user_brick.xml, catroid/src/main/res/layout/fragment_add_user_data_to_user_brick.xml, catroid/src/main/res/layout/fragment_user_brick_list.xml, catroid/src/main/res/values/strings.xml, catroid/src/main/res/values/styles.xml, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/AddUserBrickTest.java
- Implement ListFragment to show the already defined UserBricks
- As it is not possible to make ScrollViews inside ListViews the Layout of a UserBrick was refactored according to https://jira.catrob.at/browse/CATROID-573. This makes it possible that a UserDefinedBrick can consist of more lines now.
- InputFields and Labels of UserDefinedBricks are also adapted to the previously mentioned ticket. Thus, if they get longer than one line the text is displayed with dots.
- As discussed with @BeinhAlex a testcase will be added with ticket https://jira.catrob.at/browse/CATROID-219
https://jira.catrob.at/browse/CATROID-217
=> CATROID-217 Show list of user bricks

catroid/src/main/java/org/catrobat/catroid/stage/PenActor.java, catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
If you change from STRETCH mode to MAXIMIZE mode, the draws
of the pen brick are not correctly scaled. So the draws have
the wrong position.
The change of the screen mode is performed in the StageListener.
Proper scaling of the ShapeRenderer (which is used to draw) is
applied there. The scaling factor for x and y is also calculated
there.
Also changed if-query in PenActor to increase performance.
In Previous version, shapeRenderer methods were called although 
position didn't change. sprite.look.getX/Y() returns not the
centered coordinates of the actor. 
https://jira.catrob.at/browse/CATROID-351
=> CATROID-351 Correct pen brick draws in Maximize mode

catroid/src/main/java/org/catrobat/catroid/stage/ShowTextActor.java, catroid/src/main/java/org/catrobat/catroid/web/WebConnection.java, catroid/src/test/java/org/catrobat/catroid/test/web/WebConnectionTest.java
Fixes rendering crashes for long strings
=> CATROID-547 Web request brick crashes for certain URLs

catroid/src/main/java/org/catrobat/catroid/common/Constants.java
Updated URL Prefix from "http://..." to "https://..". Scratch2Catrobat Converter is now supporting HTTPS.
=> CATROID-330 Update Scratch2Catrobat converter URL prefix

catroid/src/main/java/org/catrobat/catroid/formulaeditor/Formula.java
Computing the value of certain properties no longer displays an error.
=> Fixed IllegalArgumentError in formula computation

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/MainMenuFragment.java, catroid/src/main/res/layout/landing_page.xml
https://jira.catrob.at/browse/CATROID-631
Fixed a bug which opened the wrong project when choosing the current project on the landing page after a download.
Added a test to prevent this bug in future
=> CATROID-631 Current project after download incorrectly opens previously opened project

catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
When the app is opened from the browser, there is a high chance
the user was browsing the ShareCommunity platform under the "app" flavor
which is basically the same as "pocketcode".
- add "app" url constant
- "app" index route closes web-view, similar to "pocketcode" index route
=> CATROID-637 Exit Community (open app in browser)

catroid/src/main/java/org/catrobat/catroid/content/actions/ReadVariableFromFileAction.kt
if no suffix is provided it will still append '.txt'
=> CATROID-621 removed limitation of suffix from ReadVariableFromFileBrick

catroid/src/main/java/org/catrobat/catroid/camera/CameraManager.kt, catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
Fixes issue where transparent sprites would not be shown when the camera image is inactive.
=> Sprite visibility fix

catroid/src/main/java/org/catrobat/catroid/camera/FaceDetector.kt
Creates face detection client on demand to avoid unneccessary camera access. Issue is most apparent on devices with pop-up camera (eg. Xiaomi Mi 9T Pro).
=> CATROID-652 Front Camera is always activated

catroid/build.gradle, catroid/gradle/standalone_apk_tasks.gradle
* the project folder is missing in the built apk file
* right now the package name of the apk is org.catrobat.{projectId}.standalone, which must be pre-defined during the build to something like com.mydomain.{projectName}
=> CATROID-643: fix StandaloneSignedRelease build

catroid/src/main/java/org/catrobat/catroid/content/bricks/StopSoundBrick.kt
Fixes issue where project could not be saved when a Stop Sound Brick was used.
=> CATROID-648 Projects are not being saved after using "stop _ sound" brick

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/DeleteUserDefinedReceiverBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/utils/BrickDataInteractionWrapper.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/UserDefinedBrickTest.java, catroid/src/main/java/org/catrobat/catroid/content/Script.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/UserDefinedBrick.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDefinedBrickFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/BrickController.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java, catroid/src/main/res/values/strings.xml, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/UserDefinedBrickEqualityTest.java
- Add context menu items for deleting/moving UserDefinedReceiverBrick ⇨  https://jira.catrob.at/browse/CATROID-309 and https://jira.catrob.at/browse/CATROID-310 work out-of-the-box and can be closed if this PR is merged
- Multi-brick deletion from the overflow menu is handled in the same way as for one UserDefinedReceiverBrick
=> CATROID-306 Enable delete option for UserDefinedReceiverBrick

catroid/build.gradle, catroid/proguard-project.txt, catroid/src/main/java/org/catrobat/catroid/CatroidApplication.java, catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickAddCategoryTest.java, catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickSingleFormulaFieldTest.java, catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickSpinnerDefaultValueTest.java, catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickSpinnerTest.java, catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickStringSpinnerDefaultValueTest.java, catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickStringSpinnerTest.java, catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BroadcastBrickTest.java, catroid/src/test/java/org/catrobat/catroid/test/robolectric/formulaeditor/FormulaEditorEditTextGenericTest.java
* Migrate to AndroidX (targetSdkVersion 29)
* set config annotations with sdk 28 for robolectric tests, cause android Q(Api 29) isn't yet supported by robolectric
=> CATROID-636: Migrate to AndroidX (targetSdkVersion 29)

catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickFormulaDefaultValueTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorUserDefinedBrickTest.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/Brick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ConcurrentFormulaHashMap.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/FormulaBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/UserDefinedBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/UserDefinedReceiverBrick.java, catroid/src/main/java/org/catrobat/catroid/content/commands/ChangeFormulaCommand.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorHistory.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/UndoState.java, catroid/src/main/java/org/catrobat/catroid/io/BackpackFormulaFieldSerializerAndDeserializer.java, catroid/src/main/java/org/catrobat/catroid/io/BackpackSerializer.java, catroid/src/main/java/org/catrobat/catroid/io/XStreamConcurrentFormulaHashMapConverter.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDataToUserDefinedBrickFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDefinedBrickFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/UserDefinedBrickListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.java, catroid/src/main/java/org/catrobat/catroid/userbrick/InputFormulaField.java, catroid/src/main/java/org/catrobat/catroid/userbrick/UserDefinedBrickData.java, catroid/src/main/java/org/catrobat/catroid/userbrick/UserDefinedBrickLabel.java
- derive UserDefinedBrick from FormulaBrick
- add flag isCallingBrick to UserDefinedBrick to distinguish between calling bricks - where inputs can be edited - and declarative UserDefinedBricks
- refactor UserDefinedBrickData for easier handling of inputs and labels
- generalize BrickField to FormulaField with a new Interface so that InputFormulaFields can also be handled like BrickFields within the formulaMap 
- delete special copying of UserDefinedBricks/Scripts in the ScriptController as it suffices to use the generative copying methods of bricks
- add testcase for editing the values in the formulas of UserDefinedBrickInputs
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) …
=> CATROID-304 Insert UserDefinedBricks into script

catroid/src/main/java/org/catrobat/catroid/stage/ShowBubbleActor.java, catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
Add close() method to class ShowBubbleActor and dispose
the pixmaps and textures used in the constructor to prevent
memory leaks. They (Pixmap, Texture) are holding native memory
resources if dispose is not called at the end of the lifetime.
Finally the close() method is called when BubbleActor
got removed from BubbleActorList.
https://jira.catrob.at/browse/CATROID-371
=> CATROID-371 Fix the memory leak in ShowBubbleActor

catroid/src/androidTest/java/org/catrobat/catroid/catrobattestrunner/CatrobatTestRunnerTest.java, catroid/src/main/java/org/catrobat/catroid/content/actions/AssertUserListAction.kt, catroid/src/main/java/org/catrobat/catroid/content/actions/RepeatParameterizedAction.kt, catroid/src/main/java/org/catrobat/catroid/content/bricks/BrickBaseType.java
Position counter of AssertUserList and ParameterizedTest now start with 1
Statically added 2 to the Position in script to start at 1 and also include the script header
https://jira.catrob.at/browse/CATROID-656
=> CATROID-656 Adjusted Assert Messages

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/PlaySoundBrickStageTest.java
The directory could not be found because it was not created earlier.
A call to mkdirs should fix this
=> CATROID-540 PlaySoundBrickStageTest

catroid/config/lint-baseline.xml, catroid/src/main/AndroidManifest.xml, catroid/src/main/java/org/catrobat/catroid/ui/filepicker/FilePickerActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/filepicker/ListProjectFilesTask.java
**this fixes the bug for APIs from 21 to 29.
for Android 11 (API 30) the current implementation of import projects is going to be deprecated and needs to be changed.**
=> CATROID-690: Import of Project Screen crashes

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/BrickAdapter.java
There was a problem with sublist. It probably got structurally modified somehow which results in this error.
Fixed it by manually adding the items in a for loop to a newly allocated list.
=> CATROID-459 Crash project while stacking two event bricks and two other bricks

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorVariableScopeTest.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormulaParser.java
- Make formulas containing UserDefinedBrickInputs valid
- Add testcase for adding UserDefinedBrickInputs in square brackets to existing formula
=> CATROID-233 Usage of UserDefinedBrickInputs in formulas

catroid/src/androidTest/java/org/catrobat/catroid/WaitForConditionAction.kt, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/UserDefinedBrickTest.java
- Custom ViewAction to wait for a UI Condition
- Removed thread wait fix for UserDefinedBrickTest and replaced with WaitForConditionAction
=> MAINTENANCE Reduce Flakiness in Test with custom ViewAction

catroid/src/main/java/org/catrobat/catroid/utils/NumberFormats.kt, catroid/src/test/java/org/catrobat/catroid/test/utiltests/NumberFormatsTest.java
*Certain strings with a dot incorrectly recognized as numbers were incorrectly rewritten. This PR fixes the recognition and adds a few test cases.*
https://jira.catrob.at/browse/CATROID-726
=> CATROID-726 Fix number recognition and rewriting

catroid/src/main/java/org/catrobat/catroid/content/bricks/ForItemInUserListBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ForVariableFromToBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ForeverBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/IfLogicBeginBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/IfThenLogicBeginBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/PhiroIfLogicBeginBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/RepeatBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/RepeatUntilBrick.java
Endbricks now solely use the enabled/disabled state of their parents to keep their state when reopening the project.
JIRA: https://jira.catrob.at/browse/CATROID-610
=> CATROID-610 Reopening Project loads disabled EndBricks correctly

catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/PenDownActionTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/PenUpActionTest.java, catroid/src/main/java/org/catrobat/catroid/content/Look.java, catroid/src/main/java/org/catrobat/catroid/content/PenConfiguration.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/content/actions/PenDownAction.java, catroid/src/main/java/org/catrobat/catroid/content/actions/PenUpAction.java, catroid/src/main/java/org/catrobat/catroid/content/actions/SetPenColorAction.java, catroid/src/main/java/org/catrobat/catroid/content/actions/SetPenSizeAction.java, catroid/src/main/java/org/catrobat/catroid/content/actions/StampAction.java, catroid/src/main/java/org/catrobat/catroid/stage/PenActor.java
All position changes of an object are now detected and handled by the  Pen.
https://jira.catrob.at/browse/CATROID-579
=> CATROID-579 Fix incorrect behaviour of Pen Bricks

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CategoryListFragmentTest.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/CategoryListRVAdapter.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java, catroid/src/main/res/values/strings.xml
https://jira.catrob.at/browse/CATROID-708
Implemented regex assistant button.
- add regular_expression_assistant string to string.xml
- add string to CategoryListFragment.java
- add UI-Test
=> CATROID-708 - Reg Expr Assistant Button implementation

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorRegexDetectionTest.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormula.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java, catroid/src/main/res/values/strings.xml, catroid/src/test/java/org/catrobat/catroid/test/formulaeditor/InternFormulaRegexDetectionTest.java
CATROID-725 Added context sensitive regular expression editor dialog. If first param of a regular expression is selected, an extended dialog option is shown. The dialog shown has the title "Change regular expression" and has a "Assistant" button without implemented functionality.
https://jira.catrob.at/browse/CATROID-725
=> CATROID-725 Added context sensitive regular expression editor dialog

catroid/src/main/java/org/catrobat/catroid/content/Project.java, catroid/src/main/java/org/catrobat/catroid/content/Scene.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickVariableUpdateTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickWithSecondaryListUpdateTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/UpdateVariableInFormulaBrickTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/UpdateVariableInFormulaScriptBrickTest.java
The bug was caused because all user variables and lists were handled equally as global variables. This bug can be avoided by adding a check in the update user data references function if the variable or list is contained in the project arraylist(which means it is a global variable).
https://jira.catrob.at/browse/CATROID-522
=> CATROID-522 References to a local UserVariable within a Scene will be changed in all Scenes

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/RegularExpressionAssistantDialogTest.java, catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/RegularExpressionAssistantDialog.java, catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/RegularExpressionFeature.java, catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/RegularExpressionFeatureDummy.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java, catroid/src/main/res/values/strings.xml
Catroid 737 - Added list of feature functionality to regular expression assistant window
https://jira.catrob.at/browse/CATROID-737
-Add internal list functionality to add new assistant window features
-Add UI-tests testing the display and opening of the corresponding dialog
-Add datastructure for assistant features
-Add dummy class for testing purposes
=> Catroid 737 - Added list of feature functionality to regular expression assistant window

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorRegexAssistantTest.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java
-CHANGE opening the regular expression assistant in the functions list now inserts a regular expression into the formula editor before opening the assistant dialog
-ADD UI Test checking that the correct text is inserted into the formula editor
https://jira.catrob.at/browse/CATROID-710
=> CATROID-710 RegExpAssistant Button uses RegEx functionalities

catroid/src/main/java/org/catrobat/catroid/common/NfcTagData.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/NfcTagListFragment.java
When creating the NFC tag list, if the user tries to scan the same NFC tag twice, it will not be added on the list as a new one: https://jira.catrob.at/browse/CATROID-534
=> CATROID-534 No duplicates are added to the NFC tag list

catroid/src/main/java/org/catrobat/catroid/content/Look.java
https://jira.catrob.at/browse/CATROID-772 Null pointer exceptions in PhysicsLookPositionAndAngleTest get fixed.
=> CATROID-772 Get rid of null pointer exceptions

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/HtmlExtractorDialogTest.java, catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/HtmlExtractorDialog.java, catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/RegularExpressionAssistantDialog.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java, catroid/src/main/java/org/catrobat/catroid/utils/HtmlRegexExtractor.java, catroid/src/test/java/org/catrobat/catroid/test/ui/regexassistant/HtmlRegexExtractorTest.java
CATROID-763 Result of generated Regex is insert into first parameter
- Insert the created regular expression from 4.5.1/Ticket 762 into the first param of the already existent regular expression
- HtmlExtractorDialogTest: UI Test for inserted text into first parameter
- HtmlExtractorDialog: String from keyword is insert into first parameter
https://jira.catrob.at/browse/CATROID-763
=> CATROID-763 Result of generated Regex is insert into first parameter

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/ShowTextColorSizeAlignmentBrickTest.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ShowTextColorSizeAlignmentBrick.java, catroid/src/main/java/org/catrobat/catroid/content/strategy/ShowColorPickerFormulaEditorStrategy.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
The ticket specifies that following is already implemented: _Note that if the color parameter field already contained a more complex formula that would build the hex string using, e.g., join functions etc, the tap on the color parameter in the script view immediately opens the formula editor, i.e., bypassing the pop-up menu._
As this was obviously not the case it is implemented together with this ticket.
https://jira.catrob.at/browse/CATROID-382
=> CATROID-382 Enable color picker option in formula editor

catroid/src/main/res/values/strings.xml
Change dialog text for deletion of variables to "Delete this variable?" "Deleting a variable that is still in use could cause errors. You can't undo this!"
[](https://jira.catrob.at/browse/CATROID-740)
=> CATROID-740 Change dialog text for deletion of variables

catroid/src/main/java/org/catrobat/catroid/content/bricks/UserDefinedBrick.java
https://jira.catrob.at/browse/CATROID-843
=> CATROID-843 fix FormulaEditor opens from wrong UserDefinedBrickInput

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorBrickViewOnClickTest.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ShowTextColorSizeAlignmentBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/UserVariableBrickWithVisualPlacement.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/VisualPlacementBrick.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java, catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickSingleFormulaFieldTest.java
https://jira.catrob.at/browse/CATROID-820
- make visual placement also available if no variable is selected (default text "0" is displayed)
- make visual placement also available if text size is not sane (default text size 1.0 is used)
- adapt testcases when FormulaEditor should be opened immediately
=> CATROID-820 add visual placement when no variable is selected

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/stage/LookUndoTest.java, catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.java
Ticket: https://jira.catrob.at/browse/CATROID-761
Single undo of editing or creating a look (in paintroid, or on importing from gallery / media library.)
=> CATROID-761 Single undo of editing or creating a look

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorKeyboardTest.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormulaKeyboardAdapter.java
Ticket: https://jira.catrob.at/browse/CATROID-867
CRITICAL: crash when tapping on = operator in Logic tab in formula editor
=> CATROID-867 CRITICAL: crash when tapping on = operator in Logic tab in formula editor

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorAddVariableTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/FormulaEditorDataListWrapper.java, catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
Add Cancel option for new variable option in formular editor (data).
[CATROID-743](https://jira.catrob.at/browse/CATROID-743)
=> CATROID-743 Add Cancel option for new variable

catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
Added whitespace to remove Static Analysis warning in SpriteActivity
https://jira.catrob.at/browse/CATROID-872
=> CATROID-872 remove Static Analysis warning in SpriteActivity

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/WhenBackgroundChangesToBrickTest.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/WhenBackgroundChangesBrick.java, catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
Fixed the bug by setting the current sprite of the sprite activity to the background sprite when adding the new background.
Also added a test for this behaviour.
https://jira.catrob.at/browse/CATROID-765
=> CATROID-765 "new..." option in "When background changes to" brick does not create background look

catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/io/StorageOperations.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.java
Ticket: https://jira.catrob.at/browse/CATROID-878
Potential large image file size increase on "Undo" after editing a look
=> CATROID-878 Potential large image file size increase on "Undo" after editing a look

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/DeleteLookBrickTest.java, catroid/src/main/java/org/catrobat/catroid/common/LookData.java, catroid/src/main/java/org/catrobat/catroid/content/actions/DeleteLookAction.kt, catroid/src/main/java/org/catrobat/catroid/sensing/CollisionInformation.java
Fixed the bug by invalidating the lookdata on deletion to prevent a use in the collision calculation after deletion of the file.
Also included a test for it.
https://jira.catrob.at/browse/CATROID-865
=> CATROID-865 Crash on "Delete look" and "Delete background"

catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java, catroid/src/test/java/org/catrobat/catroid/test/formulaeditor/FormulaElementTest.java
This bug occured due to an exception caused by BigDecimal after the operation resulted in an
infinitely long sequence of decimals. Fixed this by adding a precision of 128.
https://jira.catrob.at/browse/CATROID-890
=> CATROID-890 Division with decimal number crashes project

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/DeleteCheckmarkTest.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
Fixed the bug by adding a check if 1 or more items are selected before accessing the list. Also included a test.
https://jira.catrob.at/browse/CATROID-869
=> CATROID-869 Crash when tapping the checkmark with nothing selected when deleting bricks and scripts

catroid/src/main/java/org/catrobat/catroid/ui/ViewUtils.kt, catroid/src/main/java/org/catrobat/catroid/ui/dialogs/regexassistant/HtmlExtractorInputDialog.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/TextInputDialog.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/login/LoginDialogFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/login/RegistrationDialogFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/scratchconverter/ScratchSearchResultsFragment.java
https://jira.catrob.at/browse/CATROID-864
- Fixed bug of Scratch2Catrobat search view, where the results of the old search persisted even if no more character was within the textfield.
=> CATROID-864 Show keyboard for TextInputDialogs

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/visualplacement/VisualPlacementActivityTest.java, catroid/src/main/java/org/catrobat/catroid/visualplacement/VisualPlacementActivity.java, catroid/src/main/res/values/strings.xml
Jira Ticket :- https://jira.catrob.at/browse/CATROID-857
When the user taps the back arrow in the "Visual Placement editor" it ask if you want to change the changes or cancel the action. "Cancel" suggests that you get back to the editing view but the changes are just discarded and the activity gets closed. So the "Cancel" button should be renamed to "Discard".
Changes Made
"Cancel" button is renamed to "Discard"
Screenshot
=> CATROID-857 Change Dialog for exiting Visual Placement

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CopyProjectTest.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
Fixed the bug by looping over all elements in the selected item list and adding already used names in the copying to
the name list to ensure that no two copied projects receive the same name. Also added a test.
https://jira.catrob.at/browse/CATROID-866
=> CATROID-866 Copying of several selected projects copies only the first in the list

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PlaySoundAndWaitBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PlaySoundBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/ProjectActivityTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameLookTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameProjectTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameSceneTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameSoundTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameSpriteTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/UiTestUtils.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/MultiViewSpriteAdapter.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/NfcTagListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/RecyclerViewFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SceneListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.java
https://jira.catrob.at/browse/CATROID-885
- As lists or variables in the data segment of the FormulaEditor and items from the backpack cannot be renamed in the current version, those are not affected by this ticket 
- Modify existing testcases to check the new behavior and add testcases to check if the renaming of a single item works without asking for a selection
- added `sleep()` before/after opening the menu to reduce flakiness of existing tests
=> CATROID-885 Make rename option single choice

catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickCategoryFragment.java
Remove "Toggle 2D" and "Reorder scripts" options when adding bricks.
https://jira.catrob.at/browse/CATROID-891
=> CATROID-891 remove catblocks options when adding bricks

catroid/src/androidTest/java/org/catrobat/catroid/test/content/controller/LookControllerTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/controller/SceneControllerTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/controller/SoundControllerTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/controller/SpriteControllerTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/content/messagecontainer/BackpackBroadcastMessageTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/utils/TestUtils.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.java
- Add testcase for unpacking a script that contains broadcast messages into a different scene
- outsource `clearBackPack()` test method to avoid code duplication
https://jira.catrob.at/browse/CATROID-886
=> CATROID-886 Preserve broadcast messages after copying via backpack

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/ReplaceExistingProjectDialogTest.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/ReplaceExistingProjectDialogFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/TextInputDialog.java
https://jira.catrob.at/browse/CATROID-881
- allow to name projects with a not used name when downloading an existing project
- show and hide keyboard in the dialog
- set text after setting the textwatcher in TextInputDialog to validate input in the beginning    
- add testcase
=> CATROID-881 "name already exists" logic reversed when downloading existing project

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/ChangeVariableTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/DeleteLookBrickTest.java
https://jira.catrob.at/browse/CATROID-925
ChangeVariableTest works without DragNDrop, which is not needed for the test
DeleteLookBrickTests made other test fail if it fails itself, because then Intent.release would not be called and every other test using Intent.init would get an exception.
=> CATROID-925 Fix flaky tests

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
When there were not scripts in the script list the app crashed. this should be fixed now.
https://jira.catrob.at/browse/CATROID-916
=> CATROID-916 Toggle 2D cause App crash if script is empty

catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.java
fixes: https://jira.catrob.at/browse/CATROID-924
The app crashes on pressing the undo button when you switch back to the looks tab (from the scripts or sounds tab) after editing a look! The app should either perform the undo operation or hide the undo button!
=> CATROID-924 app crashes on pressing the undo button after you switch tabs

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameLookTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameProjectTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameSoundTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameSpriteTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/SpriteListFragmentExplanationTextProjectWithObjectTest.java
Fixed the bug by changing the delete confirmation from `R.string.ok` to `R.string.delete.`
https://jira.catrob.at/browse/CATROID-933
=> CATROID-933 Failing tests

catroid/src/main/java/org/catrobat/catroid/content/actions/GoToTouchPositionAction.java
Actual Behaviour: On touch, the sprite first used to go to the x PointF, update the screen, then proceed to the y PointF.
Expected: Sprite should update to the required Point in one go
=> CATROID-875 Rendering bug with "Go to touch position"

catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
https://jira.catrob.at/browse/CATROID-943
The reason for this crash was adding a non-serializable object `textBlockFunctionProvider` to the serializable class `FormulaElement` without using the `transient` keyword.
=> CATROID-943 fix crash on selecting visual placement

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorFragmentHelpUrlTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/FormulaEditorCategoryListWrapper.java, catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java, catroid/src/main/res/drawable/ic_formula_editor_help.xml, catroid/src/main/res/menu/menu_formulareditor_category.xml
[CATROID-827](https://jira.catrob.at/browse/CATROID-827)
Added a button on the top bar of the Functions/Sensors/Logic/Properties submenus in the formula editor which opens the browser with the wiki page corresponding to the current submenu.
=> CATROID-827 Help links to wiki in formula editor

catroid/build.gradle, catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
Temporary build flag FEATURE_USER_REPORTERS_ENABLED to hide user defined reporter functions in release APKs.
https://jira.catrob.at/browse/CATROID-976
=> CATROID-976 Build flag for user defined reporter functions

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/OpenUrlBrickTest.java
Ticket: https://jira.catrob.at/browse/CATROID-979
Fix failing testOpenUrlIntent
=> CATROID-979 Fix failing testOpenUrlIntent

catroid/src/main/java/org/catrobat/catroid/ProjectManager.java, catroid/src/test/java/org/catrobat/catroid/test/content/project/LoadProjectsTest.java
Added a conversion in the load project function.
=> CATROID-977 Fix crash with old "Set background to number __" brick (and its "and wait" variant)

catroid/src/main/java/org/catrobat/catroid/stage/StageLifeCycleController.java
The stageActivity.brickDialogManager can be null and this causes a NullPointerException. 
Fixed it by adding a null check and also added null checks to other members that could be null.
https://jira.catrob.at/browse/CATROID-1018
=> CATROID-1018 NullPointerException when calling brickDialogManager

catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
In the standalone APKs, the dialog for our Terms of Use and Service is shortly shown, but then the app does not wait till the user taps on one of the buttons.
https://jira.catrob.at/browse/CATROID-1007
=> CATROID-1007 Terms of use and service incorrectly shown too shortly in standalone APKs

Jenkinsfile
This PR helps so that the whole pipeline doesn't break.
Until now when the unit tests fail, the coverage XML is never created and the suites after that all get an error on the log.
https://jira.catrob.at/browse/DEVOPS-478
=> Test runs fail, if single test fails

catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivityOnTabSelectedListener.kt
https://jira.catrob.at/browse/CATROID-1020
=> CATROID-1020 Crash in org.catrobat.catroid.ui.SpriteActivityOnTabSelectedListenerKt.removeTabLayout

catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
FATAL EXCEPTION when tapping the back button while "Ask ... spoken" brick is executed
https://jira.catrob.at/browse/CATROID-1027
=> CATROID-1027 FATAL EXCEPTION on back button with "Ask ... " brick

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/NfcTagListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/RecyclerViewFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SceneListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.java
Fixed crash in RecyclerViewFragment.onPrepareOptionsMenu and SpriteListFragment.onPrepareOptionsMenu.
https://jira.catrob.at/browse/CATROID-1029
=> CATROID-1029 Crash in RecyclerViewFragment.onPrepareOptionsMenu

catroid/src/main/java/org/catrobat/catroid/content/bricks/PlaySoundAndWaitBrick.java
https://jira.catrob.at/browse/CATROID-1037
Fix NullPointerException in PlaySoundAndWaitBrick
=> CATROID-1037 Fix NullPointerException in PlaySoundAndWaitBrick

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/EmptyEventBrickTest.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/EmptyEventBrick.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/BrickAdapter.java
Fixed the bug by not setting the empty event brick as disabled but just coloring it that way.
https://jira.catrob.at/browse/CATROID-1008
=> CATROID-1008 Bricks below empty event bricks (from Catblocks) shall not be set to disabled

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
Ticket: https://jira.catrob.at/browse/CATROID-1047
App crashes on going into split-screen view in the ScriptFragment
=> CATROID-1047 App crashes on going into split screen view in the ScriptFragment

catroid/src/main/java/org/catrobat/catroid/utils/TextBlockUtil.java
Changed the value of the sensor variable X to Y and Y to -X.
https://jira.catrob.at/browse/CATROID-958
I tested the work on the Honor 9i android device.
Signed-off-by: ritiksp2411 <ritik.rjt@gmail.com>
=> CATROID-958 Textblock detection x and y sensors return the wrong value

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/DisableHintDialogTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/hints/Android9SnackbarRegressionTest.java, catroid/src/main/java/org/catrobat/catroid/common/SharedPreferenceKeys.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.java, catroid/src/main/java/org/catrobat/catroid/utils/SnackbarUtil.java, catroid/src/main/res/values/strings.xml
Implement a dialog that asks the user if they want to enable or disable hints. The dialog is shown only once, right before the first hint would be shown and will not be shown again if the user changes the hint settings afterwards.
https://jira.catrob.at/browse/CATROID-921
=> CATROID-921 Disable Hints dialog

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/looks/gallery/SpriteFromGalleryIntentTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/looks/paintroid/PocketPaintNewSpriteIntentTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/NewSpriteVisuallyPlaceDialogTest.kt, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/SpriteListFragmentExplanationTextNoObjectsProjectTest.java, catroid/src/main/java/org/catrobat/catroid/common/SharedPreferenceKeys.java, catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/NewSpriteDialogFragment.kt, catroid/src/main/res/layout/dialog_new_sprite.xml, catroid/src/main/res/values/strings.xml
Ticket: https://jira.catrob.at/browse/CATROID-189
Added switch for placing newly created sprite visually
=> CATROID-189 Visual placement interface in the object creation workflow

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/MainMenuFragment.kt
https://jira.catrob.at/browse/CATROID-1046
=> CATROID-1046 Touch area to enter project from main page is too small

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorUndoTest.java, catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/content/Project.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
https://jira.catrob.at/browse/CATROID-1056
When loading the old values of the variables after an undo a deep copy of all the uservariables was restored. This leads to the problem that there are now two instances of the same uservariable (one in the uservariable list of the project and one that is actually stored within the bricks). In order to fix this after performing an undo the uservariables are not copied in a deep manner but just the values are restored (so that the references do not change).
Additionally changed the test `FormulaEditorUndoTest` to also check if the uservariable references stay the same after an undo.
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of …
=> CATROID-1056 Fix wrong variable references after undo

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/stage/DeleteSpriteCloneTest.kt, catroid/src/main/java/org/catrobat/catroid/content/Scene.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/CloneBrick.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SpriteController.java
https://jira.catrob.at/browse/CATROID-1051
If the sprite that was used for the clone brick was deleted a clone of the current sprite will be created instead (which was also the default implementation if the sprite to clone was null)
=> CATROID-1051 Fix crash when deleting sprite of clone

catroid/src/androidTest/java/org/catrobat/catroid/test/content/controller/SpriteControllerTest.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
The issue in the ticket does not come from copying itself, but from moving the Sprite into a Group. Thereby the Sprite is converted to a GroupItemSprite and all the variables, looks, etc. copied. However it was forgotten to also copy the list of UserDefinedBricks there, leading to the issue that the UserDefinedBricks get lost when the corresponding Sprite is moved into a Group.
- Added further testcase for the conversion of Sprites to GroupItemSprites to existing test
https://jira.catrob.at/browse/CATROID-1063
=> CATROID-1063 Fix UserDefinedBricks lost when converting to GroupItemSprite

catroid/src/androidTest/java/org/catrobat/catroid/test/content/controller/SceneControllerTest.java, catroid/src/main/java/org/catrobat/catroid/content/Scope.kt, catroid/src/main/java/org/catrobat/catroid/sensing/ColorAtXYDetection.kt, catroid/src/main/java/org/catrobat/catroid/sensing/ColorCollisionDetection.kt, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.java
This bug happens when bricks with user defined data (variables, lists) get packed and a new scope is instantiated in the process. Fixed the bug by allowing a null pointer for the project in the scope. (This is necessary because when packing the script does not belong to any project). Added a userlist, a uservariable and a userdata brick type which are leading to this problem to the scenecontroller test.
https://jira.catrob.at/browse/CATROID-1019
=> CATROID-1019 Crash in org.catrobat.catroid.content.Scope

catroid/src/test/java/org/catrobat/catroid/test/content/actions/ChangeColorByNActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/ChangeSizeByNActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/ChangeTransparencyByNActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/ChangeVolumeByNActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/ChangeYByNActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/ForVariableFromToActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/ForeverActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/GlideToActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/MoveNStepsActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/PlaceAtBrickTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/PointInDirectionActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/RepeatActionTest.kt, catroid/src/test/java/org/catrobat/catroid/test/content/actions/SetColorActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/SetSizeToActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/SetTransparencyActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/SetVolumeToActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/SetXActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/SetYActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/WriteVariableToFileActionTest.kt, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CloneBrickWithFormulaTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickBroadcastMessageTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickVariableUpdateTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickWithSecondaryListBroadcastMessageTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickWithSecondaryListTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/bricks/CompositeBrickWithSecondaryListUpdateTest.java
Locally null pointer exceptions occur when executing single tests.
When executing multiple tests at once many tests do not fail even if they should.
This behaviour occured because of the wrong usage of the Junit class instead of the PowerMockRunner class.
https://jira.catrob.at/browse/CATROID-996
=> CATROID-996 Fix null pointer exceptions on local unit tests

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CopyBrickTest.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/BrickAdapter.java
https://jira.catrob.at/browse/CATROID-1066
- disable checkboxes of UserDefinedScripts in the selection process for copy
- add testcase to verify the added behavior
=> CATROID-1066 Disable copying of UserDefinedScripts

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/DeleteLookBrickTest.java
Intruduced a function to poll if the view is available.
https://jira.catrob.at/browse/CATROID-928
=> CATROID-928 Fix testPaintLookWithoutDelete in DeleteLookBrickTest.java

catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java, catroid/src/test/java/org/catrobat/catroid/test/stage/AddCloneActorStageTest.kt
- Fixed ArrayIndexOutOfBoundsException in StageListener.java:282. ( @CodeChamp-SS )
- Change code structure to make new behavior testable
- Add testcase
=> CATROID-1042 Fix ArrayIndexOutOfBoundsException in StageListener

catroid/build.gradle
I am not sure if I 100% understood the more future proof way. So this way when Paintroid is built with the Catroid Flag ("paintroidLocal") on Jenkins, the artifacts get stored by MavenLocal and then will be used to build the Catroid project. If the flag is not set (basically the usual build), Catroid will use its local paintroid libs. 
Here is a PR where I added a Toast in the MainActivity to verify that the building would work with Catroid.
https://github.com/Catrobat/Paintroid/pull/909
https://jira.catrob.at/browse/PAINTROID-248
=> PAINTROID-248 Make "BUILD_WITH_CATROID" flag work again on Jenkins

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/BrickAdapter.java
Deleted all "empty" event bricks that do not have associated bricks in their script.
https://jira.catrob.at/browse/CATROID-971
=> CATROID-971 Unused "empty" event bricks shall be discarded

catroid/src/main/java/org/catrobat/catroid/stage/PenActor.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SpriteController.java
Cloned sprites are not added to the currently playing scene which was used for getting the sprites and then drawing.
Fixed the bug by using the sprites of the sprite list contained in the stage listener(Which also performs the cloning process).
Also contains a fix that when the pen is down and the sprite is cloned, that the pen is also down for the cloned sprite.
https://jira.catrob.at/browse/CATROID-805
=> CATROID-805 Pen down and stamp ignored for clones

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/BrickAdapter.java
Made drawable mutable before setting the grayscale
https://jira.catrob.at/browse/CATROID-1134
=> CATROID-1134 Disabled Bricks are incorrectly showed as enabled

catroid/src/androidTest/java/org/catrobat/catroid/test/stage/SearchParameterTest.java, catroid/src/main/java/org/catrobat/catroid/ui/ScriptFinder.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java, catroid/src/main/res/values/strings.xml
Ticket: https://jira.catrob.at/browse/CATROID-1112
1. Disable search when the query is empty
2. Changed variable naming scheme in ScriptFinder to make them easier to understand.
=> CATROID-1112 Topbar disappears in script search

catroid/src/androidTest/java/org/catrobat/catroid/test/content/controller/SceneControllerTest.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SceneController.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SceneListFragment.java
- deleting a scene previously only deleted the corresponding directory -> also delete the instance within ProjectManager
- adapt already existing testcase to check for deleting a scene after a renaming
- adding a new scene and immediately renaming it without opening it once before, sometimes leads to the warning that the scene cannot be renamed -> also fixed by this PR
https://jira.catrob.at/browse/CATROID-888
=> CATROID-888 Fix deleting a scene after renaming

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorUndoTest.java
https://jira.catrob.at/browse/CATROID-1151
- Add a second `pressBack()` as the first one just dismisses the copy/paste dialog which was introduced with the ticket https://jira.catrob.at/browse/CATROID-826. 
=> CATROID-1151 Fix undo test after renaming a variable

Jenkinsfile, Jenkinsfile.releaseAPK, catroid/build.gradle, catroid/src/catroid/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/embroideryDesigner/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/lunaAndCat/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java, catroid/src/main/res/xml/ai_preferences.xml, catroid/src/main/res/xml/ev3_preferences.xml, catroid/src/main/res/xml/nxt_preferences.xml, catroid/src/mindstorms/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/mindstorms/java/org/catrobat/catroid/common/defaultprojectcreators/DefaultExampleProject.java, catroid/src/mindstorms/res/values/strings.xml, catroid/src/phiro/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/pocketCodeBeta/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/standalone/java/org/catrobat/catroid/common/FlavoredConstants.java, fastlane/Fastfile
https://jira.catrob.at/browse/CATROID-448
- add mindstorms flavor
- additionally enable all AI extensions for Phiro flavor
- outsource `CATROBAT_HELP_URL` to a constant for each flavor
=> CATROID-448 Mindstorms flavor

catroid/gradle/setup_jacoco.gradle
https://jira.catrob.at/browse/DEVOPS-491
Fixes a small bug in gradle task. The subdirectory where the class-files
for Kotlin classes are dumped starts with a lower case letter
(camel case). In the gradle task however it was defined capitalized.
For that reason the class-files were not found and therefore not
included in the coverage report.
=> DEVOPS-491 Include Kotlin classes in coverage report

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CopyGroupSpriteTest.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/RVAdapter.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SpriteController.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.java
https://jira.catrob.at/browse/CATROID-1064
- Also fixes problem if two different sprites are copied (e.g. one normal Sprite and one GroupItemSprite). Previously this led to weird behavior like intended GroupItemSprites without a parent GroupSprite. 
=> CATROID-1064 Fix invisible GroupItemSprite after copy

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/NavigateUpTest.kt, catroid/src/main/java/org/catrobat/catroid/ui/BaseActivity.kt
https://jira.catrob.at/browse/CATROID-1179
Fixed bug by correcting Button id from "R.id.home" to "android.R.id.home".
=> CATROID-1179 Fix Back Button not working in all Fragments

catroid/src/androidTest/java/org/catrobat/catroid/test/formulaeditor/SensorHandlerTest.kt, catroid/src/main/java/org/catrobat/catroid/formulaeditor/SensorHandler.java, catroid/src/main/java/org/catrobat/catroid/stage/StageLifeCycleController.java
https://jira.catrob.at/browse/CATROID-1171
Fixed Memory Leak by destroying SensorHandler when StageActivity is destroyed.
To compile with Leak Canary see: https://jira.catrob.at/browse/CATROID-1171?focusedCommentId=25921&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25921
=> CATROID-1171 Fix Memory Leak in SensorHandler at sensorManager

catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
https://jira.catrob.at/browse/CATROID-1178
Fixed the Memory Leaks by changing static variables to non-static in the FormulaEditorFragment. Android Studio already gave the hint that Android Context classes should not be used in a static field, since this is a memory leak.
=> CATROID-1178 Fix Memory Leaks of SpriteActivity in FormulaEditorFragment

catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/ImportObjectIntoProject.kt, catroid/src/main/java/org/catrobat/catroid/ProjectManager.java, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/NewSpriteDialogFragment.kt
https://jira.catrob.at/browse/CATROID-1125
- implementation of the functionality
- possible conflicts: local and global variables with the same name
- conflict occurs: abort the import
- test cases for conflicting and nonconflicting imports
Ticket #1128 has also been solved in this merge already (https://jira.catrob.at/browse/CATROID-1128) 
=> CATROID-1125 Add single-object to current scene

catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java, catroid/src/main/java/org/catrobat/catroid/content/actions/SpeakAndWaitAction.kt, catroid/src/main/java/org/catrobat/catroid/content/bricks/SpeakAndWaitBrick.java, catroid/src/main/java/org/catrobat/catroid/stage/SpeechSynthesizer.kt, catroid/src/test/java/org/catrobat/catroid/test/content/actions/SpeakActionTest.java, catroid/src/test/java/org/catrobat/catroid/test/content/actions/SpeakAndWaitActionTest.kt
Seperated Speak Action and Speak and Wait Action as one is asynchronous and the other blocking.
Length of sound file must be discovered at runtime as formula expressions, e. g. variables, change
values during execution.
https://jira.catrob.at/browse/CATROID-1186
=> CATROID-1186 Fix Speak and wait bug

catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java, catroid/src/mindstorms/java/org/catrobat/catroid/common/FlavoredConstants.java
https://jira.catrob.at/browse/CATROID-1188
=> CATROID-1188 Mindstorms flavor: NXT and EV3 brick categories are initially not visible

catroid/src/main/java/org/catrobat/catroid/ui/BrickLayout.java, catroid/src/main/res/layout/brick_assert_equals.xml, catroid/src/main/res/values/attrs.xml
- fixes issue that Textfields in multiline bricks cannot have different lengths and thus are not maximized to the end of the line
- change assert bricks such that both Textfields are in a new line and can be expanded to up to three lines
https://jira.catrob.at/browse/CATROID-1086
=> CATROID-1086 Fix length of assert input fields

catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickSearchFragment.kt
https://jira.catrob.at/browse/CATROID-1194
When the user searches for a Brick, recently used bricks are shown on top of the search results
=> Catroid-1194 prioritize recently used bricks in bricksearch

catroid/src/main/res/values/strings.xml
There was still one instance where "sprite" incorrectly hadn't been renamed to actor or object, which is hereby corrected.
=> Maintenance: Rename sprite(s) to actor(s)s or object(s)

catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
https://jira.catrob.at/browse/CATROID-1210
Because of the .catrobat extension of the downloaded project file, the project was not imported into the current project, but downloaded as a normal project and added to the project list.
=> CATROID-1210 wrong behaviour when importing objects from medialibrary

catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/io/XstreamSerializer.java, catroid/src/test/java/org/catrobat/catroid/test/xmlformat/SettingsXmlSerializerTest.kt
https://jira.catrob.at/browse/CATROID-1165
Fixed the issue by adding xstream aliases for EV3.class and EV3Port.class . Also added a test that prevents forgetting to add the aliases of newly added Settings and Ports.
=> CATROID-1165 Fix org.catrobat.catroid.content.LegoEV3Setting in code.xml

catroid/config/lint.xml, catroid/src/main/java/org/catrobat/catroid/ui/ScratchProgramDetailsActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/NfcTagAdapter.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/ProjectAdapter.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/RVAdapter.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/backpack/BackpackRecyclerViewFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/scratchconverter/ScratchSearchResultsFragment.java, catroid/src/main/res/drawable/ic_ripples.xml, catroid/src/main/res/layout/vh_sprite_group_item.xml, catroid/src/main/res/layout/vh_with_checkbox.xml, catroid/src/main/res/values/dimens.xml
Added visual "ripples" on the left to Objects, Actors, Looks and Sounds to indicate to the user that these blocks can be dragged up and down. Moved the icon and text a bit to the right to make place for the ripples.
=> CATROID-1092 Add ripples to Objects/Actors/Looks/Sounds

catroid/src/main/java/org/catrobat/catroid/ProjectManager.java, catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.java
https://jira.catrob.at/browse/CATROID-1180
reset Project references in ProjectManager when project gets closed. 
=> CATROID-1180 Memory Leak of SpriteActivity in ProjectManager.currentlyEditedScene

catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
Ticket: https://jira.catrob.at/browse/CATROID-1034
Face/Text detection stops working when transitioned to any other scene.
Not sure, but observing the logs, the `CameraManager` seemed to be inactive/paused during the time `startScene()` method of class `StageListener` was called while changing scenes. Hence, added `cameraManager.resume()` in `startScene()` to resume it. Here are the logs before and after the commit -
Before | After
-------| -----
=> CATROID-1034 Fix face/text detection bug

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/SayForBubbleBrickStageTest.java
Fix flaky SayForBubbleBrickStageTest with use of a timeout.
=> CATROID-1006 Fix flaky SayForBubbleBrickStageTest

catroid/build.gradle, catroid/src/androidTest/java/org/catrobat/catroid/test/formulaeditor/FlattenListTest.kt, catroid/src/main/java/org/catrobat/catroid/ProjectManager.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/Formula.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/Functions.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormula.java, catroid/src/main/res/values/strings.xml, catroid/src/test/java/org/catrobat/catroid/test/content/project/LoadProjectsTest.java
https://jira.catrob.at/browse/CATROID-850
Insert flatten(*list*) around all userlists when opening old projects where "flatten" was not yet available.
=> CATROID-850 Insert flatten(*list*) for backwards compatibility

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/OpenUrlBrickTest.java
https://jira.catrob.at/browse/CATROID-1211
Test fails because of the new added warning when the user enters a formula as text. (Logic operation OR was detected within the URL)
=> CATROID-1211 Fix failing testOpenUrlIntent

catroid/src/main/java/org/catrobat/catroid/content/actions/DeleteLookAction.kt
[CATROID-1230 - Fix testDeleteWebLook.catrobat](https://jira.catrob.at/browse/CATROID-1230)
Identified the error causing the deviation and fixed it
The sprite's look in the CLT is now properly deleted
=> CATROID-1230 Fix testDeleteWebLook.catrobat

catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java, catroid/src/main/res/layout/fragment_formula_editor.xml
Maximum lines of formula field is now 20
When toggling the functional-rows in the formula editor
the space between the layout of the formula editor and
the layout above is set accordingly.
Ticket: [CATROID-882](https://jira.catrob.at/browse/CATROID-882)
=> CATROID-882 Large unused empty area in formula editor

catroid/src/androidTest/java/org/catrobat/catroid/test/formulaeditor/InternFormulaTest.java, catroid/src/main/java/org/catrobat/catroid/utils/FormatNumberUtil.java
https://jira.catrob.at/browse/CATROID-1282
Crash happens because of trailing whitespaces ("0 ") in the conversion to a BigDecimal number, which throws a NumberFormatException.
=> CATROID-1282 Project crashes on edit object

catroid/src/main/res/layout/brick_set_camera_focus.xml
Changed size of brick "Become focus point with ..."
from medium to big.
Ticket: [CATROID-1268](https://jira.catrob.at/browse/CATROID-1268)
=> CATROID-1268 wrong size of brick_set_camera_focus

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/regression/activitydestroy/FormulaEditorFragmentActivityRecreateRegressionTest.java
[CATROID-1220](https://jira.catrob.at/browse/CATROID-1220)
Fix failing test. In the test the activity's `recreate()` method was used, which didn't guarantee recreation in a test environment. 
This has been replaced with `finish()` -ing and `restart()` -ing with the original Intent. Additionally general refactoring of the test was performed 
=> CATROID-1220 fix failing formula editor recreate activity test

catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickContextMenuTest.kt, catroid/src/main/java/org/catrobat/catroid/content/bricks/FormulaBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/UserDefinedBrick.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
https://jira.catrob.at/browse/CATROID-1231
- The "Edit Formula" item is now just visible for FormulaBricks that actually have a formula field
- Add a testcase to check if the items of the ContextMenu are correct for certain different bricks
=> CATROID-1231 Fix crash on Edit Formula for AssertBrick

Jenkinsfile, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/FormulaEditorComputeDialogComputationResultTest.kt
Jenkins testsuite fails with error "Category annotations on Parameterized classes are not supported on individual methods."
Fixed through annotating the categories for the whole instead for the (one and only) test in this file.
No change in behaviour, but now complies to rules
+ additionally changed the quarantined testsuite to always be triggert
=> Fix jenkins testsuite failing

catroid/src/androidTest/java/org/catrobat/catroid/test/stage/SearchParameterTest.java, catroid/src/androidTest/java/org/catrobat/catroid/test/ui/BrickSearchTest.kt, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SetVariableBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/utils/BrickVariableSpinnerDataInteractionWrapper.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/FormulaEditorDataListWrapper.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/FormulaEditorWrapper.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/utils/UserDataItemRVInteractionWrapper.java
[CATROID-1005](https://jira.catrob.at/browse/CATROID-1005)
Problem was: in many cases the entered string was truncated due to
too fast automated typing. Modify type string method to use replaceText
instead of doing them sequentially, since that way they might collide
with each other.
Another problem was: an alert message popped up that the string might
be a formula. This now gets dismissed if it pops up.
=> CATROID-1005 FATAL EXCEPTION: androidx.test.espresso.NoMatchingViewException

catroid/src/androidTest/java/org/catrobat/catroid/test/content/backpack/BackpackUserDefinedBricksTest.kt, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.kt, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
Copying userdefined bricks via the backpack results in copying the definition of the userdefined brick automatically now so that the userdefined brick can actually be used after unpacking in another sprite.
Additional remark: We also fixed another bug, where packing the backpack didn't work properly when doing it via the dialog that comes up when pressing and holding on a scriptblock. See changes in `ScriptFragment.java`
[CATROID-1272](https://jira.catrob.at/browse/CATROID-1272)
=> CATROID-1272 Copying Userdefined Bricks

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleEffectsTest.kt
https://jira.catrob.at/browse/CATROID-1295
Fix all failing particle effect tests. ParticleEffectsTest.particleEffectAfterSceneContinuesTest and
ParticleEffectsTest.particleEffectAfterSceneRestartsTest are failing regularly on jenkins.
=> CATROID-1295 Fix all failing particle effect tests

catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/PenDownActionTest.java, catroid/src/main/java/org/catrobat/catroid/content/PenConfiguration.java, catroid/src/main/java/org/catrobat/catroid/content/actions/GoToRandomPositionAction.java, catroid/src/main/java/org/catrobat/catroid/stage/PenActor.java
The Bug happened because in the PenConfiguration, the change of the Camera wasn`t taken into consideration.
I also found a small Bug where in the GoToRandomPosition Brick in Combination with PenDown it would always first change the x and then the y coordinate, which resulted in a wrong drawing of the Pen.
https://jira.catrob.at/browse/CATROID-1213
=> CATROID-1213 "Pen down" brick not working correctly

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/regression/activitydestroy/SpriteListFragmentActivityRecreateRegressionTest.java
https://jira.catrob.at/browse/CATROID-1359
=> CATROID-1359 Fix testActivityRecreateRenameSpriteDialog

catroid/src/androidTest/java/org/catrobat/catroid/test/content/bricks/BrickContextMenuTest.kt, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
Definitionbricks for Userdefined Bricks now have the option "add to backpack" in their context menu
https://jira.catrob.at/browse/CATROID-1339
=> CATROID-1339 "Add to backpack" option missing for "Define" bricks

catroid/src/androidTest/java/org/catrobat/catroid/test/content/controller/SceneControllerTest.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SceneController.java
https://jira.catrob.at/browse/CATROID-1374
- Added copying the screenshot of scenes for the backpack feature.
- If there exist a manual and an automatic screenshot, then only the manual screenshot is copied.
=> CATROID-1374 Scene View - image preview is not copied

catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/ImportObjectIntoProjectFromContextMenuTest.kt, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/MergeLocalSpriteTest.kt, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/merge/ImportProjectHelper.kt, catroid/src/main/java/org/catrobat/catroid/ui/ImportLaunchers.kt, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SpriteListFragment.kt, catroid/src/main/java/org/catrobat/catroid/utils/Utils.java, catroid/src/main/res/menu/menu_project_activity.xml, catroid/src/main/res/values/strings.xml
add looks ,scripts and sounds from a chosen local project to current sprite with unique names
New Test:
* MergeLocalSpriteTest
https://jira.catrob.at/browse/CATROID-1147
=> CATROID-1147 Merge local object into current

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/hints/HintsShownInCorrectActivityTest.kt, catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddBrickFragment.kt, catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickCategoryFragment.kt, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CatblocksScriptFragment.kt, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/LookListFragment.kt, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.kt, catroid/src/main/java/org/catrobat/catroid/utils/SnackbarUtil.java
When hints are enabled, the hint for the scripts is not dismissed yet and the formula editor is opened, the hint for the script hides the lower part of the screen, where hints for the formula editor are shown
https://jira.catrob.at/browse/CATROID-987
Additionally we looked through all hints and found out that other hints were shown in the wrong places aswell. All hints are now only shown in the Fragment/Activity they should be shown in.
=> CATROID-987 Overlapping hints in Formula Editor

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java, catroid/src/main/res/layout/fragment_list_view.xml
Adds padding to multiple scrollable views where floating buttons may cover-up essential functionalities
https://jira.catrob.at/browse/CATROID-847
=> CATROID-847 Floating + and play buttons may cover parameter field in lowest bricks

catroid/src/main/java/org/catrobat/catroid/stage/ShowBubbleActor.java, catroid/src/test/java/org/catrobat/catroid/test/utiltests/UtilsTest.java
Fixed issue, where line breaks in the think/say balloons were ignored.
The problem was, that the text is parsed into lines, but "\n" character
was treated as a regular character, and did not invoke a new line.
Added test to verify the changes.
This pull request fixes an issue, where line breaks from the think/say balloons were ignored, and adds a test to verify this change.
https://jira.catrob.at/browse/CATROID-1313
=> CATROID-1313 Line breaks and extra spaces are ignored in Say and Think word balloons

Jenkinsfile
Part of removal of standalone apk feature.
This removes the creation of a test standalone apk in jenkins runs for each PR.
=> DEVOPS-TASK: Remove the standalone test stage

catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/PenDownActionTest.java, catroid/src/main/java/org/catrobat/catroid/content/Look.java
Fixed this bug by using the correct user dimension units instead of the plain x and y's
https://jira.catrob.at/browse/CATROID-1375
=> CATROID-1375 Pen brick doesnt work correctly for x axis

catroid/src/androidTest/java/org/catrobat/catroid/ui/AssertEqualsBrickTest.kt, catroid/src/main/java/org/catrobat/catroid/content/actions/AssertEqualsAction.kt, catroid/src/main/java/org/catrobat/catroid/formulaeditor/Formula.java
Boolean formulas/operators/reporters show true/false instead of 1/0 in assert brick failure messages
https://jira.catrob.at/browse/CATROID-1308
=> Catroid-1308 Boolean formulas/operators/reporters should show true/false instead of 1/0 in assert brick failure messages

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameSpriteTest.kt, catroid/src/main/java/org/catrobat/catroid/content/Project.java, catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.kt
Jira ticket: https://jira.catrob.at/browse/CATROID-988
Object name could have the same name as background in another language, if corresponding language change was made is fixed. Also added uiespresso test to confirm implementation.
=> CATROID-988 Bug fixed, where object name and background can be equal

catroid/src/main/java/org/catrobat/catroid/content/bricks/UserDefinedBrick.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/BrickController.java
https://jira.catrob.at/browse/CATROID-1398
In BrickController in the "copy" function of bricks there was a if-Statement if the brick to clone is a UserDefined brick. If yes -> delete input formula of brick. I removed this if-Statement, because it doesn't make sense to delete the input formula.
=> CATROID-1398 Userdefined brick copy bug

catroid/build.gradle
Reverts Catrobat/Catroid#4510
Reason: defaultVersionCode 86 was already consumed last year in a release attempt.
=> Revert "Version increase for v1.1.0"

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorEditTextTest.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/DataListFragment.kt
When inserting a function or data into a formula in the FormulaEditor the preview in the brick was not updated correctly.
[CATROID-1384](https://jira.catrob.at/browse/CATROID-1384)
=> CATROID-1384 Continuously update parameter field in formula editor

catroid/src/main/res/values/dimens.xml
[CATROID-554](https://jira.catrob.at/browse/CATROID-554) 
Increased minWidth for DataView in Formula Editor.
=> CATROID-554 Data overview in formula editor becomes unusable

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectOptionsTest.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.kt
The ON/OFF state of the slider for the "Keep original aspect ratio" project option was reversed. ON should correspond to a project in MAXIMIZE screen mode, OFF should correspond to a project in STRETCH mode.
This PR only changes the state of the switch, not the screen mode of the project, otherwise all existing projects would have their screen mode reversed since the project options screen was released only with version 1.1.2.
https://jira.catrob.at/browse/CATROID-1422
=> CATROID-1422 Reverse "Keep original aspect ratio" project option

catroid/src/androidTest/java/org/catrobat/catroid/test/stage/SearchParameterTest.java, catroid/src/main/java/org/catrobat/catroid/ui/ScriptFinder.kt, catroid/src/main/res/layout/view_script_finder.xml, catroid/src/main/res/menu/menu_script_activity.xml, catroid/src/main/res/values/strings.xml
Ticket 1: https://jira.catrob.at/browse/CATROID-1416 -> [cc19d76](https://github.com/Catrobat/Catroid/pull/4535/commits/cc19d76a9859fa7028d6d9fb35b17587008e7f8a)
Ticket 2: https://jira.catrob.at/browse/CATROID-1415 -> [70f39df](https://github.com/Catrobat/Catroid/pull/4535/commits/70f39df5f1d30f8d691264f9c0ffdc23fb540710)
Also:
added support to start search on pressing the enter key on the soft keyboard
Changed enter key icon to search instead of "next".
-> [22308cb](https://github.com/Catrobat/Catroid/pull/4535/commits/22308cb51f37d9ef0f3e2484071d0c5986212fad)
=> CATROID-1416 "Find/search" in Scripts should ignore trailing spaces

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameSceneTest.kt, catroid/src/main/java/org/catrobat/catroid/sensing/CollisionPolygonCreationTask.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/RecyclerViewFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SceneListFragment.kt
https://jira.catrob.at/browse/CATROID-1420
- The path for the images and the sounds were not updated instantly after renaming the scene
=> CATROID-1420 [HIGH-PRIORITY] Looks in scenes becomes corrupted after renaming the scene

catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java, catroid/src/main/java/org/catrobat/catroid/content/actions/SetCameraFocusPointAction.kt, catroid/src/main/java/org/catrobat/catroid/content/bricks/SetCameraFocusPointBrick.kt, catroid/src/test/java/org/catrobat/catroid/test/content/actions/SetCameraFocusPointActionTest.java
https://jira.catrob.at/browse/CATROID-1419
=> CATROID-1419 [HIGH-PRIORITY] Crash with formulas in parameter fields of "Become focus point with x y flexibility"

catroid/build.gradle, fastlane/Fastfile
The "upload to Google Play alpha" fastlane script could not find the signed apk of Pocket Code.
=> MAINTENANCE: Fix release filename issue

catroid/src/main/java/org/catrobat/catroid/visualplacement/VisualPlacementActivity.java
https://jira.catrob.at/browse/CATROID-1417
Added super.onCreate(null) instead of savedInstance -> this will suppress any saved data on create/recreate cycle of an Activity and avoid fragment auto re-creation.
=> CATROID-1417 Bug fixed where visual placement is skipped

catroid/src/androidTest/java/org/catrobat/catroid/test/ui/BrickSearchTest.kt, catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickSearchFragment.kt, catroid/src/main/res/layout/fragment_brick_search.xml, catroid/src/main/res/xml/searchable.xml
https://jira.catrob.at/browse/CATROID-1196
Implement search history for the brick search showing recently used search queries to the user
=> Catroid-1196 Implement search history for the brick search 

catroid/config/lint-baseline.xml, catroid/src/main/java/org/catrobat/catroid/io/StorageOperations.java
=> [HOTFIX] Resolve Static Analysis Warning

Jenkinsfile
changed hardcoded arguments for pipeline Agents to the unused DockerParameters Members and added mounting from the jenkins workers for the huawei files 
https://jira.catrob.at/browse/DEVOPS-694
=> DEVOPS-694 fixed DockerParameters

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/SetPenColorBrickNumberTest.java
Fixed by removing wrong and unnecessary condition in the test
https://jira.catrob.at/browse/CATROID-1471
=> CATROID-1471 Test: testPickColorCancel fails

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/PhiroColorBrickNumberTest.java
Fixed by removing wrong and unnecessary condition in the test
https://jira.catrob.at/browse/CATROID-1470
=> CATROID-1470 Test: testPhiroLightRGBPickColorCancel fails

catroid/src/catroid/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/createAtSchool/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/embroideryDesigner/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/lunaAndCat/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/mindstorms/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/phiro/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/pocketCodeBeta/java/org/catrobat/catroid/common/FlavoredConstants.java, catroid/src/standalone/java/org/catrobat/catroid/common/FlavoredConstants.java
https://jira.catrob.at/browse/CATROID-1465
Fixed the problem, that after downloading a sprite from the Library the sprite gets added as a new project. Had to use the BASE_APP_URL_HTTPS and some other checks in order to ensure that we download a valid sprite,
=> CATROID-1465 Add sprite from library gets downloaded to current project

catroid/src/main/AndroidManifest.xml
Fix issue that Request Install Permissions were not removed in the apk
=> Fix Removing Request Install Permissions

catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/DeleteImportedSpriteTest.kt, catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/ImportObjectIntoProjectFromContextMenuTest.kt, catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/ImportObjectIntoProjectTest.kt, catroid/src/androidTest/java/org/catrobat/catroid/test/merge/MergeTestUtils.kt, catroid/src/androidTest/java/org/catrobat/catroid/test/utils/TestUtils.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/util/UiTestUtils.kt, catroid/src/main/java/org/catrobat/catroid/content/Sprite.java, catroid/src/main/java/org/catrobat/catroid/merge/ImportProjectHelper.kt, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/SpriteController.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.kt
Fixes bug that deletes file when deleting imported object.
File also got deleted for original sprite.
https://jira.catrob.at/browse/CATROID-1493
=> CATROID-1493 Fix Look gets deleted in all projects

catroid/build.gradle
Android Studio versions > 2021.1.1 (Bumblebee) had the issue of not be able to resolve some of the import links. 
When using a newer Android Studio version this PR should fix this error by adding a test implementation dependency to the main project.
Second step was to enable all Gradle tasks (only needs to be done if not all Gradle tasks are visible):
1. Go to Android Studio `File -> Settings`
2. Left side go to `Experimental -> Gradle` 
3. Uncheck all 4 options under the Gradle option 
=> [MAINTENANCE] Fix for cannot resolve symbol error IDE version > 2021.1.1

catroid/src/main/res/drawable/brick_note_1h.xml, catroid/src/main/res/layout/brick_note.xml, catroid/src/main/res/values-v25/styles.xml, catroid/src/main/res/values/colors.xml
Change the color of the NoteBrick to a darker one, so that it stands out from the other control bricks.
https://jira.catrob.at/browse/IDE-108
=> IDE-108 Catroid Change Notes Brick Color

catroid/src/lunaAndCat/res/values/colors.xml
Changed the color of Actors and Object in Luna and Cat to #EAB7D5 so that it is consistent with the the other text colors.
https://jira.catrob.at/browse/IDE-103
=> IDE-103 changed color of Actors and Object to #EAB7D5

.github/workflows/sync_crowdin.yml
https://jira.catrob.at/browse/CATROID-1564
The GitHub-action used to create PRs containing translations from crowdin fails. For Paintroid this issue was solved by increasing the version of the GitHub-action. This PR does the same for Catroid.
=> CATROID-1564 Increase version of the crowdin GitHub action

catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDataToUserDefinedBrickFragment.kt
Bugfix: adding user defined brick crashes the app.
https://jira.catrob.at/browse/IDE-11
=> CATROID-IDE-11 Adding User Defined Bricks Crashes App

catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
The test was failing because the back button in the formula editor was not set active again after exiting the function menu. I fixed this adding a call to set it active if necessary. Now the behaviour should be as intended and the test passes.
https://jira.catrob.at/browse/CATROID-1479
=> CATROID-1479 Test: testFunctionDeletion fails

catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
https://jira.catrob.at/browse/IDE-184
Problem was: Screenshotheight/width was not properly initialized in all cases. - This caused the projection matrix to be 0, thus causing the stitching patterns to disappear.
Moved initialization out of the switch s.t. it occurs in all cases.
=> IDE-184 Unexpected Behaviour in Exported Embroidery Project

catroid/src/androidTest/java/org/catrobat/catroid/test/devices/mindstorms/nxt/LegoNXTImplTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/rtl/RtlBrickTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorSensorListTest.kt, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/SettingsFragmentTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/LegoSensorPortConfigDialogTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/regression/activitydestroy/LegoConfigDialogActivityRecreationRegressionTest.java, catroid/src/main/java/org/catrobat/catroid/common/Constants.java, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/AppStoreDialogFragment.kt, catroid/src/main/java/org/catrobat/catroid/ui/settingsfragments/Ev3SensorsSettingsFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/settingsfragments/NXTSensorsSettingsFragment.java, catroid/src/main/java/org/catrobat/catroid/ui/settingsfragments/SettingsFragment.java, catroid/src/main/res/layout/dialog_google_play.xml, catroid/src/main/res/values/strings.xml, catroid/src/main/res/xml/ev3_preferences.xml, catroid/src/main/res/xml/nxt_preferences.xml, catroid/src/main/res/xml/preferences.xml, catroid/src/test/java/org/catrobat/catroid/test/robolectric/bricks/BrickAddCategoryTest.java
Instead of being able to toggle the extension on and off a dialog for downloading the extension's app is shown. Depending of the extension
Remark: We expanded the `SettingsFragmentTest` so the this functionality can be tested, but we didn't find a way to automatically test the different flavors!
Remark: Some apps are not available in the Huawai Appgallery, so we put in the link to pocket code in those dialogs for now!
https://jira.catrob.at/browse/CATROID-1199
=> CATROID-1199 Link to flavors from settings

catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
Fixed GMS for the StartListeningBrick on Huawei phones.
Since GMS for the AskSpeechBrick was already working, the same concept is now also used for the StartListeningBrick.
Since Huawei phones should be using HMS anyways once it's implemented, the applied fix should be redundant as soon as this is the case.
[Ticket](https://jira.catrob.at/browse/CATROID-1413)
=> CATROID-1413 Fix GMS Speech Recognition on Huawei Phones

catroid/src/main/java/org/catrobat/catroid/content/Look.java, catroid/src/main/java/org/catrobat/catroid/physics/PhysicsLook.java, catroid/src/main/java/org/catrobat/catroid/physics/PhysicsObjectStateHandler.java
Extracted PhysicsObjectStateHandler from PhysicsLook.
Reduce Code Duplication and Magic Number Usage, and general
Code Cleanup in PhysicsLook
This pull request extracts PhysicsObjectStateHandler from PhysicsLook, reduces Code Duplication and Magic Number usage in PhysicsLook.
https://jira.catrob.at/browse/CATROID-1057
=> CATROID-1057 REFACTOR Look/PhysicsLook

catroid/src/main/java/org/catrobat/catroid/content/WhenBounceOffScript.java
https://jira.catrob.at/browse/IDE-14 (ticket was moved / renamed)
Null values aren't serialized so they are basically missing in the XML. Changed the string to be class internally empty. To dont have confilcts with access from other code parts the getter methods are transformed to retunr null values if the string is empty. This is necessary because other code parts are calculating with "If spriteName == null ..." and do actions based on this null check.
=> IDE-14 XML issue with WhenBounceOff-Brick (Catblocks related)

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameSpriteTest.kt, catroid/src/main/java/org/catrobat/catroid/ui/BaseActivity.kt
https://jira.catrob.at/browse/IDE-43
This test only works when the OS language of the emulator or device is set to English. Somehow the project gets created in the OS language whilst menus are translated according to setLanguageSharedPreference(...). This test is used to test functionality after switching language, this means if OS language is not set to english it probably wont work.
=> Catroid-1473 Resolve flakiness in RenameSpriteTest

catroid/src/androidTest/java/org/catrobat/catroid/test/devices/multiplayer/MultiplayerTest.kt, catroid/src/main/java/org/catrobat/catroid/devices/multiplayer/Multiplayer.kt
The Bluetooth connection should be kept as long as the user doesn't exit Catroid or until the Bluetooth connection is otherwise stopped by the user.
https://jira.catrob.at/browse/CATROID-1319
Removed disconnect in isDeviceConnectedAndAlive to keep connection open.
=> CATRIOD-1319: Multiplayer Bluetooth connection should be kept as long as possible 

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/AddNewActorOrLookDialogTest.kt, catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.kt, catroid/src/main/res/layout/dialog_new_actor.xml, catroid/src/main/res/values/strings.xml
Adds a new option in the "new Object and Actors" dialog to create an empty object. Also adds a test in AddNewActorOrLookDialogTest.kt
https://jira.catrob.at/browse/CATROID-1353
=> CATROID-1353 Create Empty Object Option

catroid/src/androidTest/java/org/catrobat/catroid/test/BricksHelpUrlTest.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/EndBrick.kt, catroid/src/main/java/org/catrobat/catroid/content/bricks/ForItemInUserListBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ForVariableFromToBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/ForeverBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/IfLogicBeginBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/IfThenLogicBeginBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/PhiroIfLogicBeginBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/RepeatBrick.java, catroid/src/main/java/org/catrobat/catroid/content/bricks/RepeatUntilBrick.java, catroid/src/test/java/org/catrobat/catroid/test/xmlformat/BricksXmlSerializerTest.java, catroid/src/test/java/org/catrobat/catroid/test/xmlformat/ClassDiscoverer.java
- Create class EndBrick
- Remove inner class in composite bricks EndBrick and use constructor of new class instead
- Affected composite bricks: ForItemInUserListBrick, ForVariableFromToBrick, ForeverBrick, IfLogicBeginBrick, IfThenLogicBeginBrick, PhiroIfLogicBeginBrick, RepeatBrick, RepeatUntilBrick
https://jira.catrob.at/browse/IDE-198
=> IDE-198 Refactor End Bricks from all Composite Bricks

catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CatblocksScriptFragment.kt, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
Fixed a bug bug where the 1D Script View is reset to English, when language was changed before.
https://jira.catrob.at/browse/IDE-166
Added SettingsFragment.setToChosenLanguage() in onCreateView of ScriptFragment so that the previously selected language gets applied.
=> IDE-166 Fix Bug where 1D Script View is reset to English

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/ProjectUploadDialogTest.kt, catroid/src/main/java/org/catrobat/catroid/ui/controller/ProjectUploadController.kt
fix testUploadControllerGetsCalled
This TC was broken by another unrelated TC: testUploadControllerGetsCalled
We fixed this TC and now testUploadControllerGetsCalled is working.
https://jira.catrob.at/browse/IDE-143
=>  IDE-143 fix testUploadControllerGetsCalled 

catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/SpriteTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/RenameSpriteTest.kt, catroid/src/main/java/org/catrobat/catroid/content/Project.java
https://jira.catrob.at/browse/IDE-130
Remove `spriteEqualBackgroundTest` as an uiespresso test, instead implement as an Unit Test. In `checkIfSpriteNameEqualBackground` use Context instead of Activity. This allows calling the necessary function -> `checkIfSpriteNameEqualBackground(Context context)` from the new test. Furthermore it is a cleaner solution to use the context instead of activity. 
=> IDE-130 Fix spriteEqualBackgroundTest

catroid/src/androidTest/java/org/catrobat/catroid/test/content/sprite/DeleteImportedSpriteTest.kt, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/looks/gallery/LookFromGalleryIntentTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/looks/gallery/SpriteFromGalleryIntentTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/sounds/gallery/SoundFromGalleryIntentTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/stage/LookUndoTest.java, catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectOptionsTest.java
- some tests reference a directory which does not exists. This is now fixed by using a temporary directory.
Jira Ticket: https://jira.catrob.at/browse/CATROID-1597
=> CATROID-1597 - Fix error where directory does not exist in test

catroid/src/main/java/org/catrobat/catroid/ui/controller/BackpackListManager.java
Fix Instance creation error by checking if directory exists after mkdir and not relying on mkdir return value.
https://catrobat.atlassian.net/browse/IDE-232
=> IDE-232 Fix Instance creation error in BackpackListManager

catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java, catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormula.java, catroid/src/main/java/org/catrobat/catroid/ui/FormulaEditorClipboard.kt, catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java, catroid/src/test/java/org/catrobat/catroid/test/ui/FormulaEditorClipboardTest.kt
Copy whole content in formula editor when nothing is selected, respectively paste at the position of the pointer.
When a part is selected, copy only this part, respectively overwrite this selection with the clipboard content, when pasting.
https://jira.catrob.at/browse/IDE-177
=> IDE-177 Link cut and copy to new buttons

catroid/src/main/java/org/catrobat/catroid/stage/StageActivity.java
https://catrobat.atlassian.net/browse/CATROID-1604
Fixes a bug of the resize-button in the Stage dialog. With this fix the button can again be used to stretch/maximize the project for the target device's screen dimensions.
=> CATROID-1604 Fix resize/maximize button

catroid/src/main/java/org/catrobat/catroid/stage/ScreenshotSaver.kt
https://jira.catrob.at/browse/IDE-127
This PR reduces the dimensions of the screenshot used for thumbnails to a maximum of 480x480 pixels by resizing the bitmap while keeping the aspect ratio of the original screenshot.
=> IDE-127 reduce thumbnail screenshot dimensions

catroid/src/main/java/org/catrobat/catroid/io/ProjectAndSceneScreenshotLoader.java, catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
If a manual screenshot exists for scenes or the project, the automatic screenshot is deleted and no new automatic screenshot will be created. 
https://jira.catrob.at/browse/IDE-129
=> IDE-129 delete automatic screenshot if manual screenshot exists

catroid/src/main/java/org/catrobat/catroid/ui/dragndrop/BrickListView.kt, catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/BrickAdapter.kt, catroid/src/test/java/org/catrobat/catroid/test/ui/brickadapter/EndBrickDragAndDropTest.kt
Fix behaviour of drag and dropping the end bricks of "C" and "E" form bricks, e.g., loops and if-then-else bricks etc., and add tests.
https://catrobat.atlassian.net/browse/IDE-69
=> IDE-69 End of enclosing bricks (loops, conditionals etc) can't be moved

catroid/build.gradle, catroid/src/main/java/org/catrobat/catroid/CatroidApplication.java
Since the min SDK is 28, it is no longer necessary to use the Multidex library.
See the following for more info: https://developer.android.com/build/multidex#mdex-on-l
=> Remove Multidex usages

catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorSensorListTest.kt, catroid/src/main/java/org/catrobat/catroid/formulaeditor/GpsStatusHandler.kt, catroid/src/main/java/org/catrobat/catroid/formulaeditor/SensorHandler.java
Fixed the crashing of the geolocation sensors by using the GnnsStatus instead of the deprecated GpsStatus.
https://catrobat.atlassian.net/browse/CATROID-1605
=> CATROID-1605: Crash when using geolocation sensors
